### ISSUE TITLE
BufferUtil/unsignedLocalIntersect2by2Cardinality() method always return 0

### ISSUE THREAD

**Issue by JunyuanZheng** [RoaringBitmap/RoaringBitmap#101]
unsignedLocalIntersect2by2Cardinality() method internal **pos** variable never chenge, might be a bug?

**Comment by lemire** [comment]
The code is a result of some copy and paste. The variable should be removed as it is leftover from other code where it serves to indicate where we write the intersection. Note that we should check whether the same thing happens elsewhere including in BufferUtil.

Want to issue a PR to clean this up?

**Comment by lemire** [comment]
+1 for spotting this mistake

**Comment by JunyuanZheng** [comment]
I think I need to remove the whole method right?

**Comment by lemire** [comment]
Let me add a unit test first.

**Comment by lemire** [comment]
@JunyuanZheng 

What you have uncovered is a genuine bug, but it escaped our unit tests up to now. I have now added tests that expose the bug.

I think we need to increment pos near this line...

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/buffer/BufferUtil.java#L718

Want to submit a PR?

**Comment by lemire** [comment]
Note that if you delete the method, the code won't build anymore.

**Comment by JunyuanZheng** [comment]
I will try to improve the coverage first. Need to study the algorithm first before changing the code.

**Comment by JunyuanZheng** [comment]
I will fix the issue on next Pull Request.

**Comment by lemire** [comment]
Excellent.
