### ISSUE TITLE
Bad Compression Results

### ISSUE THREAD

**Issue by StuartAxelOwen** [RoaringBitmap/RoaringBitmap#104]
Hey, I'm getting unimpressive compression results from some real user activity data.  From reading the paper, I expected compression between 3 and 50x, and I'm seeing just a little more than 1.1x.  Is there something I am doing wrong?  Is the bitmap in question of non-ideal density or distribution?

Here's the code I used to verify:

```scala
import java.nio.file.{Files, Paths}

import org.roaringbitmap.RoaringBitmap


object BitmapTest extends App {

  def toBitmapKeys(kv: (Byte, Int)): Seq[Int] = {
    val (bits, byteNum) = kv
    (0 to 7)
      .filter(shift => ((bits >> shift) & 1l) > 0)
      .map(_ + 8 * byteNum)
  }

  val rb = new RoaringBitmap()

  val allBytes = Files.readAllBytes(Paths.get("src/main/resources/example_bitmap.bin"))

  allBytes
    .zipWithIndex
    .flatMap(toBitmapKeys)
    .foreach(rb.add)

  println("Completed population")
  println(s"Population cardinality:                        ${rb.getCardinality}")

  println(s"Uncompressed bitmap size:                      ${allBytes.length}")
  println(s"Estimated bytes size of compressed bitmap:     ${rb.getSizeInBytes}")
  rb.runOptimize()
  println(s"Estimated bytes size of run-compressed bitmap: ${rb.getSizeInBytes}")

  println("Done!")
}
```

And the results:

```
stuarts-MBP:product-data stuart$ sbt run
[info] Loading project definition from /code/apptentive/explore/product-data/project
[info] Set current project to product-data (in build file:/code/apptentive/explore/product-data/)
[info] Compiling 1 Scala source to /code/apptentive/explore/product-data/target/scala-2.11/classes...
[info] Running BitmapTest
Completed population
Population cardinality:                        1784073
Uncompressed bitmap size:                      2961813
Estimated bytes size of compressed bitmap:     2641260
Estimated bytes size of run-compressed bitmap: 2633080
Done!
[success] Total time: 7 s, completed Apr 7, 2016 11:24:37 AM
```

The bitmap in question can be downloaded [here](https://s3.amazonaws.com/apptentive-engineering/example_bitmap.bin).

**Comment by lemire** [comment]
@StuartAxelOwen 

Thanks. Your example does not strike me as one that would typically be highly compressible using bitmap-compression techniques. However if you want fast decoding and encoding speed, and 5x compression, you can get this result with another library such as ``JavaFastPFOR``.

https://github.com/lemire/JavaFastPFOR/tree/master/examples/Axelbrooke

Though I have not investigated I do not think that there is any issue related to the software. There is no fault here... except for the fact that Roaring is not designed to offer high compression in such cases.

I am closing this, reopen if you disagree. You are invited to see if JavaFastPFOR suits your needs better.

**Comment by StuartAxelOwen** [comment]
Thank you for the thoughtful response!  I'll definitely check out JavaFastPFOR.

**Comment by lemire** [comment]
@StuartAxelOwen You made it easy because you provided a specific case. Too many people want to consider the problems abstractly which makes it very hard to come up with hard facts.
