### ISSUE TITLE
Serialization / deserialization with checksum

### ISSUE THREAD

**Issue by testn** [RoaringBitmap/RoaringBitmap#115]
It would be nice if we could allow some checksum into the serialization format so that it could help avoid potential bugs in serialization / deserialization and network corruption (the checksum should be done at the higher layer to detect that.

**Comment by lemire** [comment]
I am not sure it directly concerns the library. A checksum is something useful... but I don't think it should be included in the file format.

**Comment by testn** [comment]
Maybe I can use RoaringBitmap.hashCode to do so if it does not have too much overhead?

**Comment by lemire** [comment]
@testn If your data has been randomly corrupted, the deserialization could throw an exception, so you'll never make it to ``RoaringBitmap.hashCode``.

**Comment by lemire** [comment]
I am going to close this off. Please re-open if you have more details.
