### ISSUE TITLE
PeekableIntIterator.advanceIfNeeded does not work properly for certain numbers

### ISSUE THREAD

**Issue by joelchou** [RoaringBitmap/RoaringBitmap#120]
I have encountered a weird issue while using RoaringBitmap in a project to store documents IDs. 
It works fine mostly. But, in certain cases, it does not return documents it's supposed to, such as

RoaringBitmap bitmap = new RoaringBitmap();
bitmap.add(59798854);
bitmap.add(91274955);
bitmap.add(97569495);
bitmap.add(101993170);
PeekableIntIterator it = bitmap.getIntIterator();
it.advanceIfNeeded(100620278);

it.hasNext() returns false. But, it should not. I am using version 0.6.18. I tried 0.6.21 and it's still the same.

**Comment by lemire** [comment]
Thanks for the report.

**Comment by lemire** [comment]
Verified. Fixed has been committed.

**Comment by lemire** [comment]
Running validation now.

**Comment by lemire** [comment]
Fixed in 0.6.23. Please upgrade.
