### ISSUE TITLE
Create lightweight benchmarks that complete in minutes, not hours

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#126]
I think that our benchmarking is too slow. In C/C++, we benchmark against *many more alternatives*, and we measure many different things and it takes not even a minute. Our Java benchmarks are two orders of magnitude slower (taking *hours* to complete).

The problem with such complicated and slow benchmarks is that it basically discourage anyone from using them which basically means that there is no hope for our code to get faster. It is just too hard.

I think we need to start discussing lightweight benchmarks. Something you can run in a couple of minutes.

I think that JMH is at fault here. It is really a slow approach. It is fine for microbenchmarks, but not for the kind of work we do. We need something more lightweight, fast.

**Comment by gssiyankai** [comment]
What is the dataset used  in the C/C++ benchmarks ? The same as the Java ones ?

**Comment by lemire** [comment]
@gssiyankai 

Yes, the same...
https://github.com/RoaringBitmap/CBitmapCompetition

**Comment by lemire** [comment]
The datasets are really not large and they are static (immutable) so you need to load them once.

**Comment by lemire** [comment]
Resolved with one simple java program...
https://github.com/RoaringBitmap/RoaringBitmap/commit/3d09d665a0f1e6ab0f6e06f79bf871e821202344

**Comment by lemire** [comment]
@gssiyankai  The upside of my approach is that it is really fast and lightweight. Given a jar file anywhere, I can run a test in less than a minute.  The downside is that the results are noisier than I'd like. I am not exactly sure why it is the case. It is kind of bad that Java makes benchmarking so difficult.
