### ISSUE TITLE
JMH BITMAP_TYPES=ROARING_ONLY fail with java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#132]
Starting with commit 
https://github.com/RoaringBitmap/RoaringBitmap/commit/3e49972c6f4a465cbb945d5366b5796441619a79

our JMH unit tests are failing...

One can browse the error message on travis...

https://travis-ci.org/RoaringBitmap/RoaringBitmap/jobs/187494350

The error is not comprehensible... However, we can verify that it is not caused by travis... 

Indeed, running tests manually with 

```
mvn -f ./jmh/pom.xml test -DBITMAP_TYPES=ROARING_ONLY
```

fails with the same incomprehensible errors.... there is no debugging information that I can find...

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Tests run: 48, Failures: 0, Errors: 24, Skipped: 0, Time elapsed: 18.088 sec <<< FAILURE! - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
test[dataset=census-income, type=roaring, immutable=true](org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest)  Time elapsed: 0.049 sec  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
test[dataset=census-income, type=roaring_with_run, immutable=true](org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest)  Time elapsed: 0.029 sec  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
test[dataset=census1881, type=roaring, immutable=true](org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
test[dataset=census1881, type=roaring_with_run, immutable=true](org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest)  Time elapsed: 0.002 sec  <<< ERROR!
```

As far as I can tell, the missing method, ``java.nio.ByteBuffer.limit``, has been part of Java since Java 1.4, a really long time ago.

There is nothing in the above commit that should trigger any of this.

**Comment by lemire** [comment]
c.c. @gssiyankai

**Comment by lemire** [comment]
I am tempted to write our own benchmarking framework.

**Comment by gssiyankai** [comment]
I think it has something to do with maven dependencies. I cannot analyze the issue right now because I don't have my laptop with me but I'll have a look soon.

**Comment by lemire** [comment]
@gssiyankai  I went through our dependencies, pushing everything to the latest version, hoping that this will help.  Of course, it won't... but we might as well be running the latest maven plugins.

**Comment by gssiyankai** [comment]
@lemire 
You did most of the work of fixing the issue. I just reverted one of the maven plugin version upgrade. The build is now green!

**Comment by lemire** [comment]
@gssiyankai Great work!
