### ISSUE TITLE
Best way to copy a RoaringBitmap

### ISSUE THREAD

**Issue by Kineolyan** [RoaringBitmap/RoaringBitmap#144]
Hello everyone,

I am using the project RoaringBitmap in an application at work and trying to integrate RoaringBitmaps in it.
In that process, I am facing situations where our API needs to return a copy of the result.
For internal reasons, I can't just return the result of operations such as `RoaringBitmap#and(RoaringBitmap, RoaringBitmap)` and need to copy the result.

I see that the `RoaringBitmap` has no copy constructor - nor `RoaringArray`. There is a `#clone()` method, and I use it in some situation.
So far, my solution has been to create a new RoaringBitmap and using `#or(RoaringBitmap)` to copy all values. But I suppose that it is always heavier than just making a basic copy of the RoaringArray.

Thanks for the tips

**Comment by maciej** [comment]
@Kineolyan what's wrong with `RoaringBitmap.clone()` method?

**Comment by lemire** [comment]
@Kineolyan  As @maciej  may be hinting at... It is uncommon for Java classes to have "copy constructors". That's a C++ construct. In Java, we use "clone" instead.  A clone is equivalent for all practical purposes to a copy construction. I guess that doing a ``or`` with an empty bitmap would also work nearly just as well, though I expect it is going to be a tad slower.

**Comment by lemire** [comment]
I am going to close this as I believe it is an invalid issue. Reopen if you disagree.

**Comment by Kineolyan** [comment]
@lemire I hear you. Let me process your answer and see if I can rely only on clone.
So far, no need to reopen. Thanks for the answers.
