### ISSUE TITLE
Consider receiving Iterator<? extends RoaringBitmap> in FastAggregation functions

### ISSUE THREAD

**Issue by Kineolyan** [RoaringBitmap/RoaringBitmap#145]
Hello everyone,

could we consider replacing `Iterator<RoaringBitmap>` by `Iterator<? extends RoaringBitmap>` in all functions of FastAggregation ?
This is a common pattern used by classes consuming values - `List#addAll` for example.
This is already supported natively by the functions taking Arrays.

Regarding code compatibility, it does not break any API as it is an extension of the parameter constraints.

Best regards

**Comment by lemire** [comment]
Sounds reasonable but we would need to catalog all relevant instances... e.g. https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/RoaringBitmap.java#L654

Do you want to issue a PR?

**Comment by Kineolyan** [comment]
Ok. I will have a look at all the usages of Iterator in the code base and translate it when possible with wildcard.
I post the link to the PR when it is ready.

**Comment by lemire** [comment]
@Kineolyan If you could throw in a unit test to check that the extended usage does what one would expect (even if the test is silly) that'd be great.

**Comment by lemire** [comment]
I think that the PR solves this issue. It will be part of the next release.
