### ISSUE TITLE
xorCardinality and fuzzyEquals methods

### ISSUE THREAD

**Issue by openkappa** [RoaringBitmap/RoaringBitmap#149]
I have a use case where I want to know with very low latency whether the edit distance between two bitmaps is small, in which case they should be considered to be fuzzily equal. I would also like to be able to rank bitmaps by their edit distance from a given bitmap.

Currently it is possible to implement these functions using the method andCardinality() using the identities |a xor b| = |a or b| - |a and b| and |a xor b| < threshold, but there are numerous opportunities for optimisation by implementing the methods:

int xorCardinality(RoaringBitmap other);

boolean fuzzyEquals(RoaringBitmap other, int threshold);

Are these methods a welcome addition to the interface?

**Comment by lemire** [comment]
Of course. I think that there is no issue whatsoever with ``xorCardinality``.

For ``fuzzyEquals``, I would invite you to discuss it. I guess you want an API like that for performance issues? So that the computation can return false early without processing all of the data?

**Comment by openkappa** [comment]
Precisely - to return as soon as the threshold on edit distance is breached. Whether that's the kind of relation that was envisaged for this library, I don't know.

I will submit a pull request for xorCardinality this week.

**Comment by lemire** [comment]
> Precisely - to return as soon as the threshold on edit distance is breached. Whether that's the kind of relation that was envisaged for this library, I don't know.

Sure it is. What measure of "fuzzy equality" are you thinking about?

**Comment by openkappa** [comment]
Just the edit distance which is a bitwise xor. If |A xor B| < x then A and B are fuzzily equal. If the parameter x is set to zero then the relation becomes strict equality, which would seem consistent from an API point of view.

It's not much more effort to implement Jaccard distance which has |A or B| as a denominator.

**Comment by lemire** [comment]
> It's not much more effort to implement Jaccard distance which has |A or B| as a denominator.

It is harder to bail out early though, no?

**Comment by lemire** [comment]
My main worry is one of terminology. We want to make sure that the API is intuitive. I am not sure ``fuzzyEqual`` is the best term, though maybe it is.

What you are actually measuring is the Hamming distance. (I think that the edit distance usually refers to strings.) So what about ``hasSmallHammingDistance``?

https://en.wikipedia.org/wiki/Hamming_distance

**Comment by openkappa** [comment]
It could be poor terminology on my part.

The [edit distance](https://en.wikipedia.org/wiki/Edit_distance) defined on a language of {0,1} would consider the set {1,2,3} to have a distance of 1 from  {1,2,3,4}, {1,2,3,5} when encoded as the bit strings 001110, 011110  and 101110, because in either bit string only 1 bit must be flipped in order to make them equal to 001110. 

The function I have in mind would effectively answer questions like "can I convert A to B in fewer than n operations?" Its implementation would at a high level be |A xor B| < n? 

I never have strong opinions on names, but if the logic I have described is truly a Hamming distance it could indeed be called hasSmallHammingDistance.

**Comment by lemire** [comment]
@openkappa 

What you seem to be describing is the [Hamming distance](https://en.wikipedia.org/wiki/Hamming_distance), that is | A xor B |.

The Hamming distance between 00110011 and 110011 would be "8".

The edit distance between the strings 00110011 and 110011 would be "2" because you can either insert or delete two characters to get from one to the other.

 
It is much more difficult to compute the edit distance than the Hamming distance.

**Comment by lemire** [comment]
@openkappa  Of course, you can also interpret what you are describing as the edit distance, but I guess I am stressing how important it is to avoid confusion.

**Comment by openkappa** [comment]
I propose a function which computes the bitwise xor of two bitmaps iteratively and returns false as soon as a parametrised threshold is breached, and true if the threshold is not breached after consuming the two bitmaps. 

The interpretation that this function _verifies an upper bound on the number of bits that need to be flipped in either bitmap to make it equivalent to the other_ is perfectly sound and describes my motivation. However I have absolutely no preference on the name and find hasSmallHammingDistance acceptable.

**Comment by lemire** [comment]
@openkappa  Good. I am not sure how to best name it. It could be ``fuzzyEqual``  as you suggest.

c.c. @gssiyankai @owenkaser

**Comment by lemire** [comment]
Is this issue resolved?

**Comment by openkappa** [comment]
Yes absolutely

**Comment by lemire** [comment]
Resolved in release 0.6.41
