### ISSUE TITLE
rank of RoaringBitmap produces incorrect result

### ISSUE THREAD

**Issue by MiSawa** [RoaringBitmap/RoaringBitmap#158]
It looks like [this](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/RoaringBitmap.java#L1780) line should be `else if (Util.compareUnsigned(key, xhigh) == 0)`.
By this line,
```java
RoaringBitmap.bitmapOf(65537).rank(1)
```
returns not `0` but `1`.

**Comment by gssiyankai** [comment]
@MiSawa thanks for reporting the issue. Fixed with #159

**Comment by gssiyankai** [comment]
@lemire can you issue a new release, please ?

**Comment by lemire** [comment]
@gssiyankai  Ongoing.

**Comment by lemire** [comment]
Release done. Should appear on maven repo soon.
