### ISSUE TITLE
Transparently iterate over a subset

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#166]
I would like to make a very simple API suggestion for cases where a subset of a bitmap is iterated over. This is useful when implementing cursor based pagination. The code below:

```
RoaringBitmap bitmap = RoaringBitmap.bitmapOf(...);
PeekableIntIterator it = bitmap.getIntIterator();
it.advanceIfNeeded(cursor);
while (it.hasNext() && it.peekNext() < cursor + pageSize)) {
    doStuff(it.next());
}
```

would be replaced with:

```
RoaringBitmap bitmap = RoaringBitmap.bitmapOf(...);
PeekableIntIterator it = bitmap.getIntIterator(cursor, cursor + pageSize);
while (it.hasNext()) {
  doStuff(it.next());
}
```

Is there currently a better idiom than the first code snippet?

**Comment by lemire** [comment]
@richardstartin 

Your model assumes that you create a new iterator object for each page, right?

Wouldn't you want to call the iterator with an intuitive name, like``PagedIntInterator``?

**Comment by richardstartin** [comment]
@lemire Could do, it would stop uses of PeekableIntIterator from paying for this feature too.

This is in the wider context of a REST API where paged access to data is required, and sticky session state would be a non-solution since the API is load balanced. Solr is slightly different because the underlying data structure uses skip lists but the idea is similar to their API where you can supply a cursor to skip to without evaluating the preceding pages. 

I think the code in advanceIfNeeded is fast enough to seek to the start of a page (compared to an HTTP GET) but it might be faster to evaluate logical operations directly on subsets (defined by a first element and a page size or a supremum). Do you have any thoughts on that?

**Comment by lemire** [comment]
> I think the code in advanceIfNeeded is fast enough to seek to the start of a page (compared to an HTTP GET) but it might be faster to evaluate logical operations directly on subsets (defined by a first element and a page size or a supremum). Do you have any thoughts on that?

I am not sure what you mean by "evaluate logical operations directly on subsets". Can you give an example?

**Comment by richardstartin** [comment]
By logical operations I mean and, or, xor, andNot etc.

What I mean is 

```
RoaringBitmap x = RoaringBitmap.bitmapOf(...);
RoaringBitmap y = RoaringBitmap.bitmapOf(...);
RoaringBitmap page = x.and(y, cursor, pageSize);
PeekableIntIterator it = page.getIntIterator();
```

This would use the keys to skip to container containing cursor, and evaluate until the bitmaps are exhausted of the result has size pageSize.

**Comment by lemire** [comment]
One thing comes to mind. When you "page" results, you usually say "I want the next 50 results". They way you wrote your original code...

```
it.advanceIfNeeded(cursor);
while (it.hasNext() && it.peekNext() < cursor + pageSize)) {
    doStuff(it.next());
}
```

there could be anywhere from 0 to pageSize results. Is that what you mean?

**Comment by richardstartin** [comment]
No it is indeed not. The code was a portmanteau of pagination and another idea.
This is what I meant:
```
it.advanceIfNeeded(cursor);
int i = 0;
while (it.hasNext() && i++ < pageSize)) {
    doStuff(it.next());
}
```

**Comment by lemire** [comment]
@richardstartin Are you sure? What is the semantics of ``cursor``? Currently, in the code, ``advanceIfNeeded`` would move the iterator up to value ``cursor``, but it is not equivalent to skipping ``cursor`` values, which is maybe what you want. 

Note that the library does have rank/select queries, so it is possible to implement what I think you want efficiently, but I am pretty sure that the current iterator API does not support what you want. Hence my proposal to create a different iterator.

If I understand correctly what you want, I think a few hundred lines of easy code would do it, including testing.

**Comment by richardstartin** [comment]
The semantics of cursor are what you see here in the cursors section: https://cwiki.apache.org/confluence/display/solr/Pagination+of+Results 

One way to implement pagination is to pass the page number or a function of it (skip 150 results is equivalent to page 3 with page size 50). The problem is you have to iterate over those 150 results to skip them (basically a rank computation). An alternative mechanism is for you to tell me how many results you want, I start you off at zero, and I tell you where I got to (i.e. rank(pageSize)). When you call me for the next page you pass that cursor back to me, and I start your query at cursor. So advanceIfNeeded is what I'm after. RoaringBitmap is not a paginated REST API, but I think these semantics for paged query evaluation are appropriate (and available in Solr/Lucene).

**Comment by lemire** [comment]
Ok.  Then this code is assuredly wrong...

```
PeekableIntIterator it = bitmap.getIntIterator(cursor, cursor + pageSize);
while (it.hasNext()) {
  doStuff(it.next());
```

If I understand correctly,  ``cursor`` is a value whereas ``pageSize`` is a count. So you can't add them. I *think* that what you are proposing is to incorporate the counter within ``PeekableIntIterator`` so that this code...
 
```
it.advanceIfNeeded(cursor);
int i = 0;
while (it.hasNext() && i++ < pageSize)) {
    doStuff(it.next());
}
```

can become, more or less, like this...


```
it.setCount(pageSize);
it.advanceIfNeeded(cursor);
int i = 0;
while (it.hasNext()) {
    doStuff(it.next());
}
```

where maybe the ``setCount`` and ``advanceIfNeeded`` are called by a special constructor.

Am I right?

**Comment by richardstartin** [comment]
Here is something more concrete. It is a crude evaluation of the next page of results of an intersection after some minimal element.

```
public static RoaringBitmap and(RoaringBitmap x1,
                                  RoaringBitmap x2,
                                  int cursor,
                                  int count) {
    RoaringBitmap answer = new RoaringBitmap();
    final int length1 = x1.highLowContainer.size();
    final int length2 = x2.highLowContainer.size();
    int consumed = 0;
    final short firstKey = Util.highbits(cursor);
    final short containerOffset = Util.lowbits(cursor);
    short key = firstKey;
    while (consumed < count && key < length1 && key < length2) {
      Container c1 = x1.highLowContainer.getContainer(key);
      Container c2 = x2.highLowContainer.getContainer(key);
      if  (null != c1 && null != c2) {
        Container c = c1.and(c2);
        if (key == firstKey && containerOffset > 0) { // switch off the bits covered in the last page
          c = c.iandNot(new RunContainer().add(0, containerOffset));
        }
        int card = c.getCardinality();
        if (consumed + card > count) { // filled the page, but must switch off the last bits of the container
          int selection = card - (count - consumed);
          c = c.iandNot(new RunContainer().add(c.select(selection), c.last()));
        }
        if (card > 0) {
          answer.highLowContainer.append(key, c);
          consumed += card;
        }
      }
      ++key;
    }
    return answer;
  } 
```

With a simple test to illustrate a paging mechanism.

```
@Test
  public void testPagedAnd() {
    RoaringBitmap x1 = RoaringBitmap.bitmapOf(1, 2, 3, 5, 9, 100, 1 << 16, 1 << 16 | 1, 1 << 16 | 256, 1 << 17, 1 << 17 | 1);
    RoaringBitmap x2 = RoaringBitmap.bitmapOf(2, 4, 5, 10, 100, 1 << 16, 1 << 16 | 1, 1 << 16 | 3, 1 << 16 | 256, 1 << 17, 1 << 17 | 1);
    RoaringBitmap result1 = RoaringBitmap.and(x1, x2, 0, 3);
    Assert.assertEquals(RoaringBitmap.bitmapOf(2, 5, 100), result1);

    int cursor = result1.last() + 1;

    RoaringBitmap result2 = RoaringBitmap.and(x1, x2, cursor, 3);

    Assert.assertEquals(RoaringBitmap.bitmapOf(1 << 16, 1 << 16 | 1, 1 << 16 | 256), result2);

    RoaringBitmap result3 = RoaringBitmap.and(x1, x2, result2.last() + 1, 3);

    Assert.assertEquals(RoaringBitmap.bitmapOf(1 << 17, 1 << 17 | 1), result3);
  }
```

Then you do not need to implement paging at the iterator level, you can do it by paging the results of query operations. The idea is that it would be useful for skipping large sections of the bitmaps when paging a result set statelessly.

**Comment by lemire** [comment]
OK. I understand the semantics from your code, but I don't understand the motivation.

>Then you do not need to implement paging at the iterator level, you can do it by paging the results of query operations.

What is wrong with handling the paging at the iterator level?

**Comment by richardstartin** [comment]
It needs benchmarking but it seems wasteful, if you want 1000 points and know where to start from, to intersect or unite a few bitmaps of say 25 million points to throw away most of the result. If you have a verbatim materialised bitmap you want to query without modifying, then the iterator is not wasteful.

**Comment by lemire** [comment]
Ah. Got it.

Your proposed ``and`` function would solve the problem where you need to compute the intersection between two bitmaps. If paging through such a result is an important use case, then your proposal makes sense. You pretty much have the code already so you could turn it into a PR easily. Good.

Of course, we have to be aware of its limitations as well. Suppose that the query involves computing the union of 100 bitmaps (not atypical) then what?

**Comment by richardstartin** [comment]
The code above is a toy example for one type query, but once you bound the range of containers the pages should be in you can stick them in a priority queue to minimise the number of intersections/unions performed. If the query computes the union of 100 bitmaps then at least you have a bound for the size of the output bitmap and you can't be worse off than when operating on the entire bitmaps.

**Comment by lemire** [comment]
@richardstartin  You might enjoy this paper:

Compressed bitmap indexes: beyond unions and intersections
Software: Practice & Experience 46 (2), 2016
https://arxiv.org/abs/1402.4466

**Comment by richardstartin** [comment]
I see, this one's in English. Do you have the source code for the EWAH implementation of RBMrg?

**Comment by lemire** [comment]
https://github.com/lemire/javaewah/tree/master/src/main/java/com/googlecode/javaewah/symmetric

**Comment by richardstartin** [comment]
This is a very interesting paper, thanks for the link. I assume this repository is the code referred to in the paper: https://github.com/lemire/BitSliceIndex. Do you interpret pagination as a threshold problem? I don't see the direct connection. 

I've prototyped paginated and, or, xor and andNot on a [branch](https://github.com/richardstartin/RoaringBitmap/tree/pagination). My motivation to paginate queries to a structure like you see I prototyped in February [here ](https://github.com/richardstartin/isometric/blob/master/index/src/main/java/com/openkappa/isometric/index/bitslice/RangeEncodedOptBitSliceIndex.java) based on [this paper](http://www.comp.nus.edu.sg/~chancy/sigmod98.pdf) which I use to index continuous regions of a coordinate space. So my implementations do not currently satisfy my needs: If I page access to the individual slices then I may not get a full page of the index. I also don't really care about intersecting or uniting lots of bitmaps because I think the need to do that could be obviated with an appropriate encoding. However, I like the idea of a similar interface to Adder or Thresholder which can generalise a paginated access pattern, which could support more than two input parameters, and would allow generic _boolean circuits_ to be evaluated with direct access to the containers and RoaringArray. Is this where you were going with the link to the paper?

**Comment by lemire** [comment]
Yes, the threshold queries were chosen to motivate and focus the work, but one of the underlying idea is that you can aggregate bitmaps either vertically or horizontally with different trade-offs.

**Comment by richardstartin** [comment]
I think I understand- if I need paginated access I could just index the data rotated by 90 degrees where one bitmap is a horizontal page, the nth container in that bitmap is logically a page of the nth vertical bitmap in the index. Then there could be methods like verticalOr, verticalAnd etc. Which take a single bitmap and reduce the containers. Indeed a vertical and horizontal index could share containers. In that case I don't think there's any point in creating a PR for my paginated pairwise Boolean functions.
