### ISSUE TITLE
Iterator returned from iterator() does not behave correctly if remove() is called on it

### ISSUE THREAD

**Issue by trejkaz** [RoaringBitmap/RoaringBitmap#171]
```
    @Test
    public void testRoaringFailure() throws Exception
    {
        MutableRoaringBitmap bitmap = new MutableRoaringBitmap();
        bitmap.add(1);
        bitmap.add(2);

        Iterator<Integer> i = bitmap.iterator();
        assertThat(i.hasNext(), is(true));
        assertThat(i.next(), is(1));
        i.remove();
        assertThat(i.hasNext(), is(true));
        assertThat(i.next(), is(2));
    }
```

This test fails, because the second call to `next()` returns `1`, even though we supposedly removed that element from the iterator.

This also means that if you have a `for`-loop using this iterator and someone is removing elements, the loop will run forever.

**Comment by lemire** [comment]
Thanks. Yes, remove is not implemented within iterators, I have modified the code so that it throws an UnsupportedOperationException, as it should. I'll open a distinct issue for this.

**Comment by lemire** [comment]
See https://github.com/RoaringBitmap/RoaringBitmap/issues/172

I have also issued a release with a fix for this, so that an exception is thrown when the user attempts to remove data. (We had a placeholder implementation which we did not expect users to call... this was uncautious.)
