### ISSUE TITLE
bitmapContainer.add is missing someting？

### ISSUE THREAD

**Issue by chenfenggang** [RoaringBitmap/RoaringBitmap#173]
I am learning the roaringbitmap code,and I find the function of  adding arrayContiner in bitmapContainer missing the judgment statment 。is right?
  @Override
  public ArrayContainer and(final ArrayContainer value2) {
    final ArrayContainer answer = new ArrayContainer(value2.content.length);
    int c = value2.cardinality;
    for (int k = 0; k < c; ++k) {
      short v = value2.content[k];
 //    if(this.contains(v)){
      answer.content[answer.cardinality] = v;
      answer.cardinality += this.bitValue(v);
//    }
    }
    return answer;
  }

**Comment by lemire** [comment]
Yes, it is a branchless routine... the commented out code tells you about the logic of the code, but we avoid the branching.

Check the bitValue function.

If you think that there is a bug, please provide a test.
