### ISSUE TITLE
does roaring bitmap have compression? or some optimization?

### ISSUE THREAD

**Issue by yiguolei** [RoaringBitmap/RoaringBitmap#174]
I am testing roaring bitmap,  I insert 10,100,1000,10000,100000 values into bitmap and then calculate the memory usage. I found the roaring bitmap does not have compression.
num values      memory usage
10                     360  
100                   21600  
1000                 201600  
10000               820800  
65536               820800  
100000             1640800  

for example, case 10000. the roaring bitmap simply use [65536] bits to store the number, and all bits after 10000 is zero, but roaring bitmap does not compress it. 

Any optimization I missed?

**Comment by yiguolei** [comment]
one optimization I could found is roaringbitmap should allow user specify max value. Currently, the bitmap container initialize the bitmap using long[65536/4]. When max value is specified, the bitmap will be very small. It will save lots of memory.

**Comment by ppiotrow** [comment]
Hi @yiguolei , you should first understand idea of array and bitmap containers. I recommend https://arxiv.org/pdf/1402.6407.pdf as an introduction.

**Comment by yiguolei** [comment]
I know the array container, bitmap container and run container. but I found bit map container always allocate 65536/4 long arrays, and the trim method in bitmap container is empty.

**Comment by yiguolei** [comment]
`@Override
  public Container add(final short i) {
    final int x = Util.toIntUnsigned(i);
    final long previous = bitmap[x / 64]; why using x/64 here, this will cause the 1s and 0s very discrete.
    long newval = previous | (1L << x);
    bitmap[x / 64] = newval;
    if (USE_BRANCHLESS) {
      cardinality += (previous ^ newval) >>> x;
    } else if (previous != newval) {
      ++cardinality;
    }
    return this;
  }`

**Comment by yiguolei** [comment]
@ppiotrow

**Comment by richardstartin** [comment]
@yiguolei

Containers cover disjoint sets of a fixed length 1<<16. That's why you can't change the size. BitmapContainer is only used for dense regions without runs. If you can provide a test case where BitmapContainer is created where the data isn't dense, I am sure this would be gladly received.

Regarding compression, there are two main ideas: 

prefix compression to save _up to_ 16 * 2^16-1 bits per container. This has more effect when containers are dense.

Run length encoding. From my personal benchmarks this is the killer feature of roaring in terms of both space and time. If you measure with random data you'll get no runs. For the best results implement a lexical or Gray code sort on your data first, but your actual data is likely to contain many runs, because your actual data isn't random.

**Comment by yiguolei** [comment]
@richardstartin 
In a bitmap container, every value is between 0 -- 1<<16 or 65536 and every bitmap container allocates 65536 bits. But the max value in my case is 10000 and I know it is the max value, so that I only need 10000 bits in the bit map container, but I found bitmap container always allocate 65536 bits. It wastes a lot of memory.

Anything wrong?

**Comment by lemire** [comment]
Can you provide us with your actual use case? It is harder to discuss issues in the abstract. It seems that in your use case, your values span a small range (0,a) for 'a' small. In such cases, I recommend you use Java's BitSet class.

Roaring is meant to address different scenarios.

You are correct that bitmap containers have a fixed size (64KB) as opposed to a range (e.g. from a to b). Please see the format specification...

https://github.com/RoaringBitmap/RoaringFormatSpec/blob/master/README.md

I should point out that we are not likely to change the format at this time. It has proven very successful in many important cases.

If you could give us access to actual sets from your use case, we could more easily discuss whether Roaring is appropriate for you.

**Comment by lemire** [comment]
I am going to close this for now. Please re-open if you have a documented use case, with actual realistic data, that you wish to discuss further.
