### ISSUE TITLE
IntIterator.clone() causes NullPointerException sometimes

### ISSUE THREAD

**Issue by leventov** [RoaringBitmap/RoaringBitmap#177]
E. g. in `ImmutableRoaringBitmap.ImmutableRoaringReverseIntIterator`, if there are no elements, `iter` field is not initialized (remains `null`), and `clone()` fails with `NullPointerException` at `this.iter.clone()`.

**Comment by lemire** [comment]
@leventov  Would you kindly review this commit?

https://github.com/RoaringBitmap/RoaringBitmap/commit/3a1bb7ceb86ea48ba62c0ca39960412f325fcc4f

When you approve of it, I will issue a release and close the issue.

**Comment by leventov** [comment]
@lemire LGTM
