### ISSUE TITLE
benchmarks depends on latest available RoaringBitmaps available

### ISSUE THREAD

**Issue by ppiotrow** [RoaringBitmap/RoaringBitmap#178]
When one runs benchmarks via `run.sh` on the outdated feature branch the codebase is published as let's say `0.6.45-SNAPSHOT`. If in the mean time the newest version was released (e.g..`0.6.50`) https://github.com/RoaringBitmap/RoaringBitmap/releases then it will be used in the class path for the benchmark.
I've been hit by that while working on https://github.com/RoaringBitmap/RoaringBitmap/pull/169 and noticing no improvement with the changes (and I knew there were here a months ago when I've started). And I suppose it might hit me when I was working on iterators performance merge request - which I decided to close because of benchmarks.

**Comment by lemire** [comment]
I am not sure I understand the issue. Are you able to identify the fault in the script?

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/jmh/run.sh

**Comment by lemire** [comment]
c.c. @gssiyankai

**Comment by gssiyankai** [comment]
@ppiotrow 
If I understand correcltly your point, you mean that your local version of RoaringBitmap was `0.6.45-SNAPSHOT` while a more recent release version `0.6.50` was available on maven central ?
If so, I agree that you are not benchmarking `0.6.45-SNAPSHOT` but  `0.6.50` and of course there is no difference between 2 runs.
Still, I don't think this is an issue. IMHO, you should merge master in your local branch more frequently. In the example given above, after merging, you would be benchmarking `0.6.51-SNAPSHOT` which is the most recent version overall.
In case you are in a situation where you cannot merge because you are in the middle of a long dev, I recommend you to run maven offline with `mvn -o ...`

**Comment by ppiotrow** [comment]
IMHO this is an issue. I used to run benchmarks that were checking local version of the codebase. I lack knowledge on how to define dependencies in maven. I could try to be always rebased with master but I could sometimes forget - which causes difficulties in development process - for me at least two times . Being not rebased is not explicitly stopping the `run.sh` script.

**Comment by gssiyankai** [comment]
The only solution I can see to avoid the difficulties you are referring to is to explicit set the version of RoaringBitmap in `jmh/pom.xml`. We already had a discussion about this:
https://github.com/RoaringBitmap/RoaringBitmap/commit/94ffa2a02c3404698b93bb69101418d770891686#commitcomment-20354923
We can reopen the discussion if you like.

**Comment by lemire** [comment]
@gssiyankai 

> The only solution I can see to avoid the difficulties you are referring to is to explicit set the version of RoaringBitmap in jmh/pom.xml.

We have been there before and it is harder than it seems (not saying that it is not possible!).



The script clearly leads the user (of the script) to believe that he/she will benchmark whatever gets built. It is unintuitive that it would pick up something other built. I think we can reasonably consider this to be a bug *in the script*. Or, at least, a dangerous limitation.

What we would need is...

1. Some way to query the version tag of what has been built...
2. Some way to query the version tag that will be used by JMH...


Sadly, maven does not seem to allow us to query such things.

I don't think it is the end of the story however. A bash script could compare the just built RoaringBitmap jar file, then look at the just built benchmark jar file and check that they have the same versions. It is fragile, but if it issues a warning that the user of the script cannot fail to see, then we are good.

**Comment by blasd** [comment]
Hello, if I allow myself interfering, I expect all pom versions to be aligned - in any situation. The usual way to managed this is to have a parent maven project with `packaging=pom`, referring underlying modules. Each release is done on the parent maven modules, leading to a pom version increment on each sub-modules.

Right now, the top maven module have `packaging-jar`. Changing this would require moving a lot of code. Not really nice for git histories, but quite trivial to do. An alternative, is to add a maven module with` packaging=pom` as sub-module as ensure the top module have it as parent, with the proper relativePath. Just the same, the new parent/subFolder module refers to the other modules with relative pathes. `mvn versions:set` or `mvn release ...` will need to be done over the parent/subFolder module.

Anyway, a clean solution (i.e. not querying versions in a bash script) will anyway require an additional pom with `packaging=pom` (@lemire I feel you can not get things clean and simple with maven without this `packaging=pom` additional pom.xml).

As an additional step, the root module can not have sonatype as parent, as it needs to have the new parent/subFolder as parent. I manage this by rather relying on 

    <groupId>org.sonatype.plugins</groupId>
    <artifactId>nexus-staging-maven-plugin</artifactId>

I unsure the understand if current travis behavior is fully satisfying or not.

I sketched this in https://github.com/RoaringBitmap/RoaringBitmap/pull/179

**Comment by lemire** [comment]
Thanks. Personally, I don't mind moving the files around as long as we give everyone hacking the code a chance to sync. In this instance, @ppiotrow is the one with suspended code contributions, but I don't think he would mean the files moving... his changes are quite localized and easy to track manually. 

Whatever we do, we definitively want to make sure that the travis tests keep on passing. Otherwise, it is a step backward.

**Comment by ppiotrow** [comment]
Git or me will manage to migrate my code to the new files.

**Comment by lemire** [comment]
@blasd  Right, so we can reorganize the directory structure.

**Comment by lemire** [comment]
I assumed that this is fixed.
