### ISSUE TITLE
Get random element from set

### ISSUE THREAD

**Issue by ljwagerfield** [RoaringBitmap/RoaringBitmap#186]
What's the most efficient way to implement something like `RoaringBitmap.random()`?

For example, `RoaringBitmap.first()` and `RoaringBitmap.last()` return the smallest and largest elements... but how would you obtain a random element?

Thanks in advance!

**Comment by blasd** [comment]
What about

    Random random = new Random();
    bitmap.select(random.nextInt(this.getCardinality()));

**Comment by lemire** [comment]
With the caveat that I think the code would not compile as is, I think that @blasd  has the correct answer.

Reopen if you disagree.

**Comment by ljwagerfield** [comment]
Excellent! Thank you :)

Do you happen to know the time complexity of this operation?

**Comment by lemire** [comment]
@ljwagerfield 

It is not constant time. If you repeatedly do this, it could become expensive. But even if the algorithm was formally constant time, you'd still be stuck with cache misses, due to the randomness.

If you need to do this a lot, in a tight loop, then I would suggest doing it differently. If you have an actual use case, we can discuss it.

**Comment by ljwagerfield** [comment]
We're doing this to randomly allocate a resource to an incoming request -- once allocated, the resource cannot be used by another request until it gets returned to the pool. Therefore `RoaringBitmap` seems like a good fit: we just assign each resource a contiguous ID, and we can effectively use the bitmap as a resource pool.

For various reasons, we don't want the resources that get assigned to the requests to appear deterministic (so queues/round-robin is off the table -- it must be random).

You say it's not constant, but is it better than linear? `O(logn)` perhaps? (he says, wishfully...)

**Comment by ljwagerfield** [comment]
Why we don't just use a standard `Set`:

We actually have many of these pools in existence: there's a central pool (the universal set of resources) and a pool per user (because they each have their own quotas).

Therefore we need _many_ pools, each initialised to _full_, which the users can then acquire elements from. A standard `Set` is out of the question, because it would require initialising each user's pool with all elements upfront -- so `O(N)` memory overhead for each new user, where `N` is the number of resources. `RoaringBitmap` seems ideal because you can assign all `N` resources to each user's pool, and the memory overhead is roughly `O(1)` per pool to begin with (due to the all `N` elements being contiguous integer values, they get compressed away).

**Comment by lemire** [comment]
@ljwagerfield 

Could you try running a small benchmark corresponding to your problem? If it looks too slow, get back to us with your code and we shall discuss it.

**Comment by ljwagerfield** [comment]
@lemire that's very much appreciated.

I just ran a small benchmark vs. a class I wrote _before_ learning about `RoaringBitmap` (I had hoped to replace my implementation with yours). However, in this _very particular_ use-case of "remove me a random element" it appears my existing solution is more performant.

Thank you again for offering to take a look 👍 

Happy to 'close' this one now :)

**Comment by lemire** [comment]
@ljwagerfield  Which data structure are you using right now?

**Comment by ljwagerfield** [comment]
It's just an array of integer pairs. I initialise each "pool" to full, so they start with `Array(Range(0,99))`. Then on my "random acquires" it's just a case of picking a random range in the array, and consuming a random value within the range. Consuming means either decrementing the `end`, incrementing the `start` or splitting the range in two.

Binary search is used when searching for a specific value.

**Comment by lemire** [comment]
@ljwagerfield  How do you pick the element at random?

**Comment by ljwagerfield** [comment]
```scala
val pool    = Array(Range(0,99), Range(120,525), Range(560,999))
val range   = pool[rnd % pool.length]
val element = range.start + (rnd % (range.end + 1))
...
// plus: house-keeping to remove the element.
...
```

So this particular solution provides `O(1)` for random lookup, and then worse-case `O(?)` for the removal of the element (i.e. if it picked a value in the middle of the `Range` it would need to split the `range` into two `range`s), where `?` is dependent on what type of mutable array implementation you're using -- you basically need to perform an `insert` as the new `Range` (if a split occurs) needs to come after the current `Range`.

**Comment by lemire** [comment]
@ljwagerfield So if you ever have...

```
var pool = Array(Range(0,99), Range(100,100))
```

then value 100 would be picked with probability 0.5, and all other values with probability 0.005.

That's ok?

Statistically, your approach is quite biased.

If you are not really interested in picking elements at random, you just want some vague notion of "not quite in order", then I can suggest even faster ways to do it that only require constant memory.

**Comment by ljwagerfield** [comment]
You know what, I hadn't even thought of that 🤔 

Yes, please do share!

**Comment by lemire** [comment]
@ljwagerfield 

This should be fairly fast...

https://lemire.me/blog/2017/09/18/visiting-all-values-in-an-array-exactly-once-in-random-order/

It is certainly constant memory and constant time.  It could be tuned further.

It is not "statistically fair", but it should appear pretty much random to a naive observer. And it is going to be super fast! 
🚗  💨

**Comment by ljwagerfield** [comment]
Aha! Funnily enough, this is similar to a previous approach we considered: round-robin the items in pool, but in random order, and then change the order once you get to the end (so that the next pass is in a different random order). As you've highlighted, you just need to store an `index: Int` and possibly a `seed: Int` (which gets changed at the end of the pass), so is constant memory.

The problem in our case, is that each item in the pool can only be used by one consumer/worker: an item cannot be acquired again until it is released (i.e. no shared access to items). So we really do need a random-access pool.

With the approach highlighted in your blog post, if a worker acquires an item from the pool, and takes a longer time to process it than other workers, then the round-robin mechanism will double-assign that item to another worker.

This solution only works if all works / pool consumers use the items for exactly the same amount of time, otherwise items end up becoming shared (and we require each worker to have exclusive access to their item).

I'd be very surprised if this could be solved with constant memory, but I'm very keen to hear any other suggestions you have, given the full picture!

**Comment by lemire** [comment]
Ah! Ok, so it is a pool. Well, then you need ``O(n)`` bits in your data structure. It cannot be helped. Of course, if your coerce statistically the elements so that they form continuous clusters (which is what your above approach does) then you might be able to use fewer than ``O(n)`` bits in practice, at the expense of a large statistical bias. If the statistical bias is not a concern, then maybe your approach is hard to beat.

**Comment by ljwagerfield** [comment]
I wonder if there's an efficient way of performing a weighted module operation (of sorts) to get around the statistical biasing... I can think of one way, but it involves a binary search, so `O(log2n)` time and `O(c)` memory 🤔

**Comment by lemire** [comment]
If you have a random pool, it is not going to be efficient to represent it solely as ranges, like you did. I think that the reason the ranges are efficient, is because of the strong statistical bias you have introduced.

That is, the minute you get close to a half empty interval, if you picked the elements at random, a set of ranges won’t be close to optimal storage-wise.
