### ISSUE TITLE
Anybody working on nodejs version?

### ISSUE THREAD

**Issue by terrancesnyder** [RoaringBitmap/RoaringBitmap#187]
Anybody working on a nodejs version of this?

**Comment by lemire** [comment]
Not to my knowledge.

**Comment by lemire** [comment]
@SalvatorePreviti Seems to be working on it:

https://github.com/SalvatorePreviti/roaring-wasm

https://github.com/SalvatorePreviti/roaring-node

**Comment by lemire** [comment]
Closing.
