### ISSUE TITLE
Pre-compute cardinalities for faster .rank/.select

### ISSUE THREAD

**Issue by blacelle** [RoaringBitmap/RoaringBitmap#191]
My original usecase leading to implementing Roaring64NavigableMap relies massively on .rank and .select

Then, current Roaring64NavigableMap implementation holds a cache for cumulated cardinalities. I improved further my use-case by caching the cumulated cardinalities of underlying RoaringBitmap:

    new Roaring64NavigableMap(true, () -> new FastRankRoaringBitmap());

With current FastRankRoaringBitmap implementation

    public class FastRankRoaringBitmap extends RoaringBitmap {
	private int[] highToCumulatedCardinality = null;

	@Override
	public void add(long rangeStart, long rangeEnd) {
		highToCumulatedCardinality = null;

		super.add(rangeStart, rangeEnd);
	}

	@Override
	public void add(int x) {
		highToCumulatedCardinality = null;

		super.add(x);
	}

	@Override
	public void add(int... dat) {
		highToCumulatedCardinality = null;

		super.add(dat);
	}

	@Override
	public long rankLong(int x) {
		if (highToCumulatedCardinality == null) {
			highToCumulatedCardinality = new int[highLowContainer.size()];

			if (highToCumulatedCardinality.length == 0) {
				return 0;
			}
			highToCumulatedCardinality[0] = highLowContainer.getContainerAtIndex(0).getCardinality();

			for (int i = 1; i < highToCumulatedCardinality.length; i++) {
				highToCumulatedCardinality[i] =
						highToCumulatedCardinality[i - 1] + highLowContainer.getContainerAtIndex(i).getCardinality();
			}
		}

		short xhigh = Util.highbits(x);

		int index = Util.hybridUnsignedBinarySearch(this.highLowContainer.keys, 0, this.highLowContainer.size(), xhigh);

		boolean hasBitmapOnIdex;
		if (index < 0) {
			hasBitmapOnIdex = false;
			index = -1 - index;
		} else {
			hasBitmapOnIdex = true;
		}

		long size = 0;
		if (index > 0) {
			size += highToCumulatedCardinality[index - 1];
		}

		long rank = size;
		if (hasBitmapOnIdex) {
			rank = size + this.highLowContainer.getContainerAtIndex(index).rank(Util.lowbits(x));
		}

		// assert rank == super.rankLong(x);

		return rank;
	}

	@Override
	public int select(int j) {
		if (highToCumulatedCardinality == null) {
			highToCumulatedCardinality = new int[highLowContainer.size()];

			if (highToCumulatedCardinality.length == 0) {
				return 0;
			}
			highToCumulatedCardinality[0] = highLowContainer.getContainerAtIndex(0).getCardinality();

			for (int i = 1; i < highToCumulatedCardinality.length; i++) {
				highToCumulatedCardinality[i] =
						highToCumulatedCardinality[i - 1] + highLowContainer.getContainerAtIndex(i).getCardinality();
			}
		}

		int index = Arrays.binarySearch(highToCumulatedCardinality, j);

		int fixedIndex;

		long leftover = Util.toUnsignedLong(j);

		if (index == highToCumulatedCardinality.length - 1) {
			return this.last();
		} else if (index >= 0) {
			int keycontrib = this.highLowContainer.getKeyAtIndex(index + 1) << 16;

			// If first bucket has cardinality 1 and we select 1: we actual select the first item of second bucket
			int output = keycontrib + this.highLowContainer.getContainerAtIndex(index + 1).first();

			// assert output == super.select(j);

			return output;
		} else {
			fixedIndex = -1 - index;
			if (fixedIndex > 0) {
				leftover -= highToCumulatedCardinality[fixedIndex - 1];
			}
		}

		int keycontrib = this.highLowContainer.getKeyAtIndex(fixedIndex) << 16;
		int lowcontrib =
				Util.toIntUnsigned(this.highLowContainer.getContainerAtIndex(fixedIndex).select((int) leftover));
		int value = lowcontrib + keycontrib;

		// assert value == super.select(j);

		return value;

		// throw new IllegalArgumentException("select " + j + " when the cardinality is " + this.getCardinality());
	}
    }

Should such a "feature" be integrated in the core RoaringBitmap? If yes, should it be done by composition vs inheritance? If no, how could we make such an extention easier (e.g. for now, I need access to package-friendly variables, requiring to locate at least one class in roaringbitmap package)?

**Comment by lemire** [comment]
@blasd 

At a glance, it looks like something that could be merged as-is with the following caveats:

1. We need some documentation so people know right away what functionality is provided by the new class.
2. We need reasonably thorough testing.

**Comment by blasd** [comment]
I started working on the PR

**Comment by richardstartin** [comment]
I think this was completed in #192.

**Comment by lemire** [comment]
So it was.
