### ISSUE TITLE
ArrayContainer optimize

### ISSUE THREAD

**Issue by malin177** [RoaringBitmap/RoaringBitmap#204]
in ArrayContainer.writeArray(DataOutput out)，it is that：

> out.write(v & 0xFF);
> out.write((v >>> 8) & 0xFF);

I propose to update as：

> out.writeShort(Short.reverseBytes(v));

**Comment by malin177** [comment]
in ArrayContainer.writeArray(DataOutput out)，it is that：

> out.write(v & 0xFF);
> out.write((v >>> 8) & 0xFF);

I propose to update as：

> out.writeShort(Short.reverseBytes(v));

**Comment by lemire** [comment]
Good catch. Fixed in last commit.

**Comment by malin177** [comment]
It may need to updated
out.writeShort,
not is write.
What I meant was give the concrete implementation to a subclass.  
Ofcourse,if the test succeeds,it is ok and i will test!

**Comment by lemire** [comment]
Yes, thanks. It was typo which I fixed.
