### ISSUE TITLE
Dropping support for JDK 7 in upcoming releases

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#207]
We are about to drop support for JDK 7.

This seems uncontroversial at this point. 

* AWS supports java 8: https://aws.amazon.com/sdk-for-java/
* So does Google: https://cloud.google.com/appengine/docs/java/
* Apache Spark requires Java 8.
* Druid dropped support for java 7 it seems: https://github.com/druid-io/druid/blob/master/.travis.yml
* Kylin is on java 8 : https://github.com/apache/kylin/blob/master/.travis.yml

It seems that Pinot still tests on Java 7. So there might be some pain there when upgrading.
https://github.com/linkedin/pinot

Please chime in if you have concerns.

Ping @gssiyankai @blasd @Kineolyan @ppiotrow  @kishoreg @richardstartin ...

**Comment by maciej** [comment]
@lemire having Java 8 would open new possibilities for solving #42 (parallelization). Java 8 introduces [_CompletableFuture_](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) which might be helpful.

**Comment by kishoreg** [comment]
Pinot depends on Hadoop to for batch data ingestion and it's not clear to me that all Hadoop users have moved on to Java 8+. We would like to follow the major Apache projects such as Hadoop, Hive, Kafka etc. Do we know if they have dropped support for Java 7

**Comment by lemire** [comment]
@kishoreg 

[Hadoop requires Java 8 or better](https://github.com/apache/hadoop/blob/trunk/pom.xml#L151-L153)

Apache Hive no longer seems to support Java 7:

* [HIVE-16281: Upgrade master branch to JDK8 ](https://github.com/apache/hive/commit/c3aec12363b2e81d164fd97363a3eef966f50cd0)

[Lucene/Solr trunk moved to Java8](http://yonik.com/switch-java7-java8/).

[Kafka 3.0.0 supports Java 8. It does not support Java 7.](https://www.cloudera.com/documentation/kafka/latest/topics/kafka_requirements.html)


So, yeah, it looks like the ecosystem has moved to Java 8 and it is now safe to move to Java 7, but I'd prefer to have your ok since you are a major use case for Roaring.

In all cases, we will continue to support (as far as reported bugs go) older JDK7-only releases. So we won't force people to upgrade, but we would like future versions of Roaring to be able to assume JDK8, and that's where the new features will go.

**Comment by kishoreg** [comment]
That's great.  I will check with Uber team as well since they were on JDK 7 some time back. We will make the changes to Pinot to drop support for java 7.

**Comment by lemire** [comment]
Ok. I think we are safe enough.
