### ISSUE TITLE
Missing artefacts in maven central

### ISSUE THREAD

**Issue by Crystark** [RoaringBitmap/RoaringBitmap#220]
I see 0.7.0 is on maven central but not 0.7.1.
Any chance you can release it ?

Thanks

**Comment by lemire** [comment]
Fixed... thanks.

**Comment by richardstartin** [comment]
[Is it?](https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap)

**Comment by blasd** [comment]
Yes: [http://central.maven.org/maven2/org/roaringbitmap/RoaringBitmap/0.7.1/RoaringBitmap-0.7.1.pom](url)

mvn-central webpage needs more hours to refresh itself.

**Comment by richardstartin** [comment]
My bad!

**Comment by ppiotrow** [comment]
I can't find versions `0.7.6` and `0.7.7` https://repo.maven.apache.org/maven2/org/roaringbitmap/RoaringBitmap/

**Comment by lemire** [comment]
I am aware. The maven repo times out. Investigating.

**Comment by lemire** [comment]
I flushed them out manually. They should appear online soon.

There seems to be a non-trivial amount of hacking involved. This is discouraging.
