### ISSUE TITLE
Avoid double copy in in-place array OR

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#225]
This code in in-place OR within the ArrayContainer class involves a duplicate copy:

```
    if(totalCardinality >= content.length) {
      increaseCapacity(totalCardinality);
    }
    System.arraycopy(content, 0, content, value2.cardinality, cardinality);
```

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java#L658-L661

It also occurs in the iadd method. It is also possible that the remove method has duplicate copies.
We should hunt down such code.

**Comment by amitdesai03** [comment]
Hi Lemire, I am new to open source and wanted to participate. My recent project involved heavy use of roaring bitmap and have been exploring internals of it for while. If its ok with you, i would love to take stab at fixing this.

**Comment by lemire** [comment]
That's an excellent idea. Go ahead and prepare a pull request.

**Comment by amitdesai03** [comment]
Appreciate your welcome gesture for newbies. I have submitted PR. Please review. I did run all tests and benchmarks, but not sure where to see performance to compare.

**Comment by lemire** [comment]
@amitdesai03  Looking at your code, I don't think you are such a newbie.

**Comment by amitdesai03** [comment]
@lemire thanks, I have been developer for decade now, just new to open source :)
Also really admire the work you guys have done with roaring. Lot to learn, just looking at it.

**Comment by lemire** [comment]
@amitdesai03 

> I have been developer for decade now

Yes. That's more like what I expected.

> just new to open source

There is still much to improve in Roaring.

**Comment by lemire** [comment]
I'll open a separate issue for iadd.
