### ISSUE TITLE
JUnit performance tests

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#228]
There seem to be various performance tests in unit tests. These don't just produce unreliable results, they skew coverage metrics. I suggest we delete them.

**Comment by lemire** [comment]
Can you be more specific regarding your proposal?

**Comment by richardstartin** [comment]
Yes - I suggest removing any test claiming to be a performance test (a few do, and some don't make any assertions at all) to the jmh module.

I have submitted a dummy PR to observe the impact of removing the tests called "perfXXX" or "performanceXXX". Things like memory stability can be better measured with `-prof gc` too.

My motivation is build speed. On that note, and it's a much bigger factor to build time, I find the fuzz tests frustratingly slow, I suggest they be placed under a special profile and run them only on merge.

**Comment by lemire** [comment]
@richardstartin Why did you close this?

I very much share your concerns regarding build speed.

I recommended merging some PRs that you might have opposed on this basis, but it is not an indication that I disagree with you on the end goal. There are trade-offs: many different goals... and we can both add tests and pursue the goal of having faster builds.

I think getting a great build speed is of great importance.

Can we either reopen this or open a similar PR?

**Comment by richardstartin** [comment]
I felt that since recent pull requests have gone in precisely the opposite direction to the aim stated above that it would be better to remove this objection rather than to advocate for the deletion of work considered useful by other users of the library.
