### ISSUE TITLE
Avoid double copy in in-place array add

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#231]
This code in in-place add within the ArrayContainer class involves a duplicate copy:

    if (newcardinality >= this.content.length) {
      increaseCapacity(newcardinality);
    }
    System.arraycopy(content, indexend, content, indexstart + rangelength, cardinality - indexend);

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java#L461-L464

The same problem occurs in the corresponding buffer class.

This is a follow up to https://github.com/RoaringBitmap/RoaringBitmap/issues/225

**Comment by amitdesai03** [comment]
This one was tricky to implement.
Here is gist which passes all tests.
I am not sure how to run benchmark against it.

https://gist.github.com/amitdesai03/495c99432c0b0c60987daaaa728f2d33

If you approve of it, i will remove all comments and submit clean PR.

**Comment by richardstartin** [comment]
@amitdesai03 it might be better just to submit a PR anyway, the difference is clearer to see that way.

**Comment by lemire** [comment]
Can you follow @richardstatin’s advice?

**Comment by amitdesai03** [comment]
@richardstartin @lemire  absolutely, here you go:
https://github.com/RoaringBitmap/RoaringBitmap/pull/232

**Comment by lemire** [comment]
Fixed by PR https://github.com/RoaringBitmap/RoaringBitmap/pull/232
