### ISSUE TITLE
Test deserialization with adversarial inputs

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#233]
We have input files ``crashproneinput1``, ..., ``crashproneinput7``  that have been engineered to stress the deserialization routines (make the program crash).

https://github.com/RoaringBitmap/CRoaring/tree/master/tests/testdata

We should include them in our unit tests.

**Comment by richardstartin** [comment]
Has this been implemented?

**Comment by lemire** [comment]
Yes. I just did... it wasn't much work...
https://github.com/RoaringBitmap/RoaringBitmap/commit/50515ad921d2c2c2232d7b8a5ffff7af36218696
