### ISSUE TITLE
Implement faster and more convenient "intersects with interval" checks

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#235]
Currently, if I want to test whether a bitmap has values contained in an interval, I have to do something ugly like this:

```
        // some bitmap
        RoaringBitmap rr = RoaringBitmap.bitmapOf(1,2,3,1000);

        // we want to check if it intersects a given range [10,1000]
        int low = 10;
        int high = 1000;
        RoaringBitmap range = new RoaringBitmap();
        range.add((long)low, (long)high + 1);
        //
        //

        System.out.println(RoaringBitmap.intersects(rr,range)); // prints true if they intersect
```

This is not optimal, if only because we have to create a temporary bitmap.

**Comment by richardstartin** [comment]
Might it be worthwhile to implement various operations, such as union and intersection, with intervals? It would make it much cheaper to use an "existence bitmap" representing the extent of an indexed data set.

**Comment by lemire** [comment]
I think we have, de facto, unions with intervals, in the sense that we have a ranged adds. We also have intersections with ranged removes. And we have ranged XOR with flips. Of course, it might be convenient to repackage these operations in a nicer way.

We don't have a way to check that the interval is empty without doing something like I described... which is obviously not ideal.

**Comment by richardstartin** [comment]
But they take up a fair amount of space, much more than just 64 bits, no?

**Comment by lemire** [comment]
> But they take up a fair amount of space, much more than just 64 bits, no?

I am not sure what you mean.

**Comment by richardstartin** [comment]
You can represent a range, say, `[0, 2^31)` with two 32 bit integers. The equivalent bitmap would need 2^15 keys, and 2^15 `RunContainer`s each with a `short[2]` and a `short`.

**Comment by lemire** [comment]
This solution...

```
        RoaringBitmap range = new RoaringBitmap();
        range.add((long)low, (long)high + 1);
        RoaringBitmap.intersects(rr,range);
```

has the problem you describe, which is why I raise it as an issue requiring further work.

**Comment by lemire** [comment]
Fixed fast and furiously by @richardstartin 

https://github.com/RoaringBitmap/RoaringBitmap/pull/236
