### ISSUE TITLE
Changelog/release notes

### ISSUE THREAD

**Issue by testn** [RoaringBitmap/RoaringBitmap#238]
Is it possible to have an official changelog/release notes maintained? It is quite difficult to grok it from the git commit.

**Comment by lemire** [comment]
We had a maintained changelog and it was removed in favor of the git commit.

When reviewing many major open-source projects primarily hosted on GitHub, I find that they do not have changelogs.

I am honestly not sure how a changelog file could do better than the commit list:

https://github.com/RoaringBitmap/RoaringBitmap/commits/master

Do you have specific proposals?

**Comment by testn** [comment]
I'm fine with git commit. However, sometimes, the versions were bumped without any code changes and some of the commits did not have a clear git commit message making it a little bit hard to grok.

**Comment by lemire** [comment]
We had lots of trouble with the release process which lead to missing/botched releases. Hopefully, these problems are behind us.

I am going to close this. We will work on maintaining good logs and meaningful releases.
