### ISSUE TITLE
Check for reference equality before aggregating containers

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#248]
It may be helpful to add a reference equality check at the start of some methods on `Container`, e.g.

```java
public Container or(Container other) {
    if (this == other) {
         return this;
    }
    ...
}

**Comment by lemire** [comment]
When would this condition fire?

**Comment by richardstartin** [comment]
I don't think this is possible if containers are used within the library. We can close this - sorry.
