### ISSUE TITLE
RunContainer::contains(ArrayContainer) throws Exception due to off by one termination check

### ISSUE THREAD

**Issue by sesuncedu** [RoaringBitmap/RoaringBitmap#254]
The while loop in this method has a termination condition checks for run indexes <= numberOfRuns(), which is incorrect. 

Additionally, the return value is computed incorrectly.

I have a patch for this- I just need to add a unit test (I probably ought to check the methods for the other container types as well).

Addendum:  The existing test does not trigger this error as the relevant check tests for containment with a putative subset larger than the putative set. This short circuits the precise containment logic.

Further addendum: Because the valuesLength array is sized to hold four runs, the code will not throw an exception unless the array is full (e.g. if bitmap is trimmed or if the valuesLength array is filled).

**Comment by lemire** [comment]
Reopen if this is still an issue.
