### ISSUE TITLE
It is a bug ? about ArrayContainer

### ISSUE THREAD

**Issue by english207** [RoaringBitmap/RoaringBitmap#262]
**version is 0.6.66**
I have a test for ArrayContainer  :

`
Container arrayContainer = new ArrayContainer();
        Container arrayContainer2 = new ArrayContainer();

        BitSet bitSet = new BitSet();
        BitSet bitSet2 = new BitSet();

        for (int i = 2568; i < 8908; i++) {
            arrayContainer2.add((short) i);
            bitSet2.set(i);
        }

        for (int i = 0; i < 3568; i++) {
            arrayContainer.add((short) i);
            bitSet.set(i);
        }

        Container arrayContainer3 = arrayContainer.or(arrayContainer2);
        bitSet.or(bitSet2);

        System.out.println(arrayContainer3.toString());
        System.out.println(bitSet.toString());

        System.out.println(arrayContainer3.getCardinality());
        System.out.println(bitSet.cardinality());

`

but the result is ：
arrayContainer -- {0,1,2,3,4,5,6,7,8,9,10, ...... 6656,6657,6658,6659,6660,6661,6662,6663}
bitSet               -- {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ......8901, 8902, 8903, 8904, 8905, 8906, 8907}

why did arrayContainer lose those Numbers?？
Is there a problem with the way I use it ？

**Comment by ppiotrow** [comment]
Hi, you should not work with `ArrayContainer` directly but rather use `RoaringBitmap`.
In this case you missed that the code ` arrayContainer.add((short) i);` after reaching 4096 elements in the array container return the new `BitmapContainer` object.

**Comment by lemire** [comment]
@ppiotrow is correct. Try something like this instead...

    Container arrayContainer = new ArrayContainer();
    Container arrayContainer2 = new ArrayContainer();

    BitSet bitSet = new BitSet();
    BitSet bitSet2 = new BitSet();

    for (int i = 2568; i < 8908; i++) {
        arrayContainer2  = arrayContainer2.add((short) i);
        bitSet2.set(i);
    }

    for (int i = 0; i < 3568; i++) {
        arrayContainer = arrayContainer.add((short) i);
        bitSet.set(i);
    }

    Container arrayContainer3 = arrayContainer.or(arrayContainer2);
    bitSet.or(bitSet2);

    System.out.println(arrayContainer3.toString());
    System.out.println(bitSet.toString());

    System.out.println(arrayContainer3.getCardinality());
    System.out.println(bitSet.cardinality());

**Comment by english207** [comment]
@ppiotrow @lemire  i got it , thanks 👍
