### ISSUE TITLE
getLongSizeInBytes() implementation for Roaring64NavigableMap

### ISSUE THREAD

**Issue by arpang** [RoaringBitmap/RoaringBitmap#266]
Hi,

The getLongSizeInBytes() method of Roaring64NavigableMap class is marked as "Todo". Can someone please add the implementation or tell me the logic so that I can implement and raise a pull request?

**Comment by lemire** [comment]
I think it is meant to provide an estimate of the memory usage.

PR invited.

**Comment by lemire** [comment]
Closing: https://github.com/RoaringBitmap/RoaringBitmap/pull/267
