### ISSUE TITLE
Roaring64NavigableMap get wrong cardinality value after serialization and deserialization 

### ISSUE THREAD

**Issue by ShaoxiongTang** [RoaringBitmap/RoaringBitmap#273]
Follow is my serialization and deserialization code:
`        
       import org.roaringbitmap.longlong.Roaring64NavigableMap;

import java.io.*;
import java.nio.ByteBuffer;
import java.util.Random;

public class RoaringBitmapSizeChangeTest {

    public static void main(String[] args) throws IOException {
        Roaring64NavigableMap rbm = new Roaring64NavigableMap();
        Random random = new Random();
        for (int i = 0; i < 410000; i++) {
            rbm.add(random.nextLong());
        }
        System.out.println("origin rbm size " + rbm.getIntCardinality());

        // test
        ByteBuffer byteBuffer = ByteBuffer.allocate((int) rbm.serializedSizeInBytes());
        rbm.serialize(new DataOutputStream(new ByteBufferBackedOutStream(byteBuffer)));
        Roaring64NavigableMap rbmDeserialize = extractBitMap(byteBuffer);

        System.out.println("After serialize size " + rbmDeserialize.getIntCardinality());
    }

    private static Roaring64NavigableMap extractBitMap(ByteBuffer buffer) throws IOException {
        Roaring64NavigableMap rbm = new Roaring64NavigableMap();
        buffer.flip();
        rbm.deserialize(new DataInputStream(new ByteBufferBackedInputStream(buffer)));
        return rbm;
    }

    static class ByteBufferBackedOutStream extends OutputStream {

        ByteBuffer mBB;

        ByteBufferBackedOutStream(ByteBuffer mbb) {
            mBB = mbb;
        }

        public void close() {
        }

        public void flush() {
        }

        public void write(int b) {
            mBB.put((byte) b);
        }

        public void write(byte[] b) {
            mBB.put(b);
        }

        public void write(byte[] b, int off, int l) {
            mBB.put(b, off, l);
        }
    }

    static class ByteBufferBackedInputStream extends InputStream {

        ByteBuffer buf;

        ByteBufferBackedInputStream(ByteBuffer buf) {
            this.buf = buf;
        }

        public int read() throws IOException {
            if (!buf.hasRemaining()) {
                return -1;
            }
            return 0xFF & buf.get();
        }

        public int read(byte[] bytes) throws IOException {
            int len = Math.min(bytes.length, buf.remaining());
            buf.get(bytes, 0, len);
            return len;
        }

        public long skip(long n) {
            int len = Math.min((int) n, buf.remaining());
            buf.position(buf.position() + (int) n);
            return len;
        }

        public int available() throws IOException {
            return buf.remaining();
        }

        public boolean markSupported() {
            return false;
        }

        public int read(byte[] bytes, int off, int len) throws IOException {
            len = Math.min(len, buf.remaining());
            buf.get(bytes, off, len);
            return len;
        }
    }
}
`

**Comment by blacelle** [comment]
Thanks for the reproducing case. I shall have a look soon.

**Comment by rafael-telles** [comment]
@ShaoxiongTang @blacelle  If you change it to `new Roaring64NavigableMap(true)` (setting signedLongs to true) it works properly.

**Comment by lemire** [comment]
Closing, reopen if needed.
