### ISSUE TITLE
Cardinality in Range

### ISSUE THREAD

**Issue by DanielWe2** [RoaringBitmap/RoaringBitmap#278]
There is currently no fast/simple way to query the cardinality in a given range.

They only way I know is:
- create a new temp bitmap
- use add with range to fill the bits in the range to query
- use "and" with on the two maps and then call getLongCardinality

Am I missing something?

(also: There is no simple or and and operation with range parameters. I can open another issue for that)

**Comment by lemire** [comment]
Will be part of the next release as "rangeCardinality".

**Comment by lemire** [comment]
> (also: There is no simple or and and operation with range parameters. I can open another issue for that)

It should be pretty efficient to do something like this...

```
RoaringBitmap r = new RoaringBitmap();
r.add(begin,end);
mybitmap.or(r);//mybitmap.and(r);
```

You do create a "temporary" bitmap, but it should be quite cheap in most practical cases.

**Comment by lemire** [comment]
I am closing the issue. This has been fixed in the current release.
