### ISSUE TITLE
Implement bit shift functions

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#281]
See http://bitmagic.io/dna-search.html

**Comment by linasmwix** [comment]
Upvoted. FYI Bit Set (in general) shifts are also useful for subset sum / knapsack type of problems.
Although there are more efficient (in terms of complexity) solutions, Bit Sets can do wonders to the constant factor.

**Comment by lemire** [comment]
Thanks for pinging this issue. It has been implemented quite some time ago as `addOffset`.

Closing.
