### ISSUE TITLE
Drop support for Java 8?

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#289]
Java 8 is no longer receiving public updates. Our last few artefacts don’t work in Java 8 and there is no obvious way to ensure backward compatibility going forward.

**Comment by brharrington** [comment]
Oracle will not provide public updates anymore, however, there are some other distributions of jdk8 such as Amazon's Corretto that have a [longer support window](https://aws.amazon.com/corretto/faqs/#support).

For my uses, I can cope with jdk8 support being dropped, but it would be more convenient if it was still supported. At my company the transition to jdk11 will take quite a while.

**Comment by richardstartin** [comment]
I'm using Java 8 so I would be disappointed by dropping support for Java 8, because I won't be able to use the library any more without forking it.

On the other hand there some new and relevant intrinsic functions like `Arrays.mismatch` in Java 11. What about a Java 11 branch that can be released from, which could become master at some point in the future, but in the mean time enables usage of new language features?

**Comment by drcrallen** [comment]
Looking at the list of "used by" in https://github.com/RoaringBitmap/RoaringBitmap/blob/RoaringBitmap-0.7.26/README.md , it looks like some of them are may be stuck in the past for an unknown time.

Spark looks like it is trying to be java 11 compatible for 3.0.0 ?https://issues.apache.org/jira/browse/SPARK-24421 

Hadoop (Hive by proxy?) is not that close to java 11 support https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+and+Java+9%2C+10%2C+11 

Druid probably won't upgrade until Hadoop works: https://github.com/apache/incubator-druid/issues/5589 

And there are others as well. Is this ticket about the source code or the generated bytecode?

**Comment by brharrington** [comment]
> On the other hand there some new and relevant intrinsic functions like Arrays.mismatch in Java 11. What about a Java 11 branch that can be released from, which could become master at some point in the future, but in the mean time enables usage of new language features?

If it is only a change to the internals and not the public api, then a multi-release jar would probably be a better option. That way there is one artifact and the most optimal version can be used based on the JDK the user is running.

**Comment by lemire** [comment]
There is no support for this idea. Closing.

**Comment by richardstartin** [comment]
@brharrington I haven’t experience of multi release jars - is there anything to watch out for? There are four or five places the vectorised mismatch intrinsic would be relevant in this library- it might be worth the bother.
