### ISSUE TITLE
Disable javadoc on shims module

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#306]
The shims module only exists to facilitate testing both implementations of array equality, and we have a multi release jar so the vectorised intrinsic can be used in newer versions of Java. There seem to be compatibility issues with the javadoc plugin caused by recent changes in JDK11.0.1+. Since it is just an incidental inconvenience that shims needs to be released to ensure both versions are tested, I suggest we just disable javadoc.

**Comment by lemire** [comment]
That seems reasonable, no?

**Comment by richardstartin** [comment]
All modules are affected by [JDK-8212233](https://bugs.openjdk.java.net/browse/JDK-8212233). Skipping javadoc on shims just causes RoaringBitmap to fail with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project RoaringBitmap: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
```

The workaround seems to be not to generate javadoc: the fix in JDK12 hasn't been backported to JDK11 yet.

**Comment by lemire** [comment]
But it works in master. What causes the breakage in the new code you are working on?

**Comment by richardstartin** [comment]
It work_ed_ on master 2 months ago.

**Comment by richardstartin** [comment]
#308 demonstrates that master can no longer build using the version of JDK11 travis is using, I think the only way to merge PRs is to drop javadoc or JDK11 support.

**Comment by lemire** [comment]
Ok. And travis does not yet have the JDK 12 with the fix, right?

**Comment by richardstartin** [comment]
JDK12 is not released yet.

**Comment by lemire** [comment]
Ok. We are no longer testing on jdk11.

https://github.com/RoaringBitmap/RoaringBitmap/commit/ae2ee9fb1cfc1f40c0a8bad2fcb4012425a01e10

I am going to close this issue, reopen if you think it should remain open.
