### ISSUE TITLE
Unify line-endings to '\n'

### ISSUE THREAD

**Issue by incaseoftrouble** [RoaringBitmap/RoaringBitmap#312]
As discussed previously, line endings should be uniform throughout the codebase. A simple `dos2unix` call on all source files should fix this I guess.

**Comment by blacelle** [comment]
or proper .gitattributes

e.g.

```

# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.c text
*.h text

# Declare files that will always have CRLF line endings on checkout.
*.sln text eol=crlf
*.bat text eol=crlf
*.ps1 text eol=crlf

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
*.svg binary
```

**Comment by incaseoftrouble** [comment]
True. This seems like a cleaner solution. I'll try this and see what happens.

**Comment by blacelle** [comment]
Github provides a nice article regardint this case:

    https://help.github.com/en/articles/dealing-with-line-endings#refreshing-a-repository-after-changing-line-endings

**Comment by lemire** [comment]
I am delaying merging a PR where every file is modified (presumably due to line endings). This is somewhat unpleasant and one should be super careful because it can hide substantive changes. (There are ways to diff without whitespace, but it is still dangerous.)

**Comment by incaseoftrouble** [comment]
Will do.

**Comment by lemire** [comment]
+1

**Comment by lemire** [comment]
Closing.
