### ISSUE TITLE
Support Eclipse

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#317]
The README.md instructs developers to go into roaringbitmap and type `mvn eclipse:eclipse`. This no longer works for me because of ArrayShims:

```
$ mvn eclipse:eclipse
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------< org.roaringbitmap:RoaringBitmap >-------------------
[INFO] Building RoaringBitmap 0.7.39-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> maven-eclipse-plugin:2.10:eclipse (default-cli) > generate-resources @ RoaringBitmap >>>
[WARNING] The POM for org.roaringbitmap:shims:jar:0.7.39-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.613 s
[INFO] Finished at: 2019-02-26T08:58:34-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project RoaringBitmap: Could not resolve dependencies for project org.roaringbitmap:RoaringBitmap:jar:0.7.39-SNAPSHOT: Could not find artifact org.roaringbitmap:shims:jar:0.7.39-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Going into the root of the project does not work better:

```
$ mvn eclise:eclipse
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 6 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 6 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] RoaringBitmapParent                                                [pom]
[INFO] shims                                                              [jar]
[INFO] RoaringBitmap                                                      [jar]
[INFO] Real Roaring Dataset                                               [jar]
[INFO] JMH benchmark : RoaringBitmap                                      [jar]
[INFO] fuzz-tests                                                         [jar]
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 83 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 55 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] RoaringBitmapParent 0.7.39-SNAPSHOT ................ SKIPPED
[INFO] shims .............................................. SKIPPED
[INFO] RoaringBitmap ...................................... SKIPPED
[INFO] Real Roaring Dataset ............................... SKIPPED
[INFO] JMH benchmark : RoaringBitmap ...................... SKIPPED
[INFO] fuzz-tests 0.7.39-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.058 s
[INFO] Finished at: 2019-02-26T09:00:23-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'eclise' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/lemire/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

**Comment by lemire** [comment]
@richardstartin Can you help? I consider this problem to be a major usability issue. Even if one does not care about Eclipse, it is still one of the major IDEs and it cannot be used currently with this project.

**Comment by lemire** [comment]
Ok. Seems that Eclipse can't support this project. I will move to document how to make it work with IntelliJ.

**Comment by blacelle** [comment]
For the record, I work within eclipse without any specific issue. Still, `mvn eclipse:eclipse` was especially useful at the time maven eclipse integration (m2e) was not available or quite poor. Since quite many Eclipse releases, you should import a maven based within Eclipse with File/Import/"Existing Maven projects" the root folder.

**Comment by lemire** [comment]
I am a taker if you have instructions on how to open RoaringBitmap without errors.

Here is what I did just now with the very latest Eclipse:

- File 
- Import
- Existing Maven Projects
- Select RoaringBitmap on my disk
- I get `maven-antrun-plugin:1.3:run (1 errors) Execution compile-java11, in /shims/pom.xml`


Then I have 18 errors. At a glance, it still works, but the long list of errors remains.

That's not very reasonable for a newcomer who would like to contribute to the project. What are they to think of all these errors.

Now, if there is a way to make them go away, it would help.

**Comment by lemire** [comment]
I am re-opening the issue since there are reports that this can work in Eclipse.

**Comment by lemire** [comment]
If I try to disable jmh as I had to do with IntelliJ, I reduce the number of errors to only one. Better but still a bit scary.

I am not exactly sure why the jmh module creates so much trouble... because of the external dependencies?

**Comment by lemire** [comment]
@richardstartin 

You will be happy to know that neither IntelliJ nor Eclipse has major problems with the shims. It is jmh that they don't like. Still the remaining error seems related to the shims. How do you load up this project in an IDE?

**Comment by blacelle** [comment]
About Eclipse, the ant-run report is "expected" : Eclipse indicates he does not know how to behave properly give this quite custom behavior. One solution for Eclipse newcomers is to add in shims/pom.xml:

      ```
 <pluginManagement>
        	<plugins>
        		<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
        		<plugin>
        			<groupId>org.eclipse.m2e</groupId>
        			<artifactId>lifecycle-mapping</artifactId>
        			<version>1.0.0</version>
        			<configuration>
        				<lifecycleMappingMetadata>
        					<pluginExecutions>
        						<pluginExecution>
        							<pluginExecutionFilter>
        								<groupId>org.apache.maven.plugins</groupId>
        								<artifactId>maven-antrun-plugin</artifactId>
        								<versionRange>[1.3,)</versionRange>
        								<goals>
        									<goal>run</goal>
        								</goals>
        							</pluginExecutionFilter>
        							<action>
        								<ignore></ignore>
        							</action>
        						</pluginExecution>
        					</pluginExecutions>
        				</lifecycleMappingMetadata>
        			</configuration>
        		</plugin>
        	</plugins>
        </pluginManagement>
```

Then, my workspace looks functional:
<img width="416" alt="screenshot 2019-02-26 at 20 34 32" src="https://user-images.githubusercontent.com/2117911/53440934-fcadb200-3a05-11e9-9863-8f363a26cec2.png">

**Comment by blacelle** [comment]
Then, my workspace looks functional:
<img width="416" alt="screenshot 2019-02-26 at 20 34 32" src="https://user-images.githubusercontent.com/2117911/53441007-22d35200-3a06-11e9-99e3-8bb0ce7f0211.png">

**Comment by lemire** [comment]
This helps but I still get errors like this...

```
Project 'RoaringBitmapParent' is missing required library: '/Users/lemire/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar'
The container 'Maven Dependencies' references non existing library '/Users/lemire/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar'
```

And that's not even considering what happens if I don't close the jmh module.

How do I get Eclipse to grab its dependencies?

**Comment by lemire** [comment]
Note that I do have guava, alas not the version that Eclipse wants:

```
$ ls /Users/lemire/.m2/repository/com/google/guava/guava/
14.0.1 19.0   20.0
```

**Comment by lemire** [comment]
If I click on "dependencies", I find that it is using guava 20.

**Comment by lemire** [comment]
Interesting. So I had to do "project>clean" and now everything is ok.

**Comment by lemire** [comment]
Closing. Thanks to @blacelle

**Comment by blacelle** [comment]
Indeed, Project/Clean and or "Right-Click on folder/Working Set"/Maven/"Update project" helps Eclipse cleaning its configuration, handle changes in pom.xml and refresh what needs to be changes. The second step ("Right-Click on folder/Working Set"/Maven/"Update project") holds most on `mvn eclipse:eclipse`

**Comment by lemire** [comment]
I am an optimist and I thought that when faced with a configuration error, the IDE would either try to do the cleaning once to see if it helps, or just invite me to do so as part of an error message.

I need to learn to be a pessimist.

**Comment by lemire** [comment]
Closing.
