### ISSUE TITLE
How to read roaringbitmap  from database,such as greenplum ?

### ISSUE THREAD

**Issue by sydt2014** [RoaringBitmap/RoaringBitmap#318]
I create roaringbitmap data in greenplum, but how to read these data by JDBC in java and create roaringbitmap object ?And how to write roaringbitmap into database ,such as greenplum?

**Comment by lemire** [comment]
You can, for example, store an array of bytes in your database... You’ll find plenty of examples online...

https://stackoverflow.com/questions/15134357/storing-a-byte-array-in-ms-sql

**Comment by lemire** [comment]
Then serialize and deserialize bitmaps to byte arrays, see this example...

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/examples/SerializeToByteArrayExample.java

**Comment by lemire** [comment]
If you need support specifically with greenplum please see the greenplum developers.

**Comment by lemire** [comment]
Closing. The author of the issue is encouraged to go seek support with greenplum https://greenplum.org

**Comment by sydt2014** [comment]
thanks your advise very much!
