### ISSUE TITLE
Sudden unexplained bug

### ISSUE THREAD

**Issue by bitBiaoBiao** [RoaringBitmap/RoaringBitmap#324]
Dear contributors, hi
         I am very proud to use RoaringBitmap. But I have some doubts here. When I employ 0.7.0 version, I put some negative integers into the RoaringBitmap, and the result is messy, like -516762017 -------> 32259, actually, it should be -516762017 -------> 3778205279. It happened more than once but all of a sudden, so that made me confused. I really hope it's my fault made this problem.

**Comment by lemire** [comment]
@bitBiaoBiao Can you give us a code sample to illustrate the bug you are reporting?

Please realize that, as stated, it is impossible for us to work on your problem. You are not providing nearly enough details.

**Comment by bitBiaoBiao** [comment]
@lemire First, thank you to my reply. It's all my mistakes, when I'm running my simple test code on a server environment, it was fixed and also good to run on my partner's compiled environment. It may be my compiler's problem, I will try my best to find the reason. By the way, RoaringBItmap is really great, I apologize for this intrusion.......T.T

**Comment by lemire** [comment]
Closing.
