### ISSUE TITLE
We cannot release due to JDK-8212233 

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#340]
https://bugs.openjdk.java.net/browse/JDK-8212233 is blocking us.

With OpenJDK 11.0.3 and Oracle JDK 12.0.1, we get

> [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project shims: MavenReportException: Error while generating Javadoc:
[INFO] [ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[INFO] [ERROR]
[INFO] [ERROR] Command line was: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javadoc @options @packages
[INFO] [ERROR]
[INFO] [ERROR] Refer to the generated Javadoc files in '/Users/lemire/CVS/github/RoaringBitmap/target/checkout/shims/target/apidocs' dir.

We apparently cannot issue releases with javadoc disabled and we cannot build javadoc.

Note that RoaringBitmap cannot be built with Java 8 anymore.

**Comment by richardstartin** [comment]
Is it worth rolling back? We would lose the vectorised equals but that's about it, and the build would be simpler.

**Comment by shipilev** [comment]
I don't quite understand, do you mean JDK-8212233 *regressed* the builds for you? It might be just that the failure message is similar to what JDK-8212233 is fixing. Anyhow, if you read the description there, you would see: "UPDATE: For the projects that use source/target 8, adding <source>8</source> in javadoc configuration makes the project buildable on jdk {11, 12, 13}..."

So, I checked out RoaringBitmap repo, picked up 11.0.3, fired "mvn javadoc:jar", and it failed. Then I added the suggested block like this:

```
diff --git a/pom.xml b/pom.xml
index f513766b..03fe9f35 100644
--- a/pom.xml
+++ b/pom.xml
@@ -297,14 +297,17 @@
                                <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-javadoc-plugin</artifactId>
                                        <version>3.0.1</version><!-- release fails with 3.1.0 with "Plugin 
           org.apache.maven.plugins:maven-javadoc-plugin:3.1.0 or one of its dependencies could not be resolved"
           https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/
         -->
+                                        <configuration>
+                                           <source>8</source>
+                                        </configuration>
                                </plugin>
                        </plugins>
                </pluginManagement>
     </build>
 
     <dependencyManagement>
         <dependencies>

```

...and the javadoc generation passed.

**Comment by shipilev** [comment]
...plus, I made that suggestion the first paragraph in JDK-8212233 description and made the first sentence in all caps -- hopefully it would be more distinct for the casual readers.

**Comment by richardstartin** [comment]
Is it worth retrying #311?

**Comment by shipilev** [comment]
@lemire: It seems your attempt borked the POM: duplicate </plugin>
@richardstartin: Passing source=8 when project source/target=8 (as RoaringBitmap pom.xml does) is a known configuration tweak for new Javadoc (whether we like it or not...). It seems to resolve compilation issues for me. Note #311 does it only for "release" profile, it is better to be in "<pluginManagement>" to be captured for every javadoc goal, as in my fix above.

**Comment by lemire** [comment]
@shipilev Your fix works!!!

Recopied from Twitter:

> Thanks. The proposed fix resolved the issue. Great! But, surely, JDK’s javadoc is still throwing this error, the error was not removed, right? Yet the error is clearly wrong. So as far as I can tell, the bug is still there, unresolved.

I mean... what is the point of this error in the first place?

**Comment by lemire** [comment]
Closing thanks to @shipilev

**Comment by lemire** [comment]
clap! clap! clap!
