### ISSUE TITLE
Dropping support for Maven Central and bintray

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#345]
Up until now, we have been posting our release on maven central. However, it is not clear that this is a well-maintained, serious platform at this point in time. Uploads fail constantly for seemingly random reasons. I am asking for advice regarding the possibility of dropping the maven central as an output point.

https://github.com/RoaringBitmap/RoaringBitmap/pull/343

What would be a good alternative?

**Comment by lemire** [comment]
cc @richardstartin

**Comment by brharrington** [comment]
Skimming #343, is the proposal that it would only be published to jcenter? Or that it would not be available via a public maven repo?

Only publishing to jcenter would be fine for my use-cases. Though I'll note it also has problems on occasion (e.g. https://github.com/akka/akka-http/issues/1972) so I wouldn't argue it is rock solid either. That said, jcenter is often not configured by default in build tools so it might make it a little harder to consume for some users since they'll need to add a repository to the build config.

Not publishing to any public maven repo would make it a real pain to consume.

**Comment by lemire** [comment]
>  it would only be published to jcenter?

That's a possibility, yes.

> Though I'll note it also has problems on occasion (e.g. akka/akka-http#1972) 

I am sure that's true but Maven Central is a bit of a joke right now, as far as publishing artefacts goes. It looks very much like an unmaintained system. It is almost surely the case that jcenter will be better.

> Not publishing to any public maven repo would make it a real pain to consume.

That's not in the cards. We definitively do not want folks to have to build their own jars or to download jar files manually.

Let us not go back to 1990.

The plan would be to offer something that is convenient to the users.

**Comment by richardstartin** [comment]
I'm not thrilled by the prospect of dropping maven central, to be honest. It may be "a joke" but it's also widely trusted and accessible behind corporate firewalls. On the other hand, by all reports maven central is painful for @lemire so I understand the incentive to shop around.

**Comment by lemire** [comment]
@richardstartin  Well, if someone is willing to help us with the pain I am quite willing to keep supporting Maven Central... but... we'll need help. Here is the last message I got trying to upload our jar there...

```
Last Sync Errors: Could not sync artifact RoaringBitmap-0.8.9.pom. Server response: <html> <head> <title>400 - Bad Request</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png"> <!--[if IE]> <link rel="SHORTCUT ICON" href="https://oss.sonatype.org/favicon.ico"/> <![endif]--> <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.14.13-01" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>400 - Bad Request</h1> <p>Repository with ID='orgroaringbitmap-1161' is Read Only, but action was 'create'!</p> </body> </html>
```

Do you know what this means? I sure don't. The previous error was something about missing source jar files in shims. And before that we had missing MD5 files... I can keep going all day... maybe it will go through at some point... 

So we are not in the state where the shims package has been uploaded...

https://repo1.maven.org/maven2/org/roaringbitmap/shims/0.8.9/

But we cannot upload the rest of our code... so release 0.8.9 is broken, and it is only one of several such broken releases... they add up. If you picked a release at random, you have a pretty good chance of having something that is just missing or broken... and it is not clear how we fix these things.

They only way to get a release correctly posted is to try and try and try and try endlessly.

The hours I spend on releases are hours that are not spend actually providing values to the users. In fact, it discourages me from improving the code because I know it will later have to translate into a release, and issuing a release is a major pain. It frequently takes a full afternoon to get a release out.


This is flatly unacceptable in my opinion.

Now, I understand that corporations have release engineeers that do only releases. But we don't have that. If someone wants the job... I sure don't.

**Comment by richardstartin** [comment]
@lemire that was more or less my point. I certainly wouldn't want to take on the responsibilty of releasing, because it's time consuming and error prone, but as a user, maven central is the golden source, so my position is quite selfish and I understand if you prioritise your time and sanity...

**Comment by lemire** [comment]
Incredible. I kept trying and it eventually went through... release 0.8.9 is now on maven central.

No clue why the previous attempts failed.

**Comment by marshallpierce** [comment]
I didn't change anything... that's, uh, confidence inspiring? :(

**Comment by lemire** [comment]
@marshallpierce Right?

You can think that I am doing stupid things and being a moron... but this is literally just button pressing and anyone can verify that we did nothing but keep on pressing on the button.

There is obviously bad code in the infrastructure. Or else, the systems are just overloaded...

**Comment by blacelle** [comment]
I am definitely in favor of keeping m2-central in the loop.

@lemire Could you remind here your Maven release process/commands ?

**Comment by lemire** [comment]
@blacelle 

It used to be...

```
mvn release:clean release:prepare release:perform
```

This would fail about half the time in various ways. That's why if you go through our release numbers on maven, you'll see us jumping from one version to another.

We have since moved to gradle (just now) because it is about 10x faster and easier than maven (which is about as speedy as a garbage truck). Currently, we upload to bintray... that's fast and painless. Then we have to push to maven central. That involves trying again and again and again until it succeeds.

That's litterally how it goes...

1. Try to upload to maven central.
2. Get random error message.
3. Try to upload to maven central.
4. Get random error message.
5. Try to upload to maven central.
6. Get random error message.
7. Try to upload to maven central.
8. Get random error message.
9. Try to upload to maven central.
10. Get random error message.
11. Try to upload to maven central.
12. Get random error message.

This is not how serious software is deployed.

If you create an account on bintray and ping me, I can give you privileged access to the repository there so you can see how much fun it is...

https://bintray.com

**Comment by lemire** [comment]
@blacelle I submit to you that a random error when issuing a release is simply unacceptable. Two random errors in sequence is tragic. Several and you should not be taken seriously ever again.

**Comment by lemire** [comment]
It looks like bintray is closing now.

**Comment by JanecekPetr** [comment]
Is https://jitpack.io/ an option?

**Comment by lemire** [comment]
@JanecekPetr It is a good proposal, at least for the time being.

If someone wants to work on producing other releases, the issue is open...

GitHub actions look like they can do it...

https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven

**Comment by lemire** [comment]
I am going to close this for now since we are tracking this issue elsewhere.
