### ISSUE TITLE
Higher performance requirement about the codes based on RoaringBitmap

### ISSUE THREAD

**Issue by brucenan** [RoaringBitmap/RoaringBitmap#350]
I've designed a Bit-Sliced Index based on RoaringBitmap, which use 32 RoaringBitmap objects to store many 32bit Integers. Now I want to get all distinct integers from these bitmaps and store them to s1. Below is the code:
```
MutableRoaringBitmap[]  mrbs;
RoaringBitmap s1;
...
for(int i = start;i<end;i++) {
  int s = 0;
  for (int j = 0,len = mrbs.length; j < len; j++) {
  if (mrbs[j].contains(i))
     s = s | (1 << j);
  }
  s1.add(s);
}
```
Outer loop is from left to right to locate each columns, and inner loop to get the stored integer value, then set it to s1 (The same values are stored in same position in order to implement distinct results).

How from start to end, there are about 10,000,000, which is outer loop times. And 32 times in Inner loop, the total spend time is about 7486 ms. The most of time spent on RoaringBitmap's **Contains** function. This time for me is too long to get some calculations. I've tried to divide the loop into small ones, but only reduce half of time, to about 2964ms.

Is there any better solutions to improve the performance about this code? The lower , the better. 

Thanks.

**Comment by ppiotrow** [comment]
Seems you're just iterating over values in the `mrbs` bitmap limited from `start` to `end`. I'd rather try iterator methods like `getIntIterator()`. Also no idea what is `s1`: if it's RoaringBitmap then you can even more effective just by copying.

**Comment by brucenan** [comment]
> Seems you're just iterating over values in the `mrbs` bitmap limited from `start` to `end`. I'd rather try iterator methods like `getIntIterator()` or `forEach`. Also no idea what is `s1`: if it's RoaringBitmap then you can even more effective just by copying.

mrbs includes 32 roaringbitmap objects, forEach or Iterator only get one object's iterator. Here is should fix the position for these 32 objects, one bit by one bit. Both 0 or 1 in each position impacts the stored value.

**Comment by richardstartin** [comment]
If you are implementing a BSI can you reduce the slices to an intermediate bitmap before iteration over that intermediate bitmap? Are you trying to save memory?

**Comment by richardstartin** [comment]
If you reduce your problem to one where you can iterate, try batch iterators. Druid is [experimenting](https://github.com/apache/incubator-druid/pull/6794) with using them and got [good performance gains](https://static.imply.io/gianm/vb.html) from the vectorised approach in general.

**Comment by lemire** [comment]
> Both 0 or 1 in each position impacts the stored value.

Is that true? You do a check for "contains" and then do something if true, but you do nothing if false.

**Comment by brucenan** [comment]
> > Both 0 or 1 in each position impacts the stored value.
> 
> Is that true? You do a check for "contains" and then do something if true, but you do nothing if false.

Below code is to get one stored value.  
```
if (mrbs[j].contains(i))
     s = s | (1 << j);
}
```
For example, an Integer 8 with binary format 1000.   The code get 1 at 3rd roaringbitmap, set right shift operation to 1<<3 = 8, for left 3 binary position, the value is zero. The code can skip them at all.

**Comment by lemire** [comment]
@brucenan So I am going to close this. I think you should try to use iterators, possibly batch iterators, and then report back if you still have problems.

Note that converting from a bit sliced index back to the original data is never going to be cheap. A bit sliced is useful to do number crunching quickly... but if you need to convert back, it is always going to be slow... so you should avoid that operation as much as possible.
