### ISSUE TITLE
Define serialisation format for 64 bit bitmaps

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#351]
I notice a disclaimer [here](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java#L911) that the serialisation format of `Roaring64NavigableMap` is undefined and subject to change. I would like to be able to serialise a 64 bit bitmap, and trust that I will always be able to deserialise it. One challenge is not to leak implementation details in the format such that other structures could not be deserialised, given that a sorted map of 32 bit bitmaps is not the only way one might arrange a 64 bit bitmap. A structure neutral serialisation format might align with the goal of #108.

**Comment by lemire** [comment]
Indeed. I think that defining a good 64-bit format would be important work.

**Comment by blacelle** [comment]
Can this be closed given https://github.com/RoaringBitmap/RoaringFormatSpec#extention-for-64-bit-implementations ?

**Comment by lemire** [comment]
Closing.
