### ISSUE TITLE
Efficient RoaringBitmap.orNot operation

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#352]
A method `orNot` which takes two parameters, another bitmap and an exclusive maximum element would result in the current bitmap containing any bit currently set in the bitmap, or any bit less than the limit not set in the parameter bitmap, modifying the bitmap in place. 

A static method would take two bitmaps and an exclusive maximum element as input, and create a new bitmap containing any bit less than the limit in the first bitmap but not in the second bitmap.

**Comment by lemire** [comment]
+1

**Comment by mdouaihy** [comment]
@richardstartin, would it be ok if it's implemented as an or(not()) in each container?

**Comment by richardstartin** [comment]
You would also need to put in full containers anywhere neither input bitmap has a container too. I think it should be possible to do it without unnecessary materialisation, but using existing or and not might have advantages over the best option a user has at present.

**Comment by mdouaihy** [comment]
https://github.com/RoaringBitmap/RoaringBitmap/pull/355 pushed for that purpose.

**Comment by lemire** [comment]
Closing as per https://github.com/RoaringBitmap/RoaringBitmap/pull/355
