### ISSUE TITLE
JDK1.8 Support

### ISSUE THREAD

**Issue by subprotocol** [RoaringBitmap/RoaringBitmap#353]
The 0.8.9 build in maven central does not work with my project which has a dependency on roaring. 

I found this because 0.8.9 appears to have been compiled with jdk > 1.8 (which my project uses).  In 1.9 they changed Buffer slightly. for more details: https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime

I see this error at runtime:

```
java.lang.NoSuchMethodError: java.nio.ShortBuffer.rewind()Ljava/nio/ShortBuffer;
  at org.roaringbitmap.buffer.MappeableArrayContainer.increaseCapacity(MappeableArrayContainer.java:714)
  at org.roaringbitmap.buffer.MappeableArrayContainer.increaseCapacity(MappeableArrayContainer.java:694)
  at org.roaringbitmap.buffer.MappeableArrayContainer.add(MappeableArrayContainer.java:171)
  at org.roaringbitmap.buffer.MutableRoaringBitmap.add(MutableRoaringBitmap.java:774)
  ```

Scanning open/closed issues I see why it was recently changed.

So options as I see it:

1) Perhaps this could be fixed by compiling roaring on newer JDKs, but targeting 1.8 bytecode?
2) Declare roaring JDK1.9+. If so we should update the prerequisites in README.md with JDK1.9 starting with 0.8.9 (or cut over to 0.9?)
3) cross-build or maintain separate 0.8 and 0.9 branches/releases.  Probably not worth the effort (not to mention amplifying maven central issues)

**Comment by lemire** [comment]
Thanks for reporting this issue. I definitively consider this as a bug.

> Perhaps this could be fixed by compiling roaring on newer JDKs, but targeting 1.8 bytecode?

Why do you expect that this is a bytecode issue? It looks to me more like an issue with the standard library.

Regarding bytecode, our gradle build is configured in this manner...

```
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
```

**Comment by subprotocol** [comment]
Ahh I see, you are correct. As a sanity check I confirmed that the 0.8.9 artifact in maven was indeed targeted to 1.8.
```
javap -v ./org/roaringbitmap/buffer/BitmapBatchIterator.class | grep "version:"
  minor version: 0
  major version: 52
```

I agree this is an issue with the standard library.


Doing some digging this is the path that I see-
1. Cast to Buffer in all appropriate places
2. It looks like they added --release for this very issue. http://openjdk.java.net/jeps/247   so `--release 8` would need to be specified in addition to sourceCompatibility and targetCompatibility in gradle.  This will cause a compiler error for all places where the cast is needed (making it detectable at compile time instead of at runtime)

I would be happy to look into this further and submit a PR if you think this is the correct path to go down.

**Comment by lemire** [comment]
@subprotocol 

Please do.

**Comment by lemire** [comment]
I have marked this as a bug. It is bad.

This should never happen in the future.

**Comment by richardstartin** [comment]
This was previously addressed in the maven build in #288.

**Comment by lemire** [comment]
@richardstartin You are correct Richard... which is why I am surprised it is an issue... I thought we solved this...

**Comment by subprotocol** [comment]
Looking at #288, the pom.xml does specify `<javac.release>8</javac.release>`, so this makes sense that it works there and not here.

It appears the only challenge then is to find a way to get gradle to accept a --release argument.  I am finding this exceedingly difficult to do!

https://github.com/gradle/gradle/issues/2510

Specifying it on the compilerArgs is easy, but I then run into the same issue linked above:
```> error: option -source cannot be used together with --release```

It is mentioned that source and target compatibility need to be set to null for this to work.  However, I've been unable to find a way to do this as source/target compatibility are JavaVersion enums.

**Comment by lemire** [comment]
@subprotocol 

> Looking at #288, the pom.xml does specify <javac.release>8</javac.release>, so this makes sense that it works there and not here.

It makes sense that we lose the checks, but it does not follow that we would lose backward compatibility. There has been few changes since we moved to gradle.

**Comment by lemire** [comment]
Adding the release flag is easy...

https://github.com/RoaringBitmap/RoaringBitmap/pull/354

Why won't it pick up any issue?

@subprotocol  Can you explain *why* our code is not valid Java 8? I wrote this code... It is many years old... written back in Java 8 time...

**Comment by subprotocol** [comment]
I can confirm your change in #354 resolves my build issue in my 1.8 project (yay!)


> Can you explain _why_ our code is not valid Java 8? I wrote this code... It is many years old... written back in Java 8 time...

The code is valid.  The issue is only with the bytecode.  For example, this changed between JDKs-

JDK1.8-
`Buffer position(int)`

After JDK1.8 the sub-classes of Buffer now have methods overriden with different return types. so now ShortBuffer has this on it-
`ShortBuffer position(int)`


The bytecode from a newer JDK (even with source=8 and target=8, but not release=8) will generate 1.8 byecode that reference the newer method signature that does not exist in 1.8.


So a 1.8JVM will see `ShortBuffer position(int)` and not know what that is.


Here is a diff showing this using the old build, and #354:

![image](https://user-images.githubusercontent.com/3710126/62257547-29099800-b3c3-11e9-82e7-69b8ca887ddd.png)

**Comment by lemire** [comment]
Ok. Issuing a release. Thanks for reporting the issue.

Meanwhile, I found out that we can build our project with Java 8! (This hasn't been possible in quite some time.)

**Comment by subprotocol** [comment]
Thank you!
