### ISSUE TITLE
Remove gradle jmh plugin

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#356]
I just wrote a quick benchmark for #355 and noticed how complicated it is now to activate JMH profilers and it's impossible to select a benchmark from the command line now. In my opinion this is a big step backwards.

**Comment by richardstartin** [comment]
Just build it as a regular module, then we get a jar. I think having a JMH plugin for the build is a nice idea, but in reality, these benchmarks are impractical to run in their entirety or on an repeated basis, and the appropriate parameters vary depending on what the person running the benchmarks wants to find out from the run, which varies from run to run. Is this an eccentric opinion?

**Comment by richardstartin** [comment]
Actually, having dug a bit deeper, I think it's OK to keep this in place, I just don't see any use for it. I will submit a PR to ensure the shaded benchmarks jar is Multi-Release though.

**Comment by marshallpierce** [comment]
I don't have any use for it as part of the gradle build in my own projects; I just build the jmh jar and go from there...

**Comment by richardstartin** [comment]
Indeed. This is probably the simplest way to build the benchmarks jar, `jmh` is just not a very useful gradle task.

**Comment by lemire** [comment]
Can we improve the documentation regarding JMH?

**Comment by marshallpierce** [comment]
I think "run `./gradlew jmhJar` and then run the jar as per JMH's docs" is a pretty reasonable suggestion. :man_shrugging:

**Comment by lemire** [comment]
Thanks. I updated our documentation to match...

https://github.com/RoaringBitmap/RoaringBitmap#benchmark
