### ISSUE TITLE
Releases not making it to maven central

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#360]
0.8.10 and 0.8.11 are not at [maven central](https://search.maven.org/search?q=g:org.roaringbitmap%20AND%20a:RoaringBitmap&core=gav). What is the sync time from bintray?

**Comment by lemire** [comment]
I can make you an admin in the RoaringBitmap org. on bintray.

Meanwhile... here is the answer back from maven central (the number, here 1166, increments by one with each attempt):

```
Server response: <nexus-error> <errors> <error> <id>*</id> <msg>Unhandled: Staging repository is already transitioning: orgroaringbitmap-1166</msg> </error> </errors> </nexus-error> Dropping existing partial staging repository.
```

I don't know what it means.

**Comment by lemire** [comment]
Just give me your user name on bintray.

**Comment by richardstartin** [comment]
Usename = richardstartin

**Comment by lemire** [comment]
@richardstartin You have been invited.

**Comment by lemire** [comment]
Note: at this time, it is still not synced. It is unclear how this is all supposed to work. I am not sure that the maven repo. is maintained by anyone at this time.

**Comment by richardstartin** [comment]
I’m not convinced of the merits of publishing to jcenter. As far as most projects and enterprises are concerned, a Java library doesn’t exist unless it is in Maven Central. Does the release take the right approach?

**Comment by richardstartin** [comment]
Somehow [shims](https://search.maven.org/artifact/org.roaringbitmap/shims/0.8.11/jar) made it, but not RoaringBitmap.

**Comment by richardstartin** [comment]
It's there now: https://search.maven.org/artifact/org.roaringbitmap/RoaringBitmap/0.8.11/jar

Did you do something or do we need to be aware that the sync takes days?

**Comment by lemire** [comment]
@richardstartin 

> Did you do something or do we need to be aware that the sync takes days?

I did not do anything in last 20 hours or so.

**Comment by lemire** [comment]
> As far as most projects and enterprises are concerned, a Java library doesn’t exist unless it is in Maven Central. 

I can see the logic of that as far as users of Maven Central go. For people actually pushing bits to Maven Central, the experience is subpar engineering. Random failures. No visible logging... so you can't track release, see how long they take and so forth.

This has nothing to do with JCenter. We had exactly the same problem prior to using JCenter... failed or delayed releases...

**Comment by richardstartin** [comment]
Fair enough. It shouldn’t take days, and 0.8.10 still hasn’t arrived (not that it particularly matters now), but ease of use should trump latency concerns.

**Comment by lemire** [comment]
@richardstartin I don't think we disagree.

I seek solutions...

**Comment by lemire** [comment]
I am going to close this since we have another issue and even a PR draft.
