### ISSUE TITLE
What does contains(long minimum, long supremum) mean?

### ISSUE THREAD

**Issue by qblyy** [RoaringBitmap/RoaringBitmap#361]
import org.junit.Assert;
import org.junit.Test;
import org.roaringbitmap.RoaringBitmap;

public final class Test1a {
	@Test
	public void testContains() {
		final RoaringBitmap bs = new RoaringBitmap();
		bs.add(1);

		Assert.assertFalse(bs.contains(0, 1));
		Assert.assertTrue(bs.contains(1, 2));
		Assert.assertTrue(bs.contains(1, 100));//Fail
	}
}

I think bs should  intersects with [1, 100), am I right? Thanks. 

boolean org.roaringbitmap.RoaringBitmap.contains(long minimum, long supremum)

Checks if the bitmap contains the range.

Parameters:
minimum the inclusive lower bound of the range
supremum the exclusive upper bound of the range
Returns:
whether the bitmap intersects with the range

**Comment by lemire** [comment]
>What does contains(long minimum, long supremum) mean?

It checks if the bitmap contains the range. In your case, it checks whether the bitmap contains [0,100). The bitmap containing the sole value 1 does not contain the range [0,100).

> I think bs should intersects with [1, 100), am I right? Thanks.

Yes. So you should get that `bs.intersects(1,100)` is true.

Please open an issue if this is not the case.

I am going to close this issue, reopen if I did not answer your question.

**Comment by qblyy** [comment]
Thank you. I think the boolean org.roaringbitmap.RoaringBitmap.contains(long minimum, long supremum) JavaDoc is wrong.

It should be:
@return whether the bitmap contains the range

**Comment by lemire** [comment]
You are correct. I just committed a fix.
