### ISSUE TITLE
Roaring64NavigableMap serialized binary format is not compatible with CRoaring's 64bit version

### ISSUE THREAD

**Issue by weijietong** [RoaringBitmap/RoaringBitmap#366]
As described by the tile, the serialized 64bit bitmap binary format  is not compatible between java and c++.
The java version's serialization does not solve the bit order of java's int, also has boolean wrote which does not appeared at the c++ version.

**Comment by lemire** [comment]
That’s to be expected since the interoperability guarantee only applies to the Roaring format which is 32-bit.

Contributions are invited.

**Comment by weijietong** [comment]
would be glad to do that. But the 64 bit version seems still have evolution space . just hold on this.

**Comment by finchen-tencent** [comment]
@weijietong @lemire hi， how to solve Roaring64NavigableMap  serialized  binary format is not compatible with CRoaring

**Comment by blacelle** [comment]
There is a contribution in https://github.com/RoaringBitmap/RoaringBitmap/pull/572/files in this perspective. However, it does not remove https://github.com/RoaringBitmap/RoaringBitmap/pull/572/files#diff-5bb999cb0772cc6137e43d9fcd3218478da513af25783a038bd268950f0dea29R1178 which supposedly is not written by CRoaring.

We may depend on a (static ? environment_variable) flag to switch to a different layout. What would be acceptable to do such a change without waiting for a breaking release?

Could one provide some example CRoaring 64-bits binaries, to be used in unit-tests?

**Comment by lemire** [comment]
> Could one provide some example CRoaring 64-bits binaries, to be used in unit-tests?

We definitively need that or the equivalent.

**Comment by blacelle** [comment]
This is done with https://github.com/RoaringBitmap/RoaringBitmap/pull/598

**Comment by larsk-db** [comment]
Should close it then, I guess.
