### ISSUE TITLE
RoaringBitmap is serialized to different string using node and java

### ISSUE THREAD

**Issue by rajcspsg** [RoaringBitmap/RoaringBitmap#367]
I'm using roaring bitmaps to store arrays of values.

When are using nodejs application to create and serialize the bitmap. And java application fetches the serialized string and recreates the bitmap.

Below is the node js code -

```
const RoaringBitmap32 = require('roaring/RoaringBitmap32');
const bitmap2 = new RoaringBitmap32([3, 4, 100]);
console.log('bitmap2.toArray():', bitmap2.toArray());
console.log('contentToString:', bitmap2.contentToString());
const serialized = bitmap2.serialize()
console.log("serialized " + serialized)
console.log('base 64 serialized:', serialized.toString('base64'))
console.log('deserialized:', RoaringBitmap32.deserialize(serialized).toArray())
```

Below is the output -

```
bitmap2.toArray(): [ 3, 4, 100 ]
contentToString: [3,4,100]
serialized d
base 64 serialized: AQMAAAADAAAABAAAAGQAAAA=
deserialized: [ 3, 4, 100 ]
```

Below is the java code -

```
public static void main(String[] args) {
    MutableRoaringBitmap mrb = MutableRoaringBitmap.bitmapOf(3, 4, 100);
    System.out.println("starting with  bitmap "+ mrb);
    ByteBuffer outbb = ByteBuffer.allocate(mrb.serializedSizeInBytes());
    mrb.serialize(outbb);
    outbb.flip();
    String serializedstring = Base64.getEncoder().encodeToString(outbb.array());
    System.out.println("serializedstring :\n" + serializedstring);
}
```

The output of the java code is -

```
starting with  bitmap {3,4,100}
serializedstring :
OjAAAAEAAAAAAAIAEAAAAAMABABkAA==
```

My question is why the bitmap with same contents produces different serialized string?

How can I make serialization and deserialization of roaring bitmap interoperable between java and node.js?

**Comment by lemire** [comment]
I think that the documentation of the Node wrapper explains it... Please see file roaring-node/index.d.ts, the method serialize takes a flag (portable) which defaults to false. So you want to call bitmap2.serialize(true).

Reopen if this does not solve your issue.

**Comment by rajcspsg** [comment]
@lemire Thanks that solved my issue.

**Comment by lemire** [comment]
@rajcspsg  Consider commenting at https://github.com/SalvatorePreviti/roaring-node/issues/23

**Comment by rajcspsg** [comment]
sure @lemire
