### ISSUE TITLE
RoaringBitmap of small universe vs. BitSet

### ISSUE THREAD

**Issue by JohannesLichtenberger** [RoaringBitmap/RoaringBitmap#372]
Hi,

I guess it makes little sense to use RoaringBitmap for a small universe, for instance 512 or 1024 at most (size of entries in a trie-structure of a temporal data store, for child-pointers).

Kind regards
Johannes

**Comment by JohannesLichtenberger** [comment]
And also for storing, which records out of the 512 or 1024 are present in a data page fragment (variable sized).

**Comment by JohannesLichtenberger** [comment]
Okay, just from running my unit (or more or less most of them are actually rather integration tests) I got the impression, that it's indeed way slower using RoaringBitmap (but didn't make any Benchmarks).

**Comment by lemire** [comment]
I think that this is addressed in the README:

```
This being said, there are definitively cases where attempting to use compressed bitmaps is wasteful. For example, if you have a small universe size. E.g., your bitmaps represent sets of integers from [0,n) where n is small (e.g., n=64 or n=128). If you are able to uncompressed BitSet and it does not blow up your memory usage, then compressed bitmaps are probably not useful to you. In fact, if you do not need compression, then a BitSet offers remarkable speed.
```

I am going to close this issue since I feel it is already addressed.
