### ISSUE TITLE
Corner cases in orNot

### ISSUE THREAD

**Issue by incaseoftrouble** [RoaringBitmap/RoaringBitmap#376]
Found a quite straightforward bug:

```java
long len = 3L;
long orLen = 3L;

RoaringBitmap one = new RoaringBitmap();
RoaringBitmap other = new RoaringBitmap();
other.add(0L, len);

one.orNot(other, orLen);
```

This throws an `ArrayIndexOutOfBoundsException` for all `len >= 3` and `orLen == len` (funnily enough, the error does not occur if `orLen != len`).

Trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.roaringbitmap.RunContainer.getValue(RunContainer.java:1066)
	at org.roaringbitmap.RunContainer.and(RunContainer.java:387)
	at org.roaringbitmap.Container.and(Container.java:87)
	at org.roaringbitmap.Container.iorNot(Container.java:542)
	at org.roaringbitmap.Container.iorNot(Container.java:560)
	at org.roaringbitmap.RoaringBitmap.orNotHandleRemainingOtherContainers(RoaringBitmap.java:1373)
	at org.roaringbitmap.RoaringBitmap.orNot(RoaringBitmap.java:1468)
```
Tested with 0.8.14

**Comment by incaseoftrouble** [comment]
Another, probably related bug:

```
RoaringBitmap one = new RoaringBitmap();
test.add(i);

RoaringBitmap other = new RoaringBitmap();
other.add(0L, i);

test.orNot(other, i);
```
With `i > 0`, `test.toString()` yields `{0}`, expected `{i}` (`0` should definitely not be in there)

Also `test.last()` throws a `NoSuchElementException` despite `test.isEmpty() == false`.

**Comment by incaseoftrouble** [comment]
Confirming one more point
```java
RoaringBitmap test = new RoaringBitmap();
test.add(20L, 30L);

RoaringBitmap other = new RoaringBitmap();
other.add(0L, 5L);

test.orNot(other, 10);
System.out.println(test);
```
I would expect this to print `{5,6,7,8,9,20,..,30}`, however it prints `{5,6,7,8,9}`. If this is intended this should be documented, all other range-based operations do not modify the set outside of the given range.

**Comment by lemire** [comment]
> I would expect this to print {5,6,7,8,9,20,..,29}, however it prints {5,6,7,8,9}. If this is intended this should be documented, all other range-based operations do not modify the set outside of the given range.

Can you elaborate? This does not sound wrong to me. You are specifying that your universe is [0,10).

**Comment by lemire** [comment]
OrNot is a recent addition by   @mdouaihy reviewed by @richardstartin... can you guys have a look at this issue?

**Comment by richardstartin** [comment]
I will look at it tomorrow.

**Comment by incaseoftrouble** [comment]
> Can you elaborate? This does not sound wrong to me. You are specifying that your universe is [0,10).

Aha! We are interpreting this differently, interesting. Lets say the call is `one.orNot(other, len)`. In my opinion, `len` specifies the length of the universe of `other`, not of `one` (its giving the universe of the `not` part, i.e. the domain relative to which `other` is "complemented"). The current behaviour feels like two operations thrown into one (truncate `one` to len + bitwise orNot).

I don't think its sensible that an "or-operation" may actually remove something from the set. In particular, `one.orNot(other, 0)` clears the set (well, right now it actually fills the set, but thats a bug in any case). From a practical point of view, if `orNot` simply leaves `one` untouched beyond `len`, you could simply add `remove(len, Interger.MAX_VALUE + 1L)` after that call to get the current behaviour without additional cost / needing to copy anything.

In any case, I guess this shows that this should be clarified in the doc, maybe with a small example (I can write that). I have no strong opionion on changing the current behaviour, I was just puzzled that it didn't behave as I thought it should.

As a related follow up, I guess it could be useful to have a `rangeCopy(long from, long to)` method.

**Comment by richardstartin** [comment]
I have made a PR fixing these bugs, keeping and clarifying the current interpretation of `rangeEnd` as a universe size, and fixing the other bugs. I influenced this choice because it suited the use case I had in mind, but I never ended up using this method. So I imagine it could be changed not to truncate when `rangeEnd < this.last()` without disrupting anybody.

**Comment by lemire** [comment]
I expect that there are few users, especially of the corner cases we are discussing, so breaking the behaviour, in this particular case, is acceptable, especially if it is documented.

**Comment by richardstartin** [comment]
But should we? The point of the `rangeEnd` parameter is to represent a universe size. Would calling it `universeSize` improve things?

**Comment by incaseoftrouble** [comment]
My opinion: Its a universe size in either cases, it only depends on which set this universe belongs to. From a practical point of view, I feel that truncating is a separate operation and thus should be separate.

In my use case, I'd actually need both variants but the truncation is easier to simulate with the given API. As mentioned above, having a `rangeCopy` or similar would be helpful.

**Comment by richardstartin** [comment]
Regarding the current semantics, and what "universe size" means, I think it covers the way most people would want to use it, within a bitmap index: you have an array with N records in it, indexed by some bitmaps, you call `orNot` with `rangeEnd=N`, rather than have the library assume N=2^32 (using lots of memory). That is, `universeSize` is a property of the _output_ rather than the inputs.

I think the problem is really that the parameter is called `rangeEnd`, rather than `universeSize` accompanied with an explanation of what a "universe size" is. 

Regarding changing what the method does, the question to answer is why anybody would want a method with performs `orNot` with a range of an input bitmap. Is there an actual use case for it?

**Comment by incaseoftrouble** [comment]
Sorry I don't get the first point. Why wouldn't I want the universe size on every other operation aswell then? In my understanding, the universe size is only there to make the complement sensible, otherwise you would union with a (theoretically) infinite set. For me, `A.orNot(B, n)` means `A \union ({0, ..., n-1} \setminus B)`. But I don't have a strong opinion as long as it is documented, so its up to you.

My use case: I add an abstraction layer on top of bitmaps which allows (among other things) constant time complementation. Basically, the abstraction layer knows a fixed universe size a-priori and to complement I simply flip a flag. Now, I still want to perform the classical bitwise operations with a single pass. There, sometimes the need arises for the non-truncating `orNot`. Natural example: `set.or(other)´ where `other` is "complemented". Then I'd like to call `set.map.orNot(other.map, other.domain)`. But this is rather specific, so if there is a canonical use case where the truncation is natural I don't mind. However I can't really imagine that someone would want a "truncate from 0" built in there. There is `remove(..)` after all.

**Comment by richardstartin** [comment]
If you have a set of bitmaps all with a max element below N, you can never create a bitmap with an element above N with any other operation. You can do that two ways: define a range to complement the second bitmap within, or truncate the output. I would argue that truncating the output (existing semantics) is more consistent with other operations.

**Comment by incaseoftrouble** [comment]
I'm not sure about consistent. `flip`, for example, also is a bitwise operation which has a range and does not truncate the output (arguably its a unary operation). I guess both choices are fine since orNot simply is such a "special" operation in the sense that `0 ORNOT 0 = 1` and there currently is no other such operation, so there probably is not much to compare to in terms of consistency.

**Comment by richardstartin** [comment]
No I'm convinced now, it's more general not to truncate; we can have both. We can probably simplify the code a lot too, I'll try to do it later today unless @lemire objects.

**Comment by lemire** [comment]
I do not object.
