### ISSUE TITLE
Error in remove(from, to) for run encodings (?)

### ISSUE THREAD

**Issue by incaseoftrouble** [RoaringBitmap/RoaringBitmap#377]
I seem to find a lot of things today :D

First, the bug:

```java
RoaringBitmap test = new RoaringBitmap();
test.add(0L, 64L);
for (int i = 0; i < 64; i++) {
  if (i != 30 && i != 32) {
    test.remove(i);
  }
}
test.remove(0L, 31L);
assert !test.contains(30);
assert test.contains(32);
```

Both asserts fail (actually `test = {30}`).

I suspect this is due to an offset error. The test succeeds if:
 * instead of `test.add(0L, 64L)` the indices are added one-by-one (then array representation instead of run compression is used I guess?), i.e. `for (int i = 0; i < 64; i++) test.add(i);`
 * `test.remove(0L, 32L)` instead of `... 31L)` -> then `test = {32}` correctly.
 * intead of "around 32" smaller numbers are used.

I suspect that the `to` boundary `31` is mapped to the wrong container (?).

**Comment by richardstartin** [comment]
I can probably fix this this afternoon BST if you don't have a fix.

**Comment by incaseoftrouble** [comment]
I may have found a fix, indeed an off-by-one error.

However, I'm quite surprised that this didn't occurr more often, the branch which my fix targets seems rather common.

**Comment by richardstartin** [comment]
On the contrary I doubt remove is battle hardened, I wouldn't be surprised to find that most users only ever append bits, if the bitmaps are modified at all.
