### ISSUE TITLE
orNot still not entirely consistent

### ISSUE THREAD

**Issue by incaseoftrouble** [RoaringBitmap/RoaringBitmap#394]
Hey, sorry for being so annoying :D @richardstartin 

now `orNot` sometimes truncates and sometimes doesn't. Probably an inconsistency between different containers.

Code to reproduce:
```
RoaringBitmap one = new RoaringBitmap();
one.add(0);
one.add(10);

RoaringBitmap other = new RoaringBitmap();
<initialize other>

one.orNot(other, 7);
Assert.assertTrue(one.contains(10));
```
This fails or succeeds depending on how `other` is initialized:

 * Succeeds: No init at all (`other` is empty)
 * Fails: `other.add(2)` (single number)
 * Succeeds: `other.add(2L, 5L)` (range)
 * Fails: `other.add(3L, 5L)` (smaller range)
 * Succeeds: `other.add(1L, 10L); other.remove(2L, 10L);` (single number, but probably represented as a run)
  * Fails: `for (int i : Arrays.asList(0, 1, 2, 3, 4, 5, 6)) { other.add(i); }` (range added one-by-one)

**Comment by richardstartin** [comment]
Sorry this is a remnant of what was there before. Will add a generative test to get more container-wise coverage. Thanks.

**Comment by lemire** [comment]
This should be fixed now. Closing. 

Please keep on finding bugs!

**Comment by richardstartin** [comment]
I hadn’t realised that there was a buffer implementation too, so the changes will need to be ported.

**Comment by lemire** [comment]
+1
