### ISSUE TITLE
The previousValue method sometimes returns incorrect data

### ISSUE THREAD

**Issue by tianshuang** [RoaringBitmap/RoaringBitmap#400]
`
        RoaringBitmap bitmap = new RoaringBitmap();
        String[] array = FileUtils.readFileToString(new File("/tmp/numbers.txt")).split(",");
        for (String value : array) {
            bitmap.add(Integer.parseInt(value.trim()));
        }
        System.out.println(bitmap.contains(1814436753));
        System.out.println(bitmap.previousValue(1828834057));
`

[numbers.txt](https://github.com/RoaringBitmap/RoaringBitmap/files/4521765/numbers.txt)

The above code has the following output:
true
-1

**Comment by tianshuang** [comment]
I dubuged the code and found -1 returned here, [return -1](https://github.com/RoaringBitmap/RoaringBitmap/blob/91e0bef2e9a4c588c288f9fd7c392eea87f0a20d/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L2586)

**Comment by richardstartin** [comment]
@tianshuang which version are you using?

**Comment by Cheappie** [comment]
it can be replicated on current master branch, in previousValue somehow highLowContainer.advanceUntil returns index == size, so there is no such container.

**Comment by richardstartin** [comment]
This is because the value you want to previous value of is larger than the last value in the bitmap. This should probably return `RoaringBitmap.last()`.

@incaseoftrouble you added this defensive check in `725b56db9671e8be2e72787a39683ea2abe6c2f2`. Do you think it should return the last value instead?

**Comment by incaseoftrouble** [comment]
Oh, yes, I don't know what I was doing there.

Mathematical specification: Given set `B` and index `i`, return `max {j \in B | j <= i}` or `-1` if none present (i.e. there is no `j \in B` with `j <= i`).

**Comment by tianshuang** [comment]
Thank you, when will the version that fixes the problem be released? I am going to modify the version dependency in the project.

**Comment by lemire** [comment]
@tianshuang Yes. We will release an update.

**Comment by lemire** [comment]
Closed thanks to @richardstartin 

Release should be out shortly.

**Comment by richardstartin** [comment]
@lemire was this released yet? Can the issue be closed?

**Comment by lemire** [comment]
Closing.
