### ISSUE TITLE
ArrayIndexOutOfBoundsException in BitmapContainer.iandNot

### ISSUE THREAD

**Issue by ArjohnKampman** [RoaringBitmap/RoaringBitmap#402]
I ran into an AIOOBE using the 0.8.13 release. I could try to reproduce with the latest release, but that would take 4 or 5 days to complete and I'm not seeing any relevant changes in this part of the code since 0.8.13. I would appreciate it a lot if someone could have a look at this:

```
java.lang.ArrayIndexOutOfBoundsException: Index 2666 out of bounds for length 2666
	at org.roaringbitmap.BitmapContainer.iandNot(BitmapContainer.java:604)
	at org.roaringbitmap.Container.iandNot(Container.java:487)
	at org.roaringbitmap.RoaringBitmap.andNot(RoaringBitmap.java:1241)
	at com.vound.gee.mem.BitSetIdSet.remove(BitSetIdSet.java:168)
	at ....
```

**Comment by richardstartin** [comment]
@ArjohnKampman do you have a test case to reproduce?

**Comment by ArjohnKampman** [comment]
I have used clean 0.8.13 jar files from maven central. No modifications.

**Comment by ArjohnKampman** [comment]
Note that the AIOOBE is triggered when trying to access the char array in ArrayContainer. The error message suggests that `b2.content` is an array with 2666 elements, but `b2.cardinality` is larger than 2666.

**Comment by richardstartin** [comment]
OK. A reproducer (i.e. the inputs and sequence of events to create the bitmaps such that `andNot` fails like this) would be helpful.

**Comment by lemire** [comment]
@ArjohnKampman 

> I have used clean 0.8.13 jar files from maven central. No modifications.

That's not what @richardstartin meant. He means to please share your code that triggers this problem.

**Comment by richardstartin** [comment]
@lemire actually I did ask if it was a fork, didn't check which overload line 604 was on in 0.8.13 and assumed bitmap vs bitmap. In any case, the `iandNot` code is correct, and this is a symptom of a bug somewhere else. I don't personally have time to consider every possible way to produce bitmaps where an `ArrayContainer` could report larger cardinality than it has, so a reproducer would be great for getting this fixed.

**Comment by ArjohnKampman** [comment]
I'll try to find a way to reproduce it. Will let you know if I succeed.

Op ma 27 apr. 2020 14:29 schreef Richard Startin <notifications@github.com>:

**Comment by lemire** [comment]
> I'll try to find a way to reproduce it. Will let you know if I succeed.

Please do. If we can't reproduce the bug, I am afraid that it is going to be very hard for us to do anything about it. If we can reproduce it, I can guarantee that we will fix it in short order.

**Comment by ArjohnKampman** [comment]
Analyzing my code that builds these bitmaps, I suspect that the cause of the inconsistency is that it adds integers from multiple threads concurrently. I'm going to add some synchronization here and will let you know if the exception pops up again. There's no concurrent bitmap yet, right?

**Comment by lemire** [comment]
@ArjohnKampman 

The user is responsible for handling concurrency so that's a good explanation.
