### ISSUE TITLE
A novel 64bit bitmap implementation

### ISSUE THREAD

**Issue by weijietong** [RoaringBitmap/RoaringBitmap#403]
Current 64bit bitmap implementation using the red-black tree has the following drawbacks:

* red-black tree holds the higher 32 bit key , this will hold much memory space.
* the tree structure is not cpu cache friendly, the bit set operations is not as fast as the 32 bit.
* the serialization/deserialization  performance is bad, as we need to construct/re-construct the tree.

I propose the following solution and will give a corresponding PR:

 The 64bit bitmap will use the [ART](https://db.in.tum.de/~leis/papers/ART.pdf) data structure to hold the key/value pair. The key will be the 64 bit higher part (48 bit here)of the long value( as a byte[] array). The value logically should be a container which holds the low 16 bit. But I design to hold the containers in a separated container array. All the containers will be stored in this array, So the value of the ART tree will hold the corresponding container index of the array.

The benefits is ：

* The ART tree will hold the common part of the 48 bit key . Also this structure is cpu cache friendly ,has a good operation performance, O(k) operations than O(log n).
* The serialization/deserialization of the tree part will be implemented according to the tree structure that means we do not need to re-construct the tree. The actual value container array could be serialized/deserialized separately from the tree part. 

Welcome suggestions! @lemire

**Comment by lemire** [comment]
That sounds very good.

**Comment by morningman** [comment]
Hi @weijietong , is AST fast enough to do the bit operation?

**Comment by weijietong** [comment]
What's the meaning of 'AST' ?

**Comment by morningman** [comment]
> What's the meaning of 'AST' ?

Sorry, I mean ART...

**Comment by yorkane** [comment]
Any progress here?
We are looking forward this 64BIT implementation !

**Comment by weijietong** [comment]
being busy with the unit tests. I think the PR will be ok recently.

**Comment by lemire** [comment]
You probably mean "soon"?

**Comment by weijietong** [comment]
Yes,maybe next week.

**Comment by lemire** [comment]
Closed. I am working on a release.

**Comment by yorkane** [comment]
> Closed. I am working on a release.

Will C-Version benefit from this release for 64bit performance improvement?
