### ISSUE TITLE
ArrayContainer.add(char) error message on 0.9.0 but not on 0.8.20

### ISSUE THREAD

**Issue by maxdemarzi** [RoaringBitmap/RoaringBitmap#417]
**Describe the bug**
Getting this error:
`Failed to invoke procedure `xxxxx`: Caused by: java.lang.NoSuchMethodError: 'org.roaringbitmap.Container org.roaringbitmap.ArrayContainer.add(char)'`

Offending code is:

```
Roaring64Bitmap groupNodeIds = new Roaring64Bitmap();
ResourceIterator<Node> groups = tx.findNodes(Labels.Group);
while (groups.hasNext()) {
         groupNodeIds.add(groups.next().getId());
}
```

**To Reproduce**
The Neo4j stored procedure was only adding node ids which are longs from 0 on up. Less than 10m nodes so no way it went over the limit. Anyway I downgraded to 0.8.20 and changed from Roaring64Bitmap to Roaring64NavigableMap and everything worked just fine.

**Java version:**
Java 11

**Comment by blacelle** [comment]
A temporarily work-around may be to stick with 0.9.0 and Roaring64NavigableMap. Roaring64Bitmap should provide better performances in most-cases, but Roaring64NavigableMap remains available (for now at least).

**Comment by lemire** [comment]
I do not quite understand the error. Does anyone understand ?

We do have an `ArrayContainer.add(char)` method. It replaced `ArrayContainer.add(short)`. So why would version 0.9.0 (which has `ArrayContainer.add(char)`) complain about a missing `ArrayContainer.add(char)` method?

**Comment by blacelle** [comment]
@maxdemarzi Is there a smallest probability the 0.9.0 .jar is corrupted, leading to ArrayContainer.class being corrupted ?

@lemire `ArrayContainer.add(char)` already exists in 0.8.20, suggesting something very wrong is going on (and any code relying on `ArrayContainer.add(char)` would fail, nothing specific to Roaring64Bitmap).

**Comment by lemire** [comment]
@blacelle So it is even less comprehensible than I thought given that this method exists in 0.8.20.

**Comment by lemire** [comment]
@maxdemarzi I have removed the bug tag for now. Can you provide us with a reproducible test case ? I am sure you are having an issue, but I need to reproduce it.

**Comment by maxdemarzi** [comment]
Sorry to waste your time. It was a dependency issue, another procedure was grabbing version 0.7.17.

**Comment by p1nox** [comment]
I'm having this same issue.

@maxdemarzi I setup the version directly in `pom.xml`

```
        <dependency>
            <groupId>org.roaringbitmap</groupId>
            <artifactId>RoaringBitmap</artifactId>
            <version>0.9.0</version>
        </dependency>
```

But I can see that both versions are downloaded, included in maven repository `org/roaringbitmap/RoaringBitmap`, `0.7.17` and `0.9.0`.

Do I need to import a specific version in Java code directly? How another procedure was grabbing a different version as you mentioned?
