### ISSUE TITLE
addOffset not working

### ISSUE THREAD

**Issue by justoruiz** [RoaringBitmap/RoaringBitmap#418]
**Describe the bug**
I believe `RoaringBitmap.addOffset` function doesn't work correctly for the entire range of offsets, as it seems to misbehave from 0xFFFF0000 onwards.  As per the documentation, it should support the entire 32bit range (or, alternatively, a bit set at position 0 should be shifted to the last possible index, so should the inverse operation).

**To Reproduce**
I've attached a small program (Kotlin) that shows the inconsistency.
https://gist.github.com/justoruiz/6ce81f2cf809b61407cb2ea90af98eed

**Java version:**
1.8.0.265 (Azul)
Roaring Bitmap version 0.9.1

**Comment by lemire** [comment]
Verified. Fix is upcoming.

**Comment by lemire** [comment]
PR issued.

**Comment by lemire** [comment]
Fixed in 0.9.2. Thanks for reporting the issue.

**Comment by justoruiz** [comment]
Awesome!! Thank you!!
