### ISSUE TITLE
Roaring64Bitmap.serialize(ByteBuffer) not populating ByteBuffer position value for BigEndian byteOrder buffers

### ISSUE THREAD

**Issue by nuwansa** [RoaringBitmap/RoaringBitmap#422]
reproduce code:
```java
Roaring64Bitmap bitmap = new Roaring64Bitmap();
bitmap.add(1);
bitmap.add(2);
        
ByteBuffer buffer = ByteBuffer.allocate((int) bitmap.serializedSizeInBytes()); //big endian buffer
bitmap.serialize(buffer);
//now buffer position should be equal to bitmap.serializedSizeInBytes()
 assert buffer.position() == bitmap.serializedSizeInBytes() : "invalid position";
```

ByteBuffer is slice into another ByteBuffer inside the HighLowContainer.serialize function, which hides the original buffer if passing ByteBuffer is in BIG_ENDIAN byte order

**Comment by lemire** [comment]
@nuwansa You seem to have identified the issue, would you be willing to prepare a pull request?

**Comment by nuwansa** [comment]
> @nuwansa You seem to have identified the issue, would you be willing to prepare a pull request?

sure, will do

**Comment by lemire** [comment]
Closed via a PR by the submitter. I will be issuing a patch release.
