### ISSUE TITLE
Speed up MutableRoaringBitmap by allocating buffers differently

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#424]
In the org.roaringbitmap.buffer package, we allocate container memory with code such as...

```Java
  LongBuffer array = ByteBuffer.allocateDirect(N).asLongBuffer();
```

The following would apparently be much faster...

```
ByteBuffer.allocate(N * Long.BYTES).order(ByteOrder.nativeOrder()). asLongBuffer()
```

Tweet: https://twitter.com/CZ_JanecekPetr/status/1333522238910443524

**Comment by ijuma** [comment]
Was intentional to use direct buffers in the first example and heap buffers in the second?

**Comment by lemire** [comment]
I am not sure what you mean. What was intentional? The code samples?

**Comment by lemire** [comment]
@ijuma I think I see what you meant. My example is slightly confusing. It is not what I meant.

**Comment by lemire** [comment]
I am going to close this because I remembered that we have optimized path for all Buffer types that backed by arrays. So it is unlikely that allocating Buffer types differently would help much.
