### ISSUE TITLE
Stream/PrimitiveIterators to iterate over set bits

### ISSUE THREAD

**Issue by JervenBolleman** [RoaringBitmap/RoaringBitmap#426]
**Is your feature request related to a problem? Please describe.**
I have a few Stream based API's which iterate over int/long values coming from a datastore. In some optimization cases the datastore could be a serialized roaring bitmap. It would be nice if we had `new RoaringBitmap(...).stream()` methods
to get an `IntStream` and `LongStream` for ease of use.

**Describe the solution you'd like**
I would be happy to contribute the code. This is just a query to ask if the functionality is desired.

**Comment by lemire** [comment]
Absolutely.  That sounds like a great feature.
