### ISSUE TITLE
RoaringBitmap batchOr

### ISSUE THREAD

**Issue by xiaohui0318** [RoaringBitmap/RoaringBitmap#439]
I found a method to carry out OR operation in batches, which was faster than the one on the official website under the condition of large amount of operation data and small single cardinality. However, when I applied this code online, I found that the result was not correct, and there was no problem in my local test. I couldn't figure out the reason. Online waiting for，tks.

```java
public static ImmutableRoaringBitmap batchOr(List<ImmutableRoaringBitmap> bitmaps)
  {
    Object[] arr = new Object[65536];
    for (ImmutableRoaringBitmap bitmap : bitmaps) {
      MappeableContainerPointer p = bitmap.getContainerPointer();
      while (p.hasContainer()) {
        MappeableContainer c = p.getContainer();
        short k = p.key();
        MappeableContainer old = (MappeableContainer) arr[k];
        if (old == null) {
          arr[k] = c.clone().toBitmapContainer();
        } else if (old instanceof MappeableBitmapContainer) {
          ior(old, c);
        } else {
          arr[k] = or(old, c);
        }
        p.advance();
      }
    }
    MutableRoaringBitmap bitmap = new MutableRoaringBitmap();
    final int length = arr.length;
    for (int i = 0; i < length; i++) {
      MappeableContainer mc = (MappeableContainer) arr[i];
      if (mc != null) {
        bitmap.append((short) i, mc);
      }
    }
    return bitmap;
  }
  
  static MappeableContainer ior(MappeableContainer m1, MappeableContainer m2)
  {
    if (m2 instanceof MappeableArrayContainer) {
      return m1.ior((MappeableArrayContainer) m2);
    } else if (m2 instanceof MappeableRunContainer) {
      return m1.ior((MappeableRunContainer) m2);
    }
    
    return m1.ior((MappeableBitmapContainer) m2);
  }
  
  static MappeableContainer or(MappeableContainer m1, MappeableContainer m2)
  {
    if (m2 instanceof MappeableArrayContainer) {
      return m1.or((MappeableArrayContainer) m2);
    } else if (m2 instanceof MappeableRunContainer) {
      return m1.or((MappeableRunContainer) m2);
    }
    
    return m1.or((MappeableBitmapContainer) m2);
  }
```

**Comment by lemire** [comment]
There is a number of issues with this code.  Here are two that I can see...

1.

```
short k = p.key();
```

So `k` can be negative, correct?

2.

```
rr[k] = c.clone().toBitmapContainer();
```

You forcefully convert the container to a bitmap type, but you never go back to convert it back to the container it should use as per the Roaring specification.

---------


While I encourage you to continue you work, it does not look like the approach you are taking is something we would like to do in the main library. If you'd like to do it for your own purposes, that is fine, and feel free to ask questions, but you should thoroughly test your code first, and be willing to spend some time debugging it.

--------

Closing.
