### ISSUE TITLE
for Roaring64Bitmap,    get the result from "and" method is not right

### ISSUE THREAD

**Issue by niwanjia** [RoaringBitmap/RoaringBitmap#442]
****************Describe the bug**************
for Roaring64Bitmap,    get the result from "and" method is not right。  

***************maven  dependency***********
<dependency>
      <groupId>org.roaringbitmap</groupId>
      <artifactId>RoaringBitmap</artifactId>
      <version>0.9.0</version>
</dependency>

***************Java version:****************
jdk1.8.0_112

***************My Test example****************
```Java
import org.roaringbitmap.RoaringBitmap;
import org.roaringbitmap.longlong.Roaring64Bitmap;

import java.io.IOException;

public class AndMethodTest {


    public static void main(String[] args) throws IOException {

        Roaring64Bitmap rbAnd = new Roaring64Bitmap();
        for (long k = 10000; k < 20000; k++) {
            rbAnd.add(k);
        }

        Roaring64Bitmap rbAnd2 = new Roaring64Bitmap();
        for (long k = 15000; k < 20000; k++) {
            rbAnd2.add(k);
        }

        rbAnd.and(rbAnd2);
        System.out.println("roaring64Bitmap结果个数为：" + rbAnd.getLongCardinality());

        Roaring64Bitmap rbAnd3 = new Roaring64Bitmap();
        for (long k = 100000; k < 200000; k++) {
            rbAnd3.add(k);
        }

        Roaring64Bitmap rbAnd4 = new Roaring64Bitmap();
        for (long k = 150000; k < 200000; k++) {
            rbAnd4.add(k);
        }

        rbAnd3.and(rbAnd4);
        System.out.println("roaring64Bitmap结果个数为：" + rbAnd3.getLongCardinality());

        RoaringBitmap rbAnd5 = new RoaringBitmap();
        for (int k = 10000; k < 20000; k++) {
            rbAnd5.add(k);
        }

        RoaringBitmap rbAnd6 = new RoaringBitmap();
        for (int k = 15000; k < 20000; k++) {
            rbAnd6.add(k);
        }

        rbAnd5.and(rbAnd6);
        System.out.println("roaringBitmap结果个数为：" + rbAnd5.getLongCardinality());

        RoaringBitmap rbAnd7 = new RoaringBitmap();
        for (int k = 100000; k < 200000; k++) {
            rbAnd7.add(k);
        }

        RoaringBitmap rbAnd8 = new RoaringBitmap();
        for (int k = 150000; k < 200000; k++) {
            rbAnd8.add(k);
        }

        rbAnd7.and(rbAnd8);
        System.out.println("roaringBitmap结果个数为：" + rbAnd7.getLongCardinality());
    }
}
```

***************test result****************:
roaring64Bitmap结果个数为：5000
roaring64Bitmap结果个数为：68928
roaringBitmap结果个数为：5000
roaringBitmap结果个数为：50000

**Comment by lemire** [comment]
@weijie Could you have a look?

**Comment by weijietong** [comment]
Please use the latest master code to verify the case @niwanjia . I can't reproduce your case by the master code. Maybe @lemire should release a fresh maven version.

**Comment by niwanjia** [comment]
> Please use the latest master code to verify the case @niwanjia . I can't reproduce your case by the master code. Maybe @lemire should release a fresh maven version.

I try to use the latest master code,  the test result is right. Thank you very much! Nice!

**Comment by niwanjia** [comment]
solved

**Comment by lemire** [comment]
@weijietong 

> Maybe @lemire should release a fresh maven version.

The latest release is 0.9.7 and was released after issue 437 was fixed (by you, I believe). I will start a new release process now since you have made additional commits since then.


[![Bintray](https://img.shields.io/bintray/v/roaringbitmap/maven/org.roaringbitmap%3ARoaringBitmap.svg)](https://bintray.com/roaringbitmap/maven/org.roaringbitmap%3ARoaringBitmap)


I am also modifying the issue template to instruct users to explain why they are not using the latest release if so.

Thanks.

**Comment by lemire** [comment]
Version 0.9.8 has been published.
