### ISSUE TITLE
Invalid Cert Breaking Build

### ISSUE THREAD

**Issue by Maithem** [RoaringBitmap/RoaringBitmap#444]
**Describe the bug**
When building master with `./gradlew  build` I see the following error:

```

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':jmh:shadowJar'.
> Could not resolve all dependencies for configuration ':jmh:jmh'.
   > Could not resolve it.uniroma3.mat:extendedset:1.3.4.
     Required by:
         project :jmh
      > Could not resolve it.uniroma3.mat:extendedset:1.3.4.
         > Could not get resource 'https://metamx.artifactoryonline.com/artifactory/pub-libs-releases-local/it/uniroma3/mat/extendedset/1.3.4/extendedset-1.3.4.pom'.
            > Could not HEAD 'https://metamx.artifactoryonline.com/artifactory/pub-libs-releases-local/it/uniroma3/mat/extendedset/1.3.4/extendedset-1.3.4.pom'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

This issue seems to be caused by an invalid cert being provided by [metamx.artifactoryonline.com](metamx.artifactoryonline.com)

![image](https://user-images.githubusercontent.com/7818642/106737263-52643f00-65cb-11eb-9ccb-de2e4a461d46.png)

**RoaringBitmap version:**

 Bug is observed on master

**Java version:**

openjdk version "11.0.9.1" 2020-11-04

**Comment by lemire** [comment]
I cannot reproduce. Note that our code is under CI.

If you believe that there is an issue, please ensure that you can provide steps to reproduce it (on a freshly installed machine) and, ideally, please provide a pull request that fixes the issue you have encountered.

**Comment by Maithem** [comment]
My fork was stale, but didn't notice it. 

Is there any reason why CI doesn't run tests for Java 8 ?

**Comment by lemire** [comment]
I do not think that you can build the library with Java 8.

**Comment by Maithem** [comment]
It does build. I think its a good idea to add java 8 to the CI since many projects that depend on this library actually run on java 8.

**Comment by lemire** [comment]
@Maithem Well, it partially builds:

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/shims/build.gradle.kts#L2

But you have a point.
