### ISSUE TITLE
Roaring64Bitmap::addInt Setting Wrong Bits

### ISSUE THREAD

**Issue by Maithem** [RoaringBitmap/RoaringBitmap#446]
**Describe the bug**
Since int is smaller than long, an int should always map to a positive
number in a long, that is, converting an int to a long should produce
a long in the range of [0, 2^32]. Since addInt directly calls addLong
without doing a proper conversion, the negative sign is being carried
over and setting incorrect positions in the map. For example,
addInt(-1) should be equivilant to addLong(((int) -1) & 0xffffffffL),
but its not. This patch fixes the issue by converting an int to
an unsigned long before calling addLong.

**To Reproduce**
```java
  @Test
  public void testInvalidIntMask() {
    Roaring64Bitmap map = new Roaring64Bitmap();
    int a = 0xFFFF;  // -1 in two's compliment
    map.addInt(a);
    assertEquals(map.getIntCardinality(), 1);
    long addedInt = map.getLongIterator().next();
    assertEquals(0xFFFFL, addedInt);
  }
```

**RoaringBitmap version:**

master 6ec56d38f079fb3694f9ae90542c5d630771b411

**Java version:**

openjdk version "1.8.0_282"

**Comment by lemire** [comment]
Closed by reporter.
