### ISSUE TITLE
Roaring64Bitmap Memory Leak

### ISSUE THREAD

**Issue by Maithem** [RoaringBitmap/RoaringBitmap#450]
**Describe the bug**
Since Roaring64Bitmap only adds to the ART and never removes a
prefix even if the lowpart container is empty, the tree leak memory,
even when empty. This patch will remove the high part from the
HighLowContainer when the lowpart container is empty after
a removeLong operation.
    
Also, this highpart leak can lead to incorrect results when
checking for logical equality.

**To Reproduce**

```java
  @Test
  public void testEquality() {
    Roaring64Bitmap rb1 = new Roaring64Bitmap();
    Roaring64Bitmap rb2 = new Roaring64Bitmap();

    assertEquals(rb1, rb2);
    rb1.addLong(1);
    assertNotEquals(rb1, rb2);
    rb1.removeLong(1);
    assertEquals(rb1, rb2);
  }
```

**RoaringBitmap version:**

current master 52106562712d7406fa812301646e75f84143a630

**Java version:**

openjdk version "1.8.0_282"

**Comment by weijietong** [comment]
Fixed
