### ISSUE TITLE
Roaring64NavigableMap equals Bug + Leak

### ISSUE THREAD

**Issue by Maithem** [RoaringBitmap/RoaringBitmap#452]
**Describe the bug**
When BitmapDataProvider becomes empty after a
removeLong call, the key (high part) is not removed from highToBitmap.
This results in a potential memory leak and incorrect equality check when
comparing two Roaring64NavigableMap maps.

**To Reproduce**
```java
  @Test
  public void testEmptyAfterRemove() {
    Roaring64NavigableMap rbm = new Roaring64NavigableMap();
    Roaring64NavigableMap empty = new Roaring64NavigableMap();
    rbm.addLong(1);
    assertEquals(rbm.getHighToBitmap().size(), 1);
    rbm.removeLong(1);
    assertTrue(rbm.getHighToBitmap().isEmpty());
    assertEquals(rbm, empty);
  }
```

**RoaringBitmap version:**

master as of 3f88e561c733f7be6fb4872d4d2672660961f0f9

**Java version:**

openjdk version "1.8.0_282"

**Comment by lemire** [comment]
@Maithem This was fixed, was it not? Can we close?

**Comment by Maithem** [comment]
@lemire not yet, I'm still thinking about https://github.com/RoaringBitmap/RoaringBitmap/pull/453

**Comment by lemire** [comment]
closed.
