### ISSUE TITLE
Roaring64Bitmap equals Bug + Leak

### ISSUE THREAD

**Issue by javier-godoy** [RoaringBitmap/RoaringBitmap#460]
**Describe the bug** (same as #452, but with `Roaring64Bitmap` instead of `Roaring65NavigableMap`) 

When Container becomes empty after a
removeLong call, the key (high part) is not removed from highLowContainer.
This results in a potential memory leak and incorrect equality check when
comparing two Roaring64Bitmap maps.

https://github.com/RoaringBitmap/RoaringBitmap/blob/37fe4d0cb3ce51a4f6975e614f70d70fa23f8f4f/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java#L222-L224

**To Reproduce**

```
Roaring64Bitmap b1 = new Roaring64Bitmap();
Roaring64Bitmap b2 = new Roaring64Bitmap();

b1.add(1);
b1.removeLong(1);
System.out.println(b1.equals(b2));
```

**RoaringBitmap version:** 0.9.8

**Comment by blacelle** [comment]
@Maithem Some feed regarding shared tests. Thanks.

**Comment by Maithem** [comment]
This bug was already fixed in https://github.com/RoaringBitmap/RoaringBitmap/pull/451

The following test is passing on master:

```java

  @Test
  public void leak1() {
    Roaring64Bitmap b1 = new Roaring64Bitmap();
    Roaring64Bitmap b2 = new Roaring64Bitmap();

    b1.add(1);
    b1.removeLong(1);
    assertEquals(b2, b1);
  }

```

@blacelle I'm working on refactoring tests to test against `LongBitmapDataProvider` interface which will merge both tests from `TestRoaring64Bitmap` and `TestRoaring64NavigableMap`

**Comment by lemire** [comment]
@Maithem  I understand that you recommend we close this issue, correct?

**Comment by Maithem** [comment]
@lemire I believe so. The test passes on master. `0.9.8` was released ~16 days ago, but the fix went it 4 days ago https://github.com/RoaringBitmap/RoaringBitmap/pull/451

**Comment by lemire** [comment]
Closing.

@javier-godoy : if you disagree, please open a new issue with more information.
