### ISSUE TITLE
ZipRealDataRetriever closed stream in next()

### ISSUE THREAD

**Issue by huangfeng1993** [RoaringBitmap/RoaringBitmap#465]
**Describe the bug**

ZipRealDataRetriever closed stream in next()

```
  public int[] next() {
    try ( BufferedReader buf = new BufferedReader(new InputStreamReader(zis));) {
      ....
   }
  }
```
buf is autoclosed after next(), so calling next() twice has wrong with "Stream closed"

**To Reproduce**
run any RealDataBenchmark.

**RoaringBitmap version:**
latest

**Comment by lemire** [comment]
Fixed by https://github.com/RoaringBitmap/RoaringBitmap/pull/466

Note that the fix puts us back to where we were originally, with a dangling ressource that never gets closed.

**Comment by blacelle** [comment]
For the sake of dumb guy not knowing how to properly run these JMH tests from IntelliJ:

    ./jmh/run.sh org.roaringbitmap.realdata.RealDataBenchmarkAnd

@lemire , the following is a simple/not-lazy loading of positions, a priori without leak:

 ```
 /**
   * 
   * @return an {@link Iterable} of int[], as read from the resource
   * @throws IOException something went wrong while reading the resource
   */
  public List<int[]> fetchBitPositions() throws IOException {
    List<int[]> bitPositions = new ArrayList<>();

    try (final ZipInputStream zis = getResourceAsStream()) {
      BufferedReader buf = new BufferedReader(new InputStreamReader(zis));

      while (true) {
        ZipEntry nextEntry = zis.getNextEntry();
        if (nextEntry == null) {
          break;
        }

        try {
          String oneLine = buf.readLine(); // a single, perhaps very long, line
          String[] positions = oneLine.split(",");
          int[] ans = new int[positions.length];
          for (int i = 0; i < positions.length; i++) {
            ans[i] = Integer.parseInt(positions[i]);
          }
          bitPositions.add(ans);
        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }
    return bitPositions;
  }
```

Would it be good enough? (The lazy loading looks not relevant given we loading the whole dataset before each test).

**Comment by lemire** [comment]
Let me try it.
