### ISSUE TITLE
Optimise partialRadixSort 

### ISSUE THREAD

**Issue by Ignition** [RoaringBitmap/RoaringBitmap#470]
That outer loop does 2 passes, you can just unroll it. 
Fist pass copies into the `copy` buffer second pass copies back to the `data` buffer. This eliminates the need for `System.arraycopy`.

https://github.com/RoaringBitmap/RoaringBitmap/blob/39a6de27bae195bc69048e51b2e8d4240547bd98/RoaringBitmap/src/main/java/org/roaringbitmap/Util.java#L1099-L1120

**Comment by Ignition** [comment]
Might also be worth while adding in an early exit check for it the data is already partially pre sorted. Something like 

```
static boolean isPartialSorted(int[] array) {
	for (int i = 0; i < array.length - 1; i++) {
		if ((array[i] & 0xFFFF0000) > (array[i + 1] & 0xFFFF0000))
			return false;
	}
	return true;
}
```

**Comment by lemire** [comment]
It is a good remark.

> That outer loop does 2 passes, you can just unroll it.

Why unroll?

```Java
    public static void partialRadixSort(int[] data) {
        final int radix = 8;
        int shift = 16;
        int mask = 0xFF0000;
        int[] copy = new int[data.length];
        int[] histogram = new int[(1 << radix) + 1];
        int[] primary = data;
        int[] secondary = copy;
        while (shift < 32) {
          for (int i = 0; i < data.length; ++i) {
            ++histogram[((primary[i] & mask) >>> shift) + 1];
          }
          for (int i = 0; i < 1 << radix; ++i) {
            histogram[i + 1] += histogram[i];
          }
          for (int i = 0; i < primary.length; ++i) {
            secondary[histogram[(primary[i] & mask) >>> shift]++] = primary[i];
          }
          // swap
          int[] tmp = primary;
          primary = secondary;
          secondary = tmp;
          //
          shift += radix;
          mask <<= radix;
          Arrays.fill(histogram, 0);
        }
        if(data != primary) {
            System.arraycopy(secondary, 0, data, 0, data.length);
        }
    }
```

> Might also be worth while adding in an early exit check

As a rule, it is probably best to delay optimization passes until one has run benchmarks and can quantify the cost and the benefits. Have you run benchmarks?

**Comment by lemire** [comment]
This `isPartialSorted ` code is almost surely wrong... Keep in mind that Roaring treats int values are unsigned integers. You probably want the following...

```
static boolean isPartialSorted(int[] array) {
	for (int i = 0; i < array.length - 1; i++) {
		if ((array[i] & 0xFFFF0000L) > (array[i + 1] & 0xFFFF0000L))
			return false;
	}
	return true;
}
```

**Comment by Ignition** [comment]
I don't have any comprehensive benchmarks, but for the cases I was testing (not isolated to RoaringBitmaps). I was using `bitmapOfUnordered` with a large array of data (~100'000'000 items) along with other code and getting about 20% speedup by just removing those memory moves, in theory this should be a gain regardless of data size or machine cache sizes. 

Since this is not an in-place sort, detecting the edge case of ordered (or indeed nearly ordered) was useful at avoiding unnecessary allocation & memory moves. But I believe you may to investigate more, maybe find a threshold for when it is worth doing this, this is defiantly noticeable improvement with large arrays but I've not benchmarked small arrays.

**Comment by lemire** [comment]
@Ignition @richardstartin We are going to update the code to avoid the copies. I think that there is a consensus that avoiding unnecessary copies does not require much further discussion.

The additional "is sorted" check is not hard to do (almost literally a single extra line) but I am with @richardstartin that we can't go on just based on how the code looks.

> Since this is not an in-place sort, detecting the edge case of ordered (or indeed nearly ordered) was useful at avoiding unnecessary allocation & memory moves. 

My expectation is that the user of the library almost certainly knows whether the data is sorted. If one has 100M values, one probably know whether they are sorted.

> maybe find a threshold for when it is worth doing this, this is defiantly noticeable improvement with large arrays

If you refer to checking whether they are ordered... this is surely only a benefit if they are sorted. So we have the case of a user calling `bitmapOfUnordered` on large sets of sorted values. Presumably this user does not know that the data is sorted otherwise they would not call `bitmapOfUnordered`.

**Comment by lemire** [comment]
I am closing this. 

@Ignition If you have leftover concerns, please open a new issue, providing benchmarks.

**Comment by Ignition** [comment]
Yeah, refactoring code is difficult, would be good to know it was sorted or not. (not your problem 😄)
I prefer to avoid `Arrays.sort` for large arrays and let RoaringBits handle it, because in theory partial radix sort is less work than a full sort.
It is ok, given the reduced memory move optimisation in `partialRadixSort` I can at least write:
```java
RoaringBitmapWriter<RoaringBitmap> writer = isPartialSorted(arr)
		? RoaringBitmapWriter
			.writer()
			.constantMemory()
			.runCompress(true)
			.get()
		: RoaringBitmapWriter
			.writer()
			.constantMemory()
			.doPartialRadixSort()
			.runCompress(true)
			.get();
writer.addMany(arr);
writer.flush();
var bitmap = writer.getUnderlying();
```

Thank you for looking at this issue, and the speed at making progress introducing it into the codebase.

**Comment by Ignition** [comment]
@lemire FYI, I don't know why (C++ dev, new to Java and how the JIT works) but the unrolled implementation is faster, something to look at.
