### ISSUE TITLE
Flaky Test

### ISSUE THREAD

**Issue by larsk-db** [RoaringBitmap/RoaringBitmap#481]
**Describe the bug**
There is a flaky test in the suite somewhere, most likely `org.roaringbitmap.RoaringBitmapWriterRandomisedTest`, since its both concurrent (introducing non-determinism) and random (all the non-determinism :D).

I have observed the following three possible behaviours when running the full test suite (on macOS...not sure if it makes a difference):

1. All tests complete in around 1min
2. Tests get stuck running for 15min or more (I aborted at this point, because I just assumed they'd never finish)
3. `org.roaringbitmap.RoaringBitmapWriterRandomisedTest` fails with a execution error: 

```
java.util.concurrent.CancellationException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.awaitFinished(NodeTestTask.java:206)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:142)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This might be a bug in Gradle, to be fair, but I think it's still good to track it here, because it's a bit of a pain, tbh^^

**To Reproduce**
Run `./gradlew test --rerun-tasks` a few times, potentially on macOS.

**RoaringBitmap version:**

On `master`.

**Java version:**

```bash
$ ./gradlew -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by lemire** [comment]
Points to stress here:

1. The tests do take a long time (several minutes). They may take longer on a weak machine. It is conceivable that they run in under a minute on a powerful machine but most users should expect several minutes.
2. Our tests all run systematically in CI, with every commit, on GitHub's cloud container and on other systems, we do not experience problems.
3. We could extend our CI tests to cover macOS if we think that there is an issue here. This being said, my own dev. machines all run macOS and I am not encountering a problem.

**Comment by larsk-db** [comment]
> The tests take about 4 minutes on my server. It is possible that you have a machine that is 4x faster. Even so, how do you define 'All tests complete'?

This is my output in the "good" case:
```bash
$ ./gradlew test --rerun-tasks

> Task :RoaringBitmap:compileJava
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:726: warning: [deprecation] RoaringBitmapPrivate in org.roaringbitmap has been deprecated
        RoaringBitmapPrivate.naivelazyor((RoaringBitmap) lowBitmap1, (RoaringBitmap) lowBitmap2);
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:729: warning: [deprecation] MutableRoaringBitmapPrivate in org.roaringbitmap.buffer has been deprecated
        MutableRoaringBitmapPrivate.naivelazyor((MutableRoaringBitmap) lowBitmap1,
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:1123: warning: [deprecation] RoaringBitmapPrivate in org.roaringbitmap has been deprecated
        RoaringBitmapPrivate.repairAfterLazy((RoaringBitmap) lowBitmap);
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:1125: warning: [deprecation] MutableRoaringBitmapPrivate in org.roaringbitmap.buffer has been deprecated
        MutableRoaringBitmapPrivate.repairAfterLazy((MutableRoaringBitmap) lowBitmap);
        ^
4 warnings

> Task :RoaringBitmap:test
objc[85473]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x1003784c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1004094e0). One of the two will be used. Which one is undefined.

BUILD SUCCESSFUL in 1m 18s
16 actionable tasks: 16 executed
```

I interpret this as "the whole test suite ran and completed successfully".

> Note that our tests run in CI, with every commit.

Yeah, of course. But I do like to know if I broke something unexpected before I push preferably. So I tend to run this once before I start working on a new branch to see if anything fails currently on `master` and then again before I actually create a PR so I know if I broke stuff along the way.

> > Tests get stuck running for 15min or more
> 
> What does that mean exactly?

I mean, they run in the sense that they are using CPU time. They may even be making some very slow progress, but considering the time difference to my "normal" just over 1min run time, this seemed like a bad behaviour. I couldn't really tell if there was *some* test that ended up in an endless loop and just made all the others extremely slow because they couldn't get any CPU time, or if something else was going on. But it definitely didn't seem like a "normal" test suite run-time to me, so I got impatient and aborted the command. It actually also left some orphan JVMs I had to clean up manually.

> 
> > org.roaringbitmap.RoaringBitmapWriterRandomisedTest fails with a execution error:
> 
> Did this fail in the normal course of the test, or did you get a `CancellationException` after cancelling the tests?

It fails in the course of the test without any input from my side. It doesn't even take particularly long. Here is my output for one of those cases:

```bash
$ ./gradlew test --rerun-tasks

> Task :RoaringBitmap:compileJava
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:726: warning: [deprecation] RoaringBitmapPrivate in org.roaringbitmap has been deprecated
        RoaringBitmapPrivate.naivelazyor((RoaringBitmap) lowBitmap1, (RoaringBitmap) lowBitmap2);
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:729: warning: [deprecation] MutableRoaringBitmapPrivate in org.roaringbitmap.buffer has been deprecated
        MutableRoaringBitmapPrivate.naivelazyor((MutableRoaringBitmap) lowBitmap1,
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:1123: warning: [deprecation] RoaringBitmapPrivate in org.roaringbitmap has been deprecated
        RoaringBitmapPrivate.repairAfterLazy((RoaringBitmap) lowBitmap);
        ^
/Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:1125: warning: [deprecation] MutableRoaringBitmapPrivate in org.roaringbitmap.buffer has been deprecated
        MutableRoaringBitmapPrivate.repairAfterLazy((MutableRoaringBitmap) lowBitmap);
        ^
4 warnings

> Task :RoaringBitmap:test
objc[85551]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x101d354c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x101dc64e0). One of the two will be used. Which one is undefined.

RoaringBitmapWriterRandomisedTest > RoaringBitmapWriterRandomisedTest > executionError FAILED
    java.util.concurrent.CancellationException at ForkJoinTask.java:1004

6411 tests completed, 4 failed, 30 skipped

> Task :RoaringBitmap:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RoaringBitmap:test'.
> There were failing tests. See the report at: file:///Users/lars.kroll/Programming/RoaringBitmap/RoaringBitmap/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
16 actionable tasks: 16 executed
```

Generally, I'd say 1. and 3. are my most common cases with about equal probability and 2. occurs very rarely. I've only seen it once, maybe twice.

**Comment by larsk-db** [comment]
> I have removed the unseeded random tests that I could find in PR #482 (just merged). 

I've run `./gradlew test --rerun-tasks` again a few times on latest master. Both on my MacBook and on an AWS c5.9xlarge Linux machine. 

Run Results (macOS):

1. Stuck
2. Failed (after 4min this time)
3. Stuck
4. Successful (in 8min)
5. Failed (after 10min)

Run Results (Linux):
1. Successful (in 10min)
2. 

I'll keep running a bunch more of these while in meetings and update this post.
So far, I guess I'm mostly surprised that my measly 8-core MacBook Pro can run the tests sometimes faster than a 36-core AWS instance. Are some of these disk I/O bound?

> Parallelized testing is standard and it is not really practical to expect fully single-threaded usage. If there is a threading issue, then we want to track it and fix it, not forbid multithread.

Oh absolutely. I was in no way suggesting we shouldn't parallelise tests. That'd be terrible :D
The question is: Is it a concurrency issue where we are sharing stuff between concurrent tests or is it a bug in Gradle?

**Comment by lemire** [comment]
> I guess I'm mostly surprised that my measly 8-core MacBook Pro can run the tests sometimes faster than a 36-core AWS instance

In both instances, you are running from a fresh tree...

```
> git clone https://github.com/RoaringBitmap/RoaringBitmap.git
> cd RoaringBitmap
> git checkout master
> ./gradlew test
```

And you are typing `./gradlew test` and not some buffer-aware command like `./gradlew test --rerun-tasks`.

Correct?

My 2020 Macbook Pro (M1) takes over 7 minutes to run these tests.

**Comment by larsk-db** [comment]
> > Is it a concurrency issue where we are sharing stuff between concurrent tests or is it a bug in Gradle?
> 
> It runs without problem on my macs (I am a mac user) and in CI.
> 
> I will see about adding macos tests in CI.

Well, you can see it also failed once on AWS. It just seems to be a lot rarer. Race condition that depends on kernel primitives perhaps?

**Comment by lemire** [comment]
> Well, you can see it also failed once on AWS.

Which test failed?

**Comment by larsk-db** [comment]
> > Well, you can see it also failed once on AWS.
> 
> Which test failed?

Run number 3. It's the same as always, it fails with a cancellation exception. I stopped checking the suite, but I assume it's `org.roaringbitmap.RoaringBitmapWriterRandomisedTest` again.

**Comment by larsk-db** [comment]
What I find very strange is that there is such a HUGE range of possible test run times: between 1.5min and 16min. 

I'm thinking now the ones I declared as "stuck" were just on the slow ends and I got impatient, because I didn't expect this difference.

I do get the <5min runtime a lot more rarely since your PR than before, so it seems that random stuff may have been (and may still be) a cause for this.

**Comment by larsk-db** [comment]
> I have just added macOS tests in CI. They pass.
> 
> > it fails with a cancellation exception.
> 
> I have never seen a cancellation exception. We do not see it in CI and we test with various JDKs and now on both macOS and Linux.

As you can see above, I'm getting them about 50% of the runs on my macbook and very rarely on AWS.

**Comment by lemire** [comment]
The way we handle these issues with CI tests. I cannot reproduce your issue in CI and I cannot reproduce it locally (even though I run macOS).

I understand that you believe that there is a bug. If so, I encourage you to investigate and provide a pull request. Given that I cannot reproduce the issue, you have to understand that I cannot do anymore.

I did what I could.

**Comment by larsk-db** [comment]
Ok, that's fair. But just as a final question: Do you also see these MASSIVE differences in test run-time? I feel like this is somehow at the heart of the problem and it would help me try and track this down.

**Comment by lemire** [comment]
@larsk-db 

> Do you also see these MASSIVE differences in test run-time?

We do not. You can watch the tests running in CI and see how long they take. Certainly there are variations but not massive ones.

**Comment by larsk-db** [comment]
Ok, so I ran out of ideas and randomly tried with different JDKs (14 on AWS and 11 on my mac) and now I've been seeing super consistent (in terms of timing) runs with no failures in both environments. It seems something about the funny JDK we use at work doesn't get along with either Gradle or something in the tests.

I still think it's funny that my 8-core MacBook executes everything in a bit over half the time that the 36-core AWS node does, but both are pretty fast now (2min 30s vs 4min and a bit), so...I'll take it^^

I'll close the issue. I don't think either of our time is well spent trying to figure out why exactly this is happening on this one particular JDK version, which is anyway dated.

**Comment by richardstartin** [comment]
Just to say I haven't really touched this project in anger in a long time, and I am having lots of issues with it today, including this test failure.

**Comment by lemire** [comment]
@richardstartin So you can reproduce it?

**Comment by richardstartin** [comment]
Actually no, sorry, it turns out I had just broken the radix sort 🤣
