### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown by or() method in some multithreaded application

### ISSUE THREAD

**Issue by griffinjm** [RoaringBitmap/RoaringBitmap#487]
**Describe the bug**
An ArrayIndexOutOfBoundsException gets thrown when OR-ing 2 bitmaps.
```java
java.lang.ArrayIndexOutOfBoundsException: null
at org.roaringbitmap.Util.unsignedUnion2by2(Util.java:1025) ~[RoaringBitmap-0.8.12.jar:?]
at org.roaringbitmap.ArrayContainer.ior(ArrayContainer.java:738) ~[RoaringBitmap-0.8.12.jar:?]
at org.roaringbitmap.Container.ior(Container.java:652) ~[RoaringBitmap-0.8.12.jar:?]
at org.roaringbitmap.RoaringBitmap.or(RoaringBitmap.java:2266) ~[RoaringBitmap-0.8.12.jar:?]
```

**To Reproduce**
I think the issue is that bitmap2 which is getting OR-ed with bitmap1 can also be getting OR-ed with other bitmaps at the same time. That is not to say that bitmap2 is being modified itself, but it is being used to add its contents to other bitmaps. I have not seen this happen in single threaded tests, and only under load in a Production environment.
```java
RoaringBitmap roaringBitmap1; // method local bitmap
RoaringBitmap roaringBitmap2; // shared bitmap used across multiple threads
roaringBitmap1.or(roaringBitmap2); // leads to AIOOBE
```

**RoaringBitmap version:**
0.8.12

**Java version:**
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Comment by lemire** [comment]
Thanks for the report.

You need to either produce a reproducible case that we can inspect, or else, you need to provide an analysis to demonstrate that there is a bug in the `RoaringBitmap` library. It is simply impossible for us to do anything right. We do not have evidence that there is a bug in `RoaringBitmap`.

>I think the issue is that bitmap2 which is getting OR-ed with bitmap1 can also be getting OR-ed with other bitmaps at the same time. 

The most straightforward conclusion from your report is that you have some data race. The `RoaringBitmap` library does not provide thread safety. It is entirely the responsibility of the user to avoid data races.


You can use a tool such as [RaceD](https://fbinfer.com/docs/checker-racerd/) to diagnose the data race in your application. There are other such tools and techniques to diagnose data races.

If, after diagnosing the data race, you trace it back to a bug in `RoaringBitmap` as opposed to a bug in your application, we will be eager to work with you to fix it.

**Comment by griffinjm** [comment]
@lemire you are absolutely correct, it turns out that what I thought was a method local bitmap was actually shared and multiple threads could access it at the same time. Apologies for taking some of your time, closing this issue.

**Comment by lemire** [comment]
Note that mere access should be fine if the data is nit mutated.
