### ISSUE TITLE
Invalid cache reset in FastRankRoaringBitmap

### ISSUE THREAD

**Issue by novoj** [RoaringBitmap/RoaringBitmap#498]
**Describe the bug**

Method `.select(rec)` might return confusing results when `.rank(rec)` is called before first element is added to the FastRankRoaringBitmap.

The problem is that first call to rank will create `highToCumulatedCardinality` with zero elements in method `org.roaringbitmap.FastRankRoaringBitmap#preComputeCardinalities`. But then any write call to the FastRankRoaringBitmap that sould normally purge the cache will not pass this condition:

``` java
  private void resetCache() {
    // Reset the cache on any write operation
    if (highToCumulatedCardinality != null && highToCumulatedCardinality.length >= 1) {
      // We tag the first bucket to indicate the cache is dismissed
      cumulatedCardinalitiesCacheIsValid = false;
    }
  }
```

The fix is to remove `highToCumulatedCardinality.length >= 1` but I fear this has some reasoning I don't see.

**To Reproduce**

Test case:

``` java
@Test
void testCacheIsNotReset() {
	FastRankRoaringBitmap rankRoaringBitmap = new FastRankRoaringBitmap();
	assertEquals(0, rankRoaringBitmap.rank(3));
	rankRoaringBitmap.add(3);
	rankRoaringBitmap.add(5);
	assertEquals(3, rankRoaringBitmap.select(0));
	assertEquals(5, rankRoaringBitmap.select(1));
}
```

**RoaringBitmap version:** 0.9.10

**Java version:** JDK11

**Comment by lemire** [comment]
cc @khitrin @richardstartin

**Comment by lemire** [comment]
@novoj  Do you want to contribute a pull request to fix the issue?

**Comment by richardstartin** [comment]
I don’t remember what this was for; I’ve never used it. I think @blacelle might have contributed this.

**Comment by richardstartin** [comment]
It’s probably more widely used than you might expect because its name makes it sound fast. I’d be curious to know what the motivation is for speeding up rank calculations.

**Comment by blacelle** [comment]
> I’d be curious to know what the motivation is for speeding up rank calculations.

I used to work on a fork of MAT (https://www.eclipse.org/mat/) to handle very large heaps. But I feel dumb, as I can not find this fork anymore... Oh, got it:

https://github.com/solven-eu/pepper/blob/master/mat/src/main/java/org/eclipse/mat/parser/index/IndexWriter.java#L264

MAT relies on an index from an objectId to the object position in-memory. objectId being the index of the object in the memory layout, while reading memory in one pass (i.e. the object with lower memory address has objectId==0, next object in memory layout has objectId==1), it fits into a Bitmap if you consider the rank as the objectId. The need to get quickly the objectId given the objectAddress leads to the need for a fast .rank (this in the context of 64-bits address -> Bitmap of 64-bits integers).

**Comment by novoj** [comment]
I could make a PR but I'd like to know first whether the `highToCumulatedCardinality.length >= 1` doesn't have some reason which I don't see. The fix seems really straightforward.

@lemire I don't think that the `FastRankRoaringBitmap` was meant to be immutable since there is clear logic in write methods (add / remove) that resets the cache. And yes - I chose this implementation because in my use-case I'm going to call `rank` repatedly many times, so I wanted to use most performant implementation available.

The workaround for the problem is also simple - I just don't call rank on empty bitmap. This is the method that I use that mimics Java Arrays.binarySearch() upon RoaringBitmap implementation:

``` java
/**
 *
 * @param roaringBitmap
 * @param recordId
 * @return
 */
static int indexOf(ImmutableBitmapDataProvider roaringBitmap, int recordId) {
	// this row prevents https://github.com/RoaringBitmap/RoaringBitmap/issues/498 ocurrence
	if (roaringBitmap.isEmpty()) {
		return -1;
	}
	final int rank = roaringBitmap.rank(recordId);
	final int index = rank - 1;
	final int nextRecordId = index >= 0 ? roaringBitmap.select(index) : -1;
	return nextRecordId == recordId ? index : -1 * (rank + 1);
}
```

**Comment by lemire** [comment]
It appears that the mysterious condition was written by @blacelle 

Benoit, can you have a look at this code and help us figure out why you seem to only want to reset when `highToCumulatedCardinality.length >= 1`. Surely there must a reason?

**Comment by blacelle** [comment]
Of course, just need some time thinking about it. I see no obvious reason for now.

@novoj please open a PR so that it confirms tests are OK with suggested fix

**Comment by blacelle** [comment]
I fear it may be some sort of optimizations, to skip cache dismissal.

Another fix might be not to initialize the cache when rank is called on empty bitmap. Need to check properly with a proper IDE.

**Comment by khitrin** [comment]
Removing this condition seems like correct solution, but looking around the code I've found some strange things in FastRankRoaringBitmap.select().

Filled separate issue for it: #499

**Comment by blacelle** [comment]
I feel this bug is due to a poor refactoring following @lemire feedback here (https://github.com/RoaringBitmap/RoaringBitmap/pull/192#issuecomment-350021230). (@lemire You're absolutely not in cause, but I feel I needed this >=1 constrain for the initial implementation which did not have a cumulatedCardinalitiesCacheIsValid)

**Comment by lemire** [comment]
@blacelle Never feel shy about blaming me. I make lots of mistakes!

**Comment by blacelle** [comment]
Really, no blaming at all. I poorly improved my PR following your good review, but your review helps remembering why at was relevant at some point to have this .length check. Fixes are coming.

**Comment by blacelle** [comment]
Thanks a lot for the unit-tests, helps fixing with low-burden.

**Comment by novoj** [comment]
Here's the pull request: https://github.com/RoaringBitmap/RoaringBitmap/pull/501 ... all tests are passing but I haven't discovered any tests for FastRankRoaringBitmap itself so I've created new one.
