### ISSUE TITLE
[Roaring64Bitmap] Incorrect result of `and` between disjoint bitmaps.

### ISSUE THREAD

**Issue by damnMeddlingKid** [RoaringBitmap/RoaringBitmap#502]
**Describe the bug**

I've encountered a case where the intersection of two disjoint sets gives a non-zero cardinality.

I debugged the issue and i believe it happens during ART traversal to remove the non-matching containers. Specifically theres a bug in this line https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java#L130

```
int mismatchIndex = ArraysShim.mismatch(node.prefix, 0, node.prefixLength, key, dep, node.prefixLength);
```

I believe the last argument should be something like `dep + node.prefixLength` otherwise it doesn't represent an end index starting from `dep`. It seems like this issue only happens at higher depths which is probably why it doesn't always affect operations.

**To Reproduce**

Heres a minimal example that reproduces the issue through an intersection of two disjoint sets.

```
import org.roaringbitmap.longlong.Roaring64Bitmap;

long[] left = new long[]{1076595327100L, 5060192403580L, 5035915149436L, 1074755534972L, 5060308664444L};
long[] right = new long[]{3470563844L};

Roaring64Bitmap leftMap = Roaring64Bitmap.bitmapOf(left);
Roaring64Bitmap rightMap = Roaring64Bitmap.bitmapOf(right);

leftMap.and(rightMap);

System.out.println(leftMap.getLongCardinality()); // 4
```

Expectation: Since these sets are disjoint the reported cardinality should be 0
Actual: The actual reported cardinality is 4. It manages to remove the container for `5035915149436L` but can't find the other 4.

**Proposed solution**

I'd love to work on this issue, I can think of a few different ways to go about it:

1) Rewrite the line with `dep + node.prefixLength`
2) I was comparing the traversal done here to a similar case in `findByKey` and noticed it uses `commonPrefixLength` to do the key comparison, so we can adopt that in `removeSpecifyKey`.
3) Instead of doing the traversal in `removeSpecifyKey` we could call `findByKey` to get the node and then work on it. I like the simplicity of this solution but I'm not sure if there are performance implications.

Would like to know thoughts about these approaches or any others I haven't considered. thanks!.

**RoaringBitmap version:**

0.9.15

**Java version:**

Java 1.8.0

**Comment by richardstartin** [comment]
Bugs keep turning up for this implementation, and most of them (especially this one) would have showed up after less than a second of randomised testing. The fuzz-tests module has tests for the 32 bit implementations, I suggest extending it. A and B = empty for disjoint A, B is a great property to test.

**Comment by damnMeddlingKid** [comment]
Agreed, I was thinking along the same lines.  The fuzzing could be broken
into its own issue and PR to keep the work easier to review.

So 1 PR with a fix + unit test and then a follow up for the fuzzing ?

**Comment by lemire** [comment]
@damnMeddlingKid Please submit a PR with a fix and a verification (test).

@richardstartin is, of course, correct, but I do not think that it implies that we should not quickly fix bugs as they are found. We should!

**Comment by damnMeddlingKid** [comment]
👍 I'll start working on that.
