### ISSUE TITLE
[Roaring64Bitmap] Out of bounds exception in Node48 during initShuttleFrom

### ISSUE THREAD

**Issue by larsk-db** [RoaringBitmap/RoaringBitmap#504]
Looks like I found yet another issue in the seek implementation for `Roaring64Bitmap`.

I'll look into it as soon as I can. Just reporting so people are aware the issue exists.

**Describe the bug**

```
java.lang.ArrayIndexOutOfBoundsException: 536870911
        org.roaringbitmap.art.Node48.getNextSmallerPos(Node48.java:149)
        org.roaringbitmap.art.Node48.getNearestChildPos(Node48.java:47)
        org.roaringbitmap.art.AbstractShuttle.visitToLeafFrom(AbstractShuttle.java:209)
        org.roaringbitmap.art.AbstractShuttle.visitToLeafFrom(AbstractShuttle.java:240)
        org.roaringbitmap.art.AbstractShuttle.initShuttleFrom(AbstractShuttle.java:33)
        org.roaringbitmap.art.LeafNodeIterator.<init>(LeafNodeIterator.java:60)
        org.roaringbitmap.art.Art.leafNodeIteratorFrom(Art.java:304)
        org.roaringbitmap.longlong.HighLowContainer.highKeyLeafNodeIteratorFrom(HighLowContainer.java:94)
        org.roaringbitmap.longlong.Roaring64Bitmap.forAllInRange(Roaring64Bitmap.java:182)
```

**To Reproduce**
~~I don't have a reproduction, yet. It occurred into a non-deterministic benchmark run.~~

~~I'm going to try and find one as soon as I have some free time.~~

See #505 for reproduction test.

**RoaringBitmap version:**

0.9.14

**Java version:**

Please tell us which Java version you are using.

OpenJDK 1.8.0_282

**Comment by lemire** [comment]
I have removed the 'bug' label for now. We need a test.

(I am sure you have encountered the issue, but until we can reproduce it, we do not actually know that it is a bug in Roaring64Bitmap.)
