### ISSUE TITLE
When restoring data from roaring64Bitmap, the report bug is  array is out of bounds

### ISSUE THREAD

**Issue by long1208** [RoaringBitmap/RoaringBitmap#507]
**Describe the bug**

When restoring data from roaring64Bitmap, the report bug is  array is out of bounds
just restoring part of data
the data is example :"25480628575420416,26887170096644096,26954735041658880,35327856722591744,35425396110934016"
the roaring64Bitmap longCardinality is 189110  ，
restoring data  Cardinality is 91000

**To Reproduce**
code is like this:
  while (longIterator.hasNext()) {
            // we print a page
            for (int k = 0; (k < pageSize) && longIterator.hasNext(); k++) {
                bufferedWriter.write(String.valueOf(longIterator.next()));
                bufferedWriter.write(",");
            }
            bufferedWriter.newLine();
        }
        bufferedWriter.close();

bug is

 roaring64Bitmap: 189110
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at org.roaringbitmap.art.AbstractShuttle.moveToNextLeaf(AbstractShuttle.java:95)
	at org.roaringbitmap.art.LeafNodeIterator.advance(LeafNodeIterator.java:66)
	at org.roaringbitmap.art.LeafNodeIterator.hasNext(LeafNodeIterator.java:84)
	at org.roaringbitmap.longlong.Roaring64Bitmap$PeekableIterator.hasNext(Roaring64Bitmap.java:853)
	at cn.doitedu.Test_demo.main(Test_demo.java:79)

**RoaringBitmap version:**
  0.9.14
Please report bugs after testing the latest version of the library. If you are using an older version of the library, please explain.

[For up-to-date releases, we recommend configuring maven and gradle to depend on the Jitpack repository](https://jitpack.io/#RoaringBitmap/RoaringBitmap). 

**Java version:**
Please tell us which Java version you are using.
java version "1.8.0_171"

**Comment by lemire** [comment]
@weijietong Would you have a look?

**Comment by weijietong** [comment]
@long1208 Could you try the latest code, there's come bugs fixed after your used version.

**Comment by long1208** [comment]
> Could you try the latest code, there's come bugs fixed after your used version.

i use the version 0.9.15 ,is still report that bug , what version i should use?

**Comment by weijietong** [comment]
Could you give a runnable test case code to reproduce the bug.

**Comment by long1208** [comment]
@weijietong 
code like this :
        Roaring64Bitmap roaring64Bitmap = deSerializeRoaringBitmap(ids);
        
        PeekableLongIterator longIterator = roaring64Bitmap.getLongIterator();

        final int pageSize = 1000;

        BufferedWriter bufferedWriter = null;


        bufferedWriter = new BufferedWriter(new FileWriter("test3.txt"));

        while (longIterator.hasNext()) {
      
            for (int k = 0; (k < pageSize) && longIterator.hasNext(); k++) {
                bufferedWriter.write(String.valueOf(longIterator.next()));
                bufferedWriter.write(",");
            }
            bufferedWriter.newLine();
        }
        bufferedWriter.close();
    }

    private static Roaring64Bitmap deSerializeRoaringBitmap(String ids) throws
            Exception {
        Roaring64Bitmap roaring64Bitmap = Roaring64Bitmap.bitmapOf();
        DataInputStream dataInputStream = new DataInputStream(new ByteArrayInputStream(Base64.decodeBase64(ids)));
        roaring64Bitmap.deserialize(dataInputStream);
        return roaring64Bitmap;
    }

ids is from mysql blob Format field。

**Comment by long1208** [comment]
@weijietong How to send mysql data to you？

**Comment by long1208** [comment]
[text1.txt](https://github.com/RoaringBitmap/RoaringBitmap/files/6979615/text1.txt)

**Comment by long1208** [comment]
@weijietong  this is other code:
` static String sql = "SELECT id,crowd_mix_id,cast(ids as CHAR ) as ids " +
            "FROM " +
            "vboard" +
            ".crowd_mix_result_test where crowd_mix_id=1093 ;";
    static ResultSet rs = null;
    public static final String url =
            "jdbc:mysql://localhost:3306/vboard?serverTimezone=UTC";
    public static final String user = "root";
    public static final String password = "123456";
    public static Connection conn = null;
    public static PreparedStatement ps = null;
    public static void main(String[] args) throws Exception {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, password);
            ps = conn.prepareStatement(sql);
        } catch (Exception e) {
            e.printStackTrace();
        }

        //显示数据
        String ids = "";
        try {
            rs = ps.executeQuery();//执行语句

            while (rs.next()) {
                int id = rs.getInt("id");//输入要输出的元素名
                int crowd_mix_id = rs.getInt("crowd_mix_id");
                ids = rs.getString("ids");;
                Roaring64Bitmap roaring64Bitmap = deSerializeRoaringBitmap(ids);
                long longCardinality = roaring64Bitmap.getLongCardinality();
                System.out.println("id:" + id + "  " + "crowd_mix_id: " + crowd_mix_id + " roaring64Bitmap: " + "" + longCardinality);
            }
            rs.close();
            conn.close();
            ps.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
`

**Comment by weijietong** [comment]
I am sorry, I can't give a help. The given codes and data is not friendly (also terrible) to fix the bug. I suggest you do a debugging and welcome to give a PR to fix it.

**Comment by long1208** [comment]
ok , thanks ,i change  Roaring64Bitmap  to Roaring64NavigableMap  ，it ok . i will later see it .

**Comment by blacelle** [comment]
@long1208 Could you provide the raw longs (e.g. in TXT format, one long per line)before the (de)serializing issue (i.e. the 189110 longs if I understand correctly)? Hence, I understand we shall be able to reproduce the issue by loading giving longs (which will be much easier than through mySQL), and (de)serializing.

**Comment by long1208** [comment]
@blacelle 
the raw data ,this is my from Roaring64NavigableMap  restoring data.
[test3.txt](https://github.com/RoaringBitmap/RoaringBitmap/files/6981627/test3.txt)

**Comment by blacelle** [comment]
@weijietong @lemire  Unrelated to this issue: Roaring64Bitmap.add(long, long) will add the range between the 2 longs, while Roaring64Bitmap.add(long...) will add each long. Hence, I feel there is a confusion over the behavior of Roaring64Bitmap.add over 2 longs as some would expect adding the 2 longs, and not the range. Should we rename Roaring64Bitmap.add(long, long) into Roaring64Bitmap.addRange(long, long). (same for Roaring64NavigableMap)

There is also a RoaringBitmap.add(int, int), but it is deprecated (in profit of a RoaringBitmap.add(long, long)). @lemire Do you feel we should rename both into XXX.addRange (or anything less confusive)?

**Comment by blacelle** [comment]
(I may happen a separate ticket, I just spot this will digging into this)

**Comment by lemire** [comment]
@blacelle `addRange` throughout feels like the better choice. We could deprecate the abuse of the method `add` and suggest everyone moves to `addRange`. This can be done as a distinct PR.

**Comment by weijietong** [comment]
@long1208  please run your code using the [PR](https://github.com/RoaringBitmap/RoaringBitmap/pull/509), I think I have fixed the bug. Thanks for your final brief data.

**Comment by weijietong** [comment]
>  Should we rename Roaring64Bitmap.add(long, long) into Roaring64Bitmap.addRange(long, long). (same for Roaring64NavigableMap)

Aggree!

**Comment by weijietong** [comment]
@lemire I think we need a new release to have this fix.

**Comment by lemire** [comment]
Of course! I will take care of the release soon.

**Comment by long1208** [comment]
@weijietong i try it use Roaring64Bitmap  ,it work , thanks very much ,also thanks to you   @blacelle

**Comment by long1208** [comment]
@weijietong  could you tell me ,what method  i can get the Roaring64Bitmap size in memory. i just try roaring64Bitmap.getLongSizeInBytes() is not work .

**Comment by blacelle** [comment]
roaring64bitmap.serializedSizeInBytes()

@weijietong Should we implement.getLongSizeInBytes() a way or another?

In Roaring64NavigableMap, I went for:

```
  @Override
  public int getSizeInBytes() {
    return (int) getLongSizeInBytes();
  }
```
(Far from perfect, both implementation should have similar behavior)

**Comment by lemire** [comment]
See release 0.9.16

**Comment by weijietong** [comment]
@blacelle I have no plan to implement these two methods, as I am busy with my work now.
