### ISSUE TITLE
AND between two Roaring64NavigableMaps throws unsupported operation

### ISSUE THREAD

**Issue by vnesek** [RoaringBitmap/RoaringBitmap#528]
**Describe the bug**
And between two bitmaps throws exception.

**To Reproduce**
```kotlin
        val x = Roaring64NavigableMap()
        val y = Roaring64NavigableMap.bitmapOf(4)
        
        x.add(123, 124)
        x.and(y)
```

throws
```
.and is not between class org.roaringbitmap.longlong.Roaring64NavigableMap and class org.roaringbitmap.buffer.MutableRoaringBitmap
java.lang.UnsupportedOperationException: .and is not between class org.roaringbitmap.longlong.Roaring64NavigableMap and class org.roaringbitmap.buffer.MutableRoaringBitmap
	at org.roaringbitmap.longlong.Roaring64NavigableMap.and(Roaring64NavigableMap.java:880)

```
**RoaringBitmap version:**
0.9.22

**Java version:** 
16

**Comment by lemire** [comment]
@blacelle Could you have a look?

**Comment by lemire** [comment]
@blacelle I am curious... What is the rationale for these code sequences to generate what are effectively non-interoperable internal types?

```kotlin
val x = Roaring64NavigableMap()
x.add(123, 124)
```

```kotlin
val y = Roaring64NavigableMap.bitmapOf(4)
```

(You don't have to answer that... but it seems somewhat... interesting...?)

**Comment by richardstartin** [comment]
I think they should have been kept separate in this class, it's difficult to abstract over the storage types and doing so would impose costs. So I would have been tempted to introduce a generic type parameter for the bitmaps in the leaves, rather than try to handle everything as a `BitmapDataProvider` (or whatever it's called) and either miss combinations or implement aggregation routines for the cartesian product of container and storage types.

**Comment by vnesek** [comment]
For a user of an API this is confusing. If I read docs correctly Roaring64NavigableMap() is mutable object.

This belief is reinforced by helper static code:

```java
  public static Roaring64NavigableMap bitmapOf(final long... dat) {
    final Roaring64NavigableMap ans = new Roaring64NavigableMap();
    ans.add(dat);
    return ans;
  }
```

Same code using RoaringBitmap or Roaring64Bitmap works.

My use case involves around 1M low cardinality (up to 50) bitmaps that are joined into bigger blocks and chunked afterwards for processing. Should I use Roaring64Bitmap instead?
