### ISSUE TITLE
Roaring64Bitmap.removeLong results in a NegativeArraySizeException

### ISSUE THREAD

**Issue by ayush-san** [RoaringBitmap/RoaringBitmap#558]
**Describe the bug**
I am trying to build a funnel for a tracking system where an event can transition to multiple states. After an event has moved to a new state(B from A), I will want to remove it from calc of state A

While calling `roaringBitmap.removeLong(trackId);`, I am getting the following exception 

```
Caused by: java.lang.NegativeArraySizeException
	at org.roaringbitmap.art.Node4.remove(Node4.java:124)
	at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:144)
	at org.roaringbitmap.art.Art.remove(Art.java:104)
	at org.roaringbitmap.longlong.HighLowContainer.remove(HighLowContainer.java:63)
	at org.roaringbitmap.longlong.Roaring64Bitmap.removeLong(Roaring64Bitmap.java:752)
	at flinkcommonjobs.helpers.FunnelCustomProcess.process(FunnelCustomProcess.java:107)
```
Plot of count emitted by the bitmap, as you can see I am not getting the above exception everytime
<img width="428" alt="image" src="https://user-images.githubusercontent.com/57655135/167806372-e221c2d1-a868-4585-a3dd-5b769feb6849.png">

trackId are generated in a random order.

Should I call `runOptimize` before removing the Id? 

**To Reproduce**
My code snippet

```java
Roaring64Bitmap roaringBitmap = distinctCountState.get(eventKey);
if (!roaringBitmap.isEmpty()) {
    roaringBitmap.removeLong(trackId);
    distinctCountState.put(eventKey, roaringBitmap);
}
```

**RoaringBitmap version:** 0.9.26 https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap/0.9.26
**Java version:** openjdk version "1.8.0_312"

**Comment by lemire** [comment]
@weijietong : could you have a look ?

**Comment by weijietong** [comment]
@ayush-san please try to use the latest version to verify your case.We have fixed a empty() bug after your using version.And the given reproduced codes by you is not runnable to reproduce the bug.

**Comment by ayush-san** [comment]
@weijietong From where can I get the latest version(I can't run this job on my local environment, I need to deploy it on our prod env)? Maven repository still has `0.9.26` as the latest version

**Comment by weijietong** [comment]
Sorry , I make a mistake about the version number, your 0.9.26 version include all the 64 bit version bug fixes. To your case, I think the reproducing code is not right. The Roaringbitmap collection is not empty doesn't indicat it contains the to be remove key. The interface doesn't guarantee it won't throw exception in case remove a not existing key. I suggest you need to rewrite your coding logic to ensure the to be remove key does exist in the Roaring64Bitmap.

**Comment by ayush-san** [comment]
@weijietong Will this be the right check `roaringBitmap.contains(trackId)`? What will be the time complexity of this operation?

**Comment by richardstartin** [comment]
> 

This sounds like a usability problem - remove methods should be idempotent.

**Comment by weijietong** [comment]
I do a simple test case to remove some non-exist keys from the roaring64bitmap, not occured an exception. I am not sure it's a bug or not.  The exception stack shows the array size be a negative one which is also strange.Hope you can give a reproducible codes.

BTW, store a random value to bitmap is not ideal. It maybe not save the memory,on the contrary, it may wast the memory.

**Comment by ayush-san** [comment]
@weijietong As I mentioned, this issue is happening randomly. The job will run for some time and then fail with this exception. Stacktrace points to the `removeLong` function call.

**Comment by weijietong** [comment]
also need to log the removed one.

**Comment by ayush-san** [comment]
I am using flink with a parallelism of 7 but no two operators will be in a race condition

**Comment by richardstartin** [comment]
`Roaring64Bitmap` isn't thread-safe so if any of those operators mutate the same bitmap you will generally have issues.

**Comment by lemire** [comment]
> no two operators will be in a race condition

The code sample you provide above does not appear to contain any lock. How do you know that you are not accessing the same bitmap in two separate threads?

**Comment by ayush-san** [comment]
@lemire I am using keyed state in flink which makes sure that no two keys are accessed by the other state
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/fault-tolerance/state/#using-keyed-state

**Comment by lemire** [comment]
We will be happy to receive a reproducible bug report.

As @weijietong correctly explained, just capture the state of the bitmap and the value of the key being removed. Then verify that you can isolate and reproduce the issue. We will happily investigate and fix it... but we need a reproducible single-threaded case.
