### ISSUE TITLE
Serialized class org.roaringbitmap.RoaringBitmapSupplier must implement java.io.Serializable

### ISSUE THREAD

**Issue by chenyongyin** [RoaringBitmap/RoaringBitmap#563]
dubbo version 2.7.7. Last error is: Failed to invoke remote method: xxxx, provider,cause: org.apache.dubbo.remoting.RemotingException: Failed to send response: Response [id=4, version=2.0.2, status=20, event=false, error=null, result=AppResponse [value={0,682,684,685,719,720,721,722,725,726,728,729,752,759,771,772,776,782,793,796,1730,1811,1833,1952,1965,1968,1970,1971,1972,1975,1976,1977,1978,1979,1981,1984,1987,1988,1989,1990,1991,1993,2000,2001}, exception=null]], cause: java.lang.RuntimeException: Serialized class org.roaringbitmap.RoaringBitmapSupplier must implement java.io.Serializable

**Comment by lemire** [comment]
It does not make sense to me to serialize a class with no state.

If you really think it is an issue, please provide your motivation. You need to explain why you would attempt to serialize RoaringBitmapSupplier.

**Comment by chenyongyin** [comment]
> It does not make sense to me to serialize a class with no state.
> 
> If you really think it is an issue, please provide your motivation. You need to explain why you would attempt to serialize RoaringBitmapSupplier.

Because using the Dubbo RPC framework, if you return Roaring64NavigableMap, it will throw an exception: Serialized class org. Roaringbitmap. RoaringBitmapSupplier must implement Java IO. Serializable, Therefore, RoaringBitmapSupplier needs to implement Java.io.Serializable

**Comment by blacelle** [comment]
This suggests Dubbo RPC framework does not follow `Externalizable` directives, as Roaring64NavigableMap.writeExternal does not serialize RoaringBitmapSupplier field.

**Comment by richardstartin** [comment]
> This suggests Dubbo RPC framework does not follow `Externalizable` directives, as Roaring64NavigableMap.writeExternal does not serialize RoaringBitmapSupplier field.

Mark it as transient to avoid confusion

**Comment by richardstartin** [comment]
> > Mark it as transient to avoid confusion
> 
> Dubbo builds its own serialization/deserialization routines. It is configurable. E.g., you can register classes with standard approaches like Kryo. We do not know what the reporter (@chenyongyin) tried in terms of configuration. The default that Dubbo relies upon might be totally insane for passing binary objects like RoaringBitmaps. E.g., if you try to convert our data structures into a JSON tree, you would end up with something that would be a performance nightmare. Typically, such frameworks expect you to have fairly simple and small data structures... so it is not important that the payload be compact and especially efficient. Passing bitmaps is another story and not a common use case, it requires care. So while we can make changes to accommodate Dubbo, I would like to see benchmarks (data size, data serialization/deserialization performance) before we encourage it.

Marking non-serialized fields as transient creates better defaults for serialization frameworks and doesn’t have any performance impact. I don’t see a reason not to do it, even if it shouldn’t be necessary because the class implements Externalizable.

**Comment by kimmking** [comment]
Another way is using FastJson with custom-serializer(http://kimmking.cn/2017/06/06/json-best-practice/#9-7__u81EA_u5B9A_u4E49_u5E8F_u5217_u5316_u4E0E_u53CD_u5E8F_u5217_u5316).
