### ISSUE TITLE
RoaringBitmap.previousValue returning wrong value

### ISSUE THREAD

**Issue by igorcalabria** [RoaringBitmap/RoaringBitmap#564]
**Describe the bug**

`RoaringBitmap#previousValue` is returning wrong value or throws assertion error when running with `-ea` in some situations.

**To Reproduce**

```java
RoaringBitmap.bitmapOf(27399807).previousValue(403042); // This returns 27399807 or throws assertion error when application is run with -ea 
```

Not all values lower than the minimum value of the bitmap has this behaviour. For example, `RoaringBitmap.bitmapOf(27399807).previousValue(1000)` returns -1 which is correct. 

**RoaringBitmap version:**

0.9.28

**Java version:**

openjdk version "11.0.14"

**Comment by richardstartin** [comment]
@igorcalabria Thanks for the bug report, especially the steps to reproduce the issue - it is fixed by #565

**Comment by lemire** [comment]
Released.

**Comment by igorcalabria** [comment]
@richardstartin cheers! That was quick

**Comment by lemire** [comment]
Damn it. Re-releasing.
