### ISSUE TITLE
batchiterator hasNext returns true even if the last iterator is empty

### ISSUE THREAD

**Issue by ashishkf** [RoaringBitmap/RoaringBitmap#569]
https://github.com/RoaringBitmap/RoaringBitmap/blob/ecab803e00eae6ecb575b7e1c2df983aa30eb041/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java#L40

This happens if all bits in the last container are flipped. The nextBatch return '0' but hasNext keeps returning true causing infinite loop if you used the standard recommended batch iteration pattern:
while (hasNext()) {
     n = nextBatch();
    for (int i = 0; i < n; i++) {
   }
}

**Comment by richardstartin** [comment]
Containers in a `RoaringBitmap` should never be empty. Can you please provide here a test case which produces a bitmap with an empty container?

**Comment by lemire** [comment]
I removed the 'bug' label for now. Let us establish that it is a bug first.

Do we have a reproducible test case? Please provide a single-threaded function reproducing the issue.

**Comment by ashishkf** [comment]
Here we go:
this test fails on the last assert.  
@Test
  public void reproduceHasNextOnBatchIteratorBug() {
    ImmutableRoaringBitmap bm = ImmutableRoaringBitmap.bitmapOf(8511);

    BatchIterator bi = bm.getBatchIterator();

    int[] batch = new int[10];
    int target = 8511;

    Assert.assertTrue(bi.hasNext());

    int n = bi.nextBatch(batch);
    Assert.assertEquals(n, 1);
    Assert.assertEquals(batch[0], target);

    target++;

    Assert.assertTrue(bi.hasNext());

    n = bi.nextBatch(batch);
    Assert.assertEquals(n, 1);
  }

**Comment by ashishkf** [comment]
Seems like the issue is that hasNext is only checking if iterator is not null. It should also check if iterator.hasNext is true. The problem is if iterator.hasNext is false, it will have to then check if next container is non empty.

**Comment by ashishkf** [comment]
I found another issue. The advanceIfNeeded is supposed to keep advancing as long as the next value is less than the target. It actually does not. After calling advanceIfNeeded with target is greater than the bitmap.last(), hasNext returns true but nextBatch returns empty. So can't rely on advanceIfNeeded. The sample code documented in the advanceIfNeeded will go into infinite loop.
@Test
  public void reproduceHasNextOnBatchIteratorBug() {
    ImmutableRoaringBitmap bm = ImmutableRoaringBitmap.bitmapOf(8511);

    BatchIterator bi = bm.getBatchIterator();

    int[] batch = new int[10];
    int target = 8511;

    Assert.assertTrue(bi.hasNext());

    int n = bi.nextBatch(batch);
    Assert.assertEquals(n, 1);
    Assert.assertEquals(batch[0], target);

    target++;

    bi.advanceIfNeeded(target);
    Assert.assertTrue(bi.hasNext());

    n = bi.nextBatch(batch);
    Assert.assertEquals(n, 1);
  }

**Comment by richardstartin** [comment]
> 

This does not demonstrate an infinite loop. It does demonstrate slightly quirky behaviour: it's possible for the iterator to claim it has more data and then return an offset of zero, after which the iterator will return false for all calls of `hasNext()`. Modifying your test slightly demonstrates this:

```java
  @Test
  public void demonstrateQuirkyIteration() {
    ImmutableRoaringBitmap bm = ImmutableRoaringBitmap.bitmapOf(8511);
    BatchIterator bi = bm.getBatchIterator();
    int[] batch = new int[10];
    int target = 8511;
    assertTrue(bi.hasNext());
    int n = bi.nextBatch(batch);
    assertEquals(n, 1);
    assertEquals(batch[0], target);
    assertTrue(bi.hasNext());
    n = bi.nextBatch(batch);
    assertEquals(n, 0);
    assertFalse(bi.hasNext());
  }
```

**Comment by richardstartin** [comment]
> ```java
>   @Test
>   public void reproduceHasNextOnBatchIteratorBug() {
>     ImmutableRoaringBitmap bm = ImmutableRoaringBitmap.bitmapOf(8511);
> 
>     BatchIterator bi = bm.getBatchIterator();
> 
>     int[] batch = new int[10];
>     int target = 8511;
> 
>     Assert.assertTrue(bi.hasNext());
> 
>     int n = bi.nextBatch(batch);
>     Assert.assertEquals(n, 1);
>     Assert.assertEquals(batch[0], target);
> 
>     target++;
> 
>     bi.advanceIfNeeded(target);
>     Assert.assertTrue(bi.hasNext());
> 
>     n = bi.nextBatch(batch);
>     Assert.assertEquals(n, 1);
>   }
> ```

This test also does not demonstrate an infinite loop, modifying your test again slightly shows this is the same quirky termination (claim there is more data in `hasNext`, produce no data in `nextBatch`, terminate on the next call to `hasNext`).

**Comment by richardstartin** [comment]
This iterator has an unusual termination sequence which could be fixed by simplifying the code, but it does not trigger an infinite loop. Loops like

```java
var it = bitmap.getBatchIterator();
var buffer = new int[256];
while (it.hasNext()) {
    int limit = it.nextBatch(buffer);
    process(limit, buffer);
}
```

Never loop infinitely.

**Comment by ashishkf** [comment]
Yes, the above two issues can be handled by updating the documentation of advanceIfNeeded to use the modified terminating condition.
Found one more issue:
After advanceIfNeeded, the nextBatch skips over the some docs completely. I think the issue is that the advanceIfNeeded checks only if current (key  >> 16) is >= (target >> 16) and then does a binary search for the (char) target in the array container. Later when nextBatch is called it starts returning data from (key) + getData(index).

@Test
  public void testBatchIteratorWithAdvanceIfNeeded() {
    MutableRoaringBitmap blockIds = new MutableRoaringBitmap();
    blockIds.add(3 << 16);
    blockIds.add((3 << 16) + 5);
    blockIds.add((3 << 16) + 10);

    BatchIterator batchIterator = blockIds.getBatchIterator();
    batchIterator.advanceIfNeeded(6);
    Assert.assertTrue(batchIterator.hasNext());
    int[] batch = new int[10];
    int n = batchIterator.nextBatch(batch);
    Assert.assertTrue(n > 0);
    Assert.assertEquals(batch[0], 3<<16);
  }

**Comment by ashishkf** [comment]
BatchIntIterator::hasNext has this code:
```
if (!delegate.hasNext() || (mark = delegate.nextBatch(buffer)) == 0) {
      return false;
}

```
If the delegate.hasNext() returns true but delegate.nextBatch returns 0, then hasNext will return false. Thus, terminate the application's while(hasNext()) early.

**Comment by richardstartin** [comment]
> ```java
>  @Test
>   public void testBatchIteratorWithAdvanceIfNeeded() {
>     MutableRoaringBitmap blockIds = new MutableRoaringBitmap();
>     blockIds.add(3 << 16);
>     blockIds.add((3 << 16) + 5);
>     blockIds.add((3 << 16) + 10);
> 
>     BatchIterator batchIterator = blockIds.getBatchIterator();
>     batchIterator.advanceIfNeeded(6);
>     Assert.assertTrue(batchIterator.hasNext());
>     int[] batch = new int[10];
>     int n = batchIterator.nextBatch(batch);
>     Assert.assertTrue(n > 0);
>     Assert.assertEquals(batch[0], 3<<16);
>   }
> ```

This is a bug, I'll put a fix in shortly. Thanks for reporting this.

**Comment by richardstartin** [comment]
The comments here are addressed in #573 which:

1. simplifies iteration so there isn't an empty last batch
2. fixes the advanceIfNeeded bug reported here

The last comment about `BatchIntIterator` doesn't relate to a possible scenario as the iterator can't return 0 until there's no data left anyway.

**Comment by richardstartin** [comment]
This will be resolved in the next release

**Comment by ashishkf** [comment]
When is the next release? I would like to pick up this fix ASAP.

**Comment by lemire** [comment]
The release should become visible to you very soon.
