### ISSUE TITLE
Illegal character in path at index 10: file:///D:\repository\git\RoaringBitmap\bsi\build/repos/localDebug

### ISSUE THREAD

**Issue by panda0120** [RoaringBitmap/RoaringBitmap#571]
**Describe the bug**
when i execuse the command ./gradlew.bat assemble,then the process throw exception:
Illegal character in path at index 10: file:///D:\repository\git\RoaringBitmap\bsi\build/repos/localDebug

**To Reproduce**
use windows11, then use community edition of the idea to open the code.

**RoaringBitmap version:**
master 

**Java version:**

jdk1.8

**Comment by panda0120** [comment]
the temporary treatment is to modify this file:./build.gradle.kts.
at line 142:
`
//            repositories {
//                maven {
//                    name = "localDebug"
//                    url = URI.create("file:///${project.buildDir}/repos/localDebug")
//                }
//            }
`

**Comment by lemire** [comment]
@marshallpierce  Can you help us? It does seem that due to different separators, `URI.create("file:///${project.buildDir}/repos/localDebug")` might fail under Windows.

I do not understand this code. What is this localDebug and why is it there?

My instinct would be to do what @panda0120 suggests and just remove it entirely. But I'd prefer to understand it first.

**Comment by marshallpierce** [comment]
localDebug is a local-on-disk maven repo to allow you to easily inspect the artifacts you would be publishing to maven central, as in:

```
./gradlew publishSonatypePublicationToLocalDebugRepository -Pversion=foo
```

This is much easier to do than uploading to Sonatype's creaky system when interactively tinkering with build artifacts.

Anyway, I'll take a stab at assembling the URI in a different way that should be Windows-compatible.

**Comment by marshallpierce** [comment]
@panda0120 can you give #576 a try?
