### ISSUE TITLE
Method `forEachInRange` returns wrong numerical values(64Bit)

### ISSUE THREAD

**Issue by EayonChen** [RoaringBitmap/RoaringBitmap#577]
**Describe the bug**
hello，
i encountered some problems in the process of using `Roaring64Bitmap.forAllInRange` or `Roaring64Bitmap.forEachInRange`.

When i use `forAllInRange` to iterate over the bitmap,i get some wrong numerical values.
Sometimes numerical values can be generated out of nowhere, sometimes lost.

**To Reproduce**
I found three different types of errors and provided three examples of how to reproduce:

case 1 
When the starting point of the traversal exceeds MaxLongValue (the largest value in the bitmap), a new value is generated out of nowhere.
```
    val bitmap: Roaring64Bitmap = new Roaring64Bitmap
    bitmap.add(
       45011744312L
      ,45008074636L
      ,41842920068L
      ,41829418930L
      ,40860008694L
      ,40232297287L
      ,40182908832L
      ,40171852270L
      ,39933922233L
      ,39794107638L
    )
    val maxLong: Long = bitmap.getReverseLongIterator.peekNext() //45011744312L

    bitmap.forEachInRange(46000000000L,1000000000,
      new LongConsumer {
        override def accept(value: Long): Unit = {
          if(maxLong < value) {
            println(value) // 46000027192L
          }
        }
      })
```
case 2
 In a certain interval during the traversal process, a new value is generated out of nowhere
```
    val bitmap: Roaring64Bitmap = new Roaring64Bitmap
    bitmap.add(
       30385375409L
      ,30399869293L
      ,34362979339L
      ,35541844320L
      ,36637965094L
    )

    bitmap.forEachInRange(33000000000L, 1000000000,
      new LongConsumer {
        override def accept(value: Long): Unit = {
          println(value) // got 33000010093L
        }
      })
```
case 3
lost
```
    val bitmap: Roaring64Bitmap = new Roaring64Bitmap
    bitmap.add(
      14510802367L
      ,26338197481L
      ,32716744974L
      ,32725817880L
      ,35679129730L
    )

    bitmap.forEachInRange(32000000000L, 1000000000,
      new LongConsumer {
        override def accept(value: Long): Unit = {
          // 32716744974, 32725817880L
          println(value)  // only 32725817880L
        }
      })
```

**RoaringBitmap version:**

0.9.25

**Java version:**

Java version 1.8  (1.8.0_322)

Scala version 2.12.15

**Comment by lemire** [comment]
@larsk-db Would you please review this bug report ?

**Comment by larsk-db** [comment]
I'll try to take a look this weekend. I can't do it during work hours anymore, since we actually switched away from `Roaring64Bitmap` at work as overall the implementation is too brittle and still has lots of bugs.

**Comment by larsk-db** [comment]
Issues are confirmed; test cases are in #578. Thank you for the bug report @EayonChen.
Will look into what causes these issues now.

**Comment by EayonChen** [comment]
thanks all
