### ISSUE TITLE
Roaring64Bitmap Iterator error:Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6

### ISSUE THREAD

**Issue by frank0417** [RoaringBitmap/RoaringBitmap#580]
**Describe the bug**
19-digit 40,000 initializations, traversing the array out of bounds

Data such as ：
     3242766498713841665
     3492544636360507394
     3418218112527884289
     3220956490660966402
     3495344165583036418
     3495023214002368514
     3485108231289675778
 

       List<String> str= parseAccountIdsFromXlsx("xxxx.xlsx");
        Roaring64Bitmap rb=new Roaring64Bitmap();
        List<Long>accounts= Lists.newArrayList();
        str.stream().forEach(s->{
            if(StringUtils.isNumeric(s.trim())){
                try {
                    rb.add(Long.valueOf(s));
                }catch (NumberFormatException e){
                    System.out.println(s);
                }
            }
        });

        LongIterator it = rb.getLongIterator();
        long temp = 0L;
        while(it.hasNext()) {
            temp = it.next();
            count++;
        }

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at org.roaringbitmap.art.AbstractShuttle.moveToNextLeaf(AbstractShuttle.java:78)
	at org.roaringbitmap.art.LeafNodeIterator.hasNext(LeafNodeIterator.java:49)
	at org.roaringbitmap.longlong.Roaring64Bitmap$2.hasNext(Roaring64Bitmap.java:366)

**RoaringBitmap version:**

org.roaringbitmap:RoaringBitmap:0.9.8

**Java version:**
1.8

**Comment by lemire** [comment]
I fail to verify the issue:

https://github.com/RoaringBitmap/RoaringBitmap/pull/581

Please open a new issue with a reproducible test case. Consider issuing a pull request with your test case.

Here is the new test that I added :

```Java
  @Test
   public void testIssue580() {
     Roaring64Bitmap rb = Roaring64Bitmap.bitmapOf(3242766498713841665L, 3492544636360507394L,
       3418218112527884289L, 3220956490660966402L, 3495344165583036418L, 3495023214002368514L,
       3485108231289675778L);
     LongIterator it = rb.getLongIterator();
     int count = 0;
     while(it.hasNext()) {
         it.next();
         count++;
     }
     assertEquals(count, 7);
   }
```

**Comment by lemire** [comment]
Importantly, you reported a bug against an old version of the library. Please upgrade the dependency to the latest version of the library first.
