### ISSUE TITLE
negation of roaring bitmap

### ISSUE THREAD

**Issue by patelprateek** [RoaringBitmap/RoaringBitmap#585]
I have use cases where we may have to add millions of items to roaring bitmaps , one idea we were thinking is in few scenarios if we actually take negation of set and represent that using roaring bitmap , the data may be more compressed , especially when the sets are too dense . I am curious if the library provides any api generate a negated roaring bitmap , does it make sense to have this implemented.

**Comment by larsk-db** [comment]
Yes, in a sense this is possible: We've essentially been doing that on-the-fly in our code by using range materialisation (using `forAllInRange`). You can basically just interpret the callbacks in `RelativeRangeConsumer` inverted.
This gives you a particular range inverted materialised. The thing of course is that sets are (logically) infinite, so you always have to invert on a fixed range.

**Comment by lemire** [comment]
It is called flip:

https://github.com/RoaringBitmap/RoaringBitmap/blob/a307727d3a87fe89aa3d1a7328821b057717d4bf/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L1815
