### ISSUE TITLE
RoaringBitmap#intersects breaks for lower minumum values 

### ISSUE THREAD

**Issue by igorcalabria** [RoaringBitmap/RoaringBitmap#588]
**Describe the bug**
When the difference between the lowest value in the bitmap and the minimum passed to intersects function is higher than a threshold, it retruns wrong values. 

**To Reproduce**

```java
import org.roaringbitmap.RoaringBitmap;

public class App {
    public static void main(String[] args) {
        int valueInBitmap = 27470832;
        int baseValue = 27597418;
        int minValueThatWorks = 27459584;

        RoaringBitmap bitmap = RoaringBitmap.bitmapOf(valueInBitmap);

        System.out.println(bitmap.intersects(minValueThatWorks, baseValue)); // Returns true. Ok
        System.out.println(bitmap.intersects(minValueThatWorks-1, baseValue)); // Returns false. Not Ok
    }
}
```

I think one of the problems is around `container.intersects(offset, 1 << 16)`. If I understood things correctly, this test is not necessarily correct when the minimum key is on a different container than the one at pos. Maybe an early test could be added if there's an intersection on key level. In this case, minimum is in bucket 418, the value of the bitmap is in bucket 419 and supremum is in key 421. 

```java
  while (pos < length && supKey > (keys[pos])) {
      Container container = highLowContainer.getContainerAtIndex(pos);
      if (container.intersects(offset, 1 << 16)) {
        return true;
      }
      offset = 0;
      ++pos;
    }
```
https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L1197`

**RoaringBitmap version:**

0.9.33

**Java version:**

11

**Comment by lemire** [comment]
You are correct. This looks like a straight-forward bug.

**Comment by igorcalabria** [comment]
Just saw your PR, I think the same bug is also present for `ImmutableRoaringBitmap`  too 
https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java#L1239

**Comment by lemire** [comment]
@igorcalabria Correct. I am issuing a second release with the same fix extended.
