### ISSUE TITLE
Unexpected behavior with intersect()

### ISSUE THREAD

**Issue by mitochon** [RoaringBitmap/RoaringBitmap#607]
**Describe the bug**

Intersects doesn't behave as expected
https://github.com/RoaringBitmap/RoaringBitmap/blob/RoaringBitmap-0.9.0/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L633

**To Reproduce**
Run the following minimal reproducible code (Scala)
```
  val (start1, end1) = (71711701L, 71719778L)
  val (start2, end2) = (71396920L, 71815947L)
  val ror = new RoaringBitmap()
  ror.add(start1, end1)
  println("intersects? " + ror.intersects(start2, end2))
  // returns false (not expected)

  val ror2 = new RoaringBitmap()
  ror2.add(start1, end1)
  val ror3 = new RoaringBitmap()
  ror3.add(start2, end2)
  println("intersects? " + !RoaringBitmap.and(ror2, ror3).isEmpty())
  // returns true (as expected)
```

**RoaringBitmap version:**
0.9.0

Please report bugs after testing the latest version of the library. If you are using an older version of the library, please explain.
Using as part of Spark 3.1.3 dependency

Make sure to compare your version against the latest available version at https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap

**Java version:**
1.8

**Comment by richardstartin** [comment]
I think this was fixed recently. Can you try the latest release (0.9.36) please?

**Comment by mitochon** [comment]
Thanks for the quick response. That's right 0.9.36 doesn't exhibit this behavior
