### ISSUE TITLE
Roaring64Bitmap has too many container and leads to OOM when Roaring64Bitmap adds many sparse long numbers.

### ISSUE THREAD

**Issue by dingerchen** [RoaringBitmap/RoaringBitmap#616]
When I use Roaring64Bitmap  to  add java long number including negative long, the Roaring64Bitmap creates many ArrayContainer and LeafNode taking up much heap memory.For example, when Roaring64Bitmap longCardinality is 20000000, it's byte size is up to 549.2MB like the picture bellow.But 20000000 long numbers in array is 152.58MB with each long number is 8 bytes. I want to know why sparse long numbers in Roaring64Bitmap will occupy so much memory and create so many ArrayContainer and LeafNode. Is there any method to optimizing this case?

![image](https://user-images.githubusercontent.com/127710980/224611385-fefdadbf-52f7-48da-bb91-420b98d5b1bc.png)

![image](https://user-images.githubusercontent.com/127710980/224611316-68b13f0f-6104-45e7-996b-97646f9df448.png)

**Comment by lemire** [comment]
Before using a data structure (e.g., `Roaring64Bitmap`), you should ensure that it performs well for your use case.

If the reporter believes that there is a bug, they should provide a reproducible test case and some analysis.

If the reporter believes that the implementation could be optimized, they are encouraged to provide a pull request.
