### ISSUE TITLE
Debug visualizer for Visual Studio or lldb

### ISSUE THREAD

**Issue by sketchylizard** [RoaringBitmap/RoaringBitmap#618]
We recently started using Roaring64Map in our code to manage a (potentially) large visited set for graph traversal. We replaced an unordered_set<uint64_t> and our simplest traversals are twice as fast for large graphs. Thanks to all who worked on it.

Our developers occasionally set breakpoints to look at results from a traversal, and want to know if a given node (integer) is in the result. With unordered_set<uint64_t> Visual Studio's debugger would show you a list of the entries in the hash table, which was convenient. I have been asked to create a visualizer for Visual Studio. Since I primarily use Linux/clang myself, I am also interested in doing one for lldb.

Obviously, it would be great to just find a ready-made one, but I'm willing to do the work. I'm mostly looking for tips or advice on how I might accomplish this task.

**Comment by lemire** [comment]
> our simplest traversals are twice as fast for large graphs.

Great !!!

>  I'm mostly looking for tips or advice on how I might accomplish this task.

Are you sure you are commenting on the right project? RoaringBitmap is a *java* library. Maybe you meant CRoaring?
