### ISSUE TITLE
Roaring64Bitmap : Overflow error when calculating ANDNOT between two 64-bitmaps

### ISSUE THREAD

**Issue by casofiei-gcd** [RoaringBitmap/RoaringBitmap#619]
**Describe the bug**

Overflow error when calculating ANDNOT between two 64-bitmaps.

**To Reproduce**

```java
import org.roaringbitmap.longlong.Roaring64Bitmap;

public class RoaringBitmapTest
{
   private static final long[] CLEANER_VALUES = {140664568792144l};
   private static final long[] ADDRESS_SPACE_VALUES = {140662937752432l};

   public static void main(String[] args)
   {

      Roaring64Bitmap addressSpace = new Roaring64Bitmap();
      Roaring64Bitmap cleaner = new Roaring64Bitmap();
      int iteration = 0;

      while (true) 
      {
         System.out.println("Iteration: " + (++iteration));

         cleaner.add(CLEANER_VALUES);

         addressSpace.add(ADDRESS_SPACE_VALUES);
         addressSpace.add(CLEANER_VALUES);  // if this is missing, then it doesn't fail

         addressSpace.andNot(cleaner);
      }
   }
}
```

**Bug Symptoms**

On iteration 32, we get a crash with the following stack trace:

```stack
Exception in thread "main" java.lang.NegativeArraySizeException
        at org.roaringbitmap.art.Node4.remove(Node4.java:124)
        at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:144)
        at org.roaringbitmap.art.AbstractShuttle.remove(AbstractShuttle.java:115)
        at org.roaringbitmap.art.LeafNodeIterator.remove(LeafNodeIterator.java:104)
        at org.roaringbitmap.art.KeyIterator.remove(KeyIterator.java:34)
        at org.roaringbitmap.longlong.Roaring64Bitmap.andNot(Roaring64Bitmap.java:379)
        at RoaringBitmapTest.main(RoaringBitmapTest.java:26)
```

**Investigation findings**

The variable newLength in `org.roaringbitmap.art.Node4.remove()` line 123, is of type byte and on iteration 32 it overflows with a value of -128. On line 124, this length is used to define an array, resulting in the `NegativeArraySizeException`. This `newLength` value represents the length of the prefix of the node to be removed after it is shrunk to a leaf node. This calculated value should not change in each iteration, however it gets incremented until it overflows its type capacity.

**Possible hint for fix**

If you look at Art.insert, there is this code where it transforms a LEAF node into a Node4 node:

```java
    if (node.nodeType == NodeType.LEAF_NODE) {
      LeafNode leafNode = (LeafNode) node;
      byte[] prefix = leafNode.getKeyBytes();
      int commonPrefix = commonPrefixLength(prefix, depth, prefix.length, key, depth, key.length);
      Node4 node4 = new Node4(commonPrefix);
```

Look how the `Node4` instance has the prefix length set as the common prefix length between this node and the leaf node.

In `Node4.remove`, where it 'shrinks' this into a leaf node, it doesn't compute the common prefix length:

```java
    if (count == 1) {
      //shrink to leaf node
      Node child = children[0];
      byte newLength = (byte) (child.prefixLength + this.prefixLength + 1);
      byte[] newPrefix = new byte[newLength];
      System.arraycopy(this.prefix, 0, newPrefix, 0, this.prefixLength);
      newPrefix[this.prefixLength] = IntegerUtil.firstByte(key);
      System.arraycopy(child.prefix, 0, newPrefix, this.prefixLength + 1, child.prefixLength);
```

What might be missing here is the common prefix length calculation

Please advice on what steps need to be taken to make this fix.
Thank you for this nice library.

**RoaringBitmap version:**

First detected at 0.9.27, issue persists still at current latest version 0.9.39

**Java version:**

openjdk version "1.8.0_362"

**Comment by casofiei-gcd** [comment]
Not at this time.  We're not sure what the correct solution would be.

On first iteration, when `addressSpace.add(CLEANER_VALUES)` is called, there is a root leaf node with a prefix of length zero, and a new Node4 root is created with 2 leaf children (for the existing N1 node and the new value N2), this root having a prefix length of 3.  When the `andNot` is performed, the root becomes back the leaf node N1, but at this time this root leaf node gets a computed prefix length of 4.

On second iteration when `addressSpace.add(CLEANER_VALUES)`, there is again the root leaf node N1 (with prefix length of 4), a new Node4 root gets created, where the existing N1 node gets added as a child, and the other child is for the new value.  When `andNot` is performed, the leaf node N1 (with prefix length of 4) becomes again a root leaf node, but this time with a prefix length of 8.  And so on.

The assumption is that something is wrong at `Node4.remove(int pos)`, when shrinking to a leaf node.  On a second thought, why would a leaf node need a prefix?

**Comment by lemire** [comment]
@weijietong Can you have a look?

**Comment by weijietong** [comment]
I am busy these two weeks, will take a look at it after this period as soon as possible.

**Comment by weijietong** [comment]
This was fixed at the [PR](https://github.com/RoaringBitmap/RoaringBitmap/pull/620).

**Comment by lemire** [comment]
@weijietong Great stuff. I have issued a release.
