### ISSUE TITLE
Can't check value 65535 using `contains(long minimum, long supremum)`

### ISSUE THREAD

**Issue by coderzc** [RoaringBitmap/RoaringBitmap#623]
**Describe the bug**

Can't check value 65535 using `contains(long minimum, long supremum)`.

I'm not sure if my usage is wrong, please correct me if I'm using it wrong, thanks~

**To Reproduce**
```java
RoaringBitmap roaringBitmap = new RoaringBitmap();
for (long i = 1L; i <= 100000L; i++) {
    roaringBitmap.add(i, i + 1);
}

System.out.println(roaringBitmap.contains(65535L, 65535L + 1));
```
This test output is `false`, expected to output `true`.

**RoaringBitmap version:**

0.9.15

Make sure to compare your version against the latest available version at https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap

**Java version:**

OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)

**Comment by yoursmanjunad** [comment]
I think we get false because here, 65536L is inclusive, and 65536L + 1 becomes exclusive. To make this run, I think we should use roaringBitmap.contains(65535L, 65536L) instead of roaringBitmap.contains(65535L, 65535L + 1)

**Comment by coderzc** [comment]
> ```java
> RoaringBitmap roaringBitmap = new RoaringBitmap();
> for (long i = 1L; i <= 100000L; i++) {
>     roaringBitmap.add(i, i + 1);
> }
> 
> System.out.println(roaringBitmap.contains(65535L, 65535L + 1));
> ```

I tried using `roaringBitmap.contains(65535L, 65536L)`, but it still returns false.

**Comment by yoursmanjunad** [comment]
i think this should work, RoaringBitmap roaringBitmap = new RoaringBitmap();
for (long i = 1; i <= 65536; i++) {
    roaringBitmap.add(i, i + 1);
}
System.out.println(roaringBitmap);

long start = 65535L;
long end = start + 1L;
System.out.println(roaringBitmap.contains(start, end));

**Comment by coderzc** [comment]
> ```java
> RoaringBitmap roaringBitmap = new RoaringBitmap();
> ```

<img width="799" alt="image" src="https://user-images.githubusercontent.com/26179648/234165408-95043401-7941-4c10-b59d-fe5398e358c7.png">

I tried this test but it still can't check value 65535

**Comment by yoursmanjunad** [comment]
hey, what is the file name of it? I would like to work on that on my machine.

**Comment by coderzc** [comment]
> hey, what is the file name of it? I would like to work on that on my machine.

https://github.com/apache/pulsar/blob/c4aec6661e795c46181dc1fa79282065fa875768/pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java

**Comment by coderzc** [comment]
I also found some other values can't be cheked
```
    @Test
    public void testContains() {
        RoaringBitmap roaringBitmap = new RoaringBitmap();
        for (long i = 1; i <= 100_000; i++) {
            roaringBitmap.add(i, i + 1);
        }

        for (long i = 1; i <= 100_000; i++) {
            if (!roaringBitmap.contains(i, i + 1)) {
                System.out.println("don't contain:" + i);
            }
        }

        RoaringBitmap roaringBitmap2 = new RoaringBitmap();
        for (long i = 1; i <= 1000_000; i++) {
            roaringBitmap2.add(i, i + 1);
        }

        for (long i = 1; i <= 1000_000; i++) {
            if (!roaringBitmap2.contains(i, i + 1)) {
                System.out.println("don't contain:" + i);
            }
        }

        RoaringBitmap roaringBitmap3 = new RoaringBitmap();
        for (long i = 1; i <= 10_000_000; i++) {
            roaringBitmap3.add(i, i + 1);
        }

        for (long i = 1; i <= 10_000_000; i++) {
            if (!roaringBitmap3.contains(i, i + 1)) {
                System.out.println("don't contain:" + i);
            }
        }
    }
```

Output:
```
don't contain:65535
don't contain:983039
don't contain:9961471
```

**Comment by lemire** [comment]
Wow. This does look like a bug.

I will check tomorrow.

**Comment by lemire** [comment]
It is indeed a bug. A new release should follow shortly.
