### ISSUE TITLE
Unserialising empty ImmutableRoaringBitmaps results in a RuntimeException

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/RoaringBitmap#64]
After adapting the [example code](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java#L31) for loading a `ImmutableRoaringBitmap` from a `ByteBuffer` to load two consecutive empty bitmaps results in the following exception:

```
Exception in thread "main" java.lang.RuntimeException: I failed to find one of the right cookies. 0
	at org.roaringbitmap.buffer.ImmutableRoaringArray.<init>(ImmutableRoaringArray.java:102)
	at org.roaringbitmap.buffer.ImmutableRoaringBitmap.<init>(ImmutableRoaringBitmap.java:406)
…
```

Code (in Scala):
```scala
object EmptyBitmapLoadingBug extends App {
  val rr1 = MutableRoaringBitmap.bitmapOf()
  val rr2 = MutableRoaringBitmap.bitmapOf()
  val bos = new ByteArrayOutputStream()
  val dos = new DataOutputStream(bos)
  rr1.serialize(dos)
  rr2.serialize(dos)
  dos.close()
  val bb = ByteBuffer.wrap(bos.toByteArray)
  val rrback1 = new ImmutableRoaringBitmap(bb)
  bb.position(bb.position() + rrback1.serializedSizeInBytes())
  val rrback2 = new ImmutableRoaringBitmap(bb)
}
```

The exception is thrown on loading the second bitmap.

I'm using RoaringBitmaps 0.5.9 on Java 1.8.0_65.

**Comment by lemire** [comment]
Verified.

**Comment by lemire** [comment]
Thanks for the bug report. Fixed in release 0.5.17. Please upgrade and verify.

**Comment by maciej** [comment]
Verified as fixed. Thank you, @lemire!

**Comment by lemire** [comment]
@maciej  Please keep the bug reports coming! ;-)

**Comment by maciej** [comment]
:+1: whenever I find any – I definitely will! However due to the quality of the project – I doubt there will be many coming. :-)
