### ISSUE TITLE
Inconsistent Results between `RoaringBitmap.andNotCardinality(s1, s2)` and `RoaringBitmap.andNot(s1, s2).getCardinality()`

### ISSUE THREAD

**Issue by shencangsheng** [RoaringBitmap/RoaringBitmap#644]
**Describe the bug**

I have noticed an issue where there are inconsistent results when using `RoaringBitmap.andNotCardinality(s1, s2)` and `RoaringBitmap.andNot(s1, s2).getCardinality()`.

**result**

![show](https://github.com/RoaringBitmap/RoaringBitmap/assets/67856731/92962a59-0627-42db-b980-333851f6437a)

**RoaringBitmap version:**

```xml
<dependency>
                <groupId>org.roaringbitmap</groupId>
                <artifactId>RoaringBitmap</artifactId>
                <version>0.9.45</version>
 </dependency>
```

**Java version:**

Open JDK 11

**Comment by lemire** [comment]
We need a reproducible test case. The current report is incomplete and cannot be investigated.

I am going to close this. Please open a new bug report with an example of the issue you have outlined. The example should be reproducible.

**Comment by lemire** [comment]
Please be aware that it is most likely that the bug is in your own code. You need to do enough investigation to provide strong evidence that the bug is in our library.

If you have done this work, then you should be able to provide us with enough information so that we can reproduce the issue.

We are not magicians: if we cannot verify that there is an issue, then we have no hope of fixing it.

**Comment by shencangsheng** [comment]
@lemire  
Okay, I'll give you the duplicate code

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import org.roaringbitmap.RoaringBitmap;

import java.io.File;
import java.io.IOException;

/**
 * <br>
 * 〈〉
 *
 * @author shencangsheng
 * @create 2023/7/24
 */
public class Main {
    public static void main(String[] args) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        RoaringBitmap s1 = RoaringBitmap.bitmapOf(objectMapper.readValue(new File("/tmp/s1.json"), int[].class));
        RoaringBitmap s2 = RoaringBitmap.bitmapOf(objectMapper.readValue(new File("/tmp/s2.json"), int[].class));
        System.out.println(RoaringBitmap.andNotCardinality(s1, s2));
        System.out.println(RoaringBitmap.andNot(s1, s2).getCardinality());
    }
}
```

This is the output

![image](https://github.com/RoaringBitmap/RoaringBitmap/assets/67856731/5c88b556-1159-486e-9434-8172dddcb242)

This is the input file

[input.zip](https://github.com/RoaringBitmap/RoaringBitmap/files/12141399/input.zip)
