### ISSUE TITLE
How to and  List<? extends RoaringBitmap>  efficiently

### ISSUE THREAD

**Issue by GeekHM** [RoaringBitmap/RoaringBitmap#649]
I want to perform and calculation on Iterator<? extends RoaringBitmap> bitmaps。
I found this method  public static RoaringBitmap and(final Iterator<? extends RoaringBitmap> bitmaps, final long rangeStart, final long rangeEnd)
But I don't know how to set rangeStart and rangeEnd efficiently
Can you give me some advice about this function or others method。Thank you very much！
<img width="769" alt="image" src="https://github.com/RoaringBitmap/RoaringBitmap/assets/34578736/090846d9-1034-4e07-a4cd-40fe52a9fb96">

**Comment by GeekHM** [comment]
ok,thakns!
<img width="555" alt="image" src="https://github.com/RoaringBitmap/RoaringBitmap/assets/34578736/14e5a261-fbb4-4c16-b8d8-9a9f28895531">

**Comment by lemire** [comment]
Yes, the function you have described works too. We offer multiple ways to solve these problems.
