### ISSUE TITLE
Question about Roaring64Bitmap mapping and streaming

### ISSUE THREAD

**Issue by ate47** [RoaringBitmap/RoaringBitmap#655]
Hello,

I didn't find a discussions tab or a question issue template so I'm asking that here, if it should be somewhere else I'm sorry, can I have a link to this somewhere else?

We are using the Roaring64Bitmap implementation for our binary structure and I was wondering:

1. Is it possible to map the bitmap instead of using a memory version?
2. Is it possible to generate a roaring bitmap using a (sorted?) stream of bits without having the bitmap loaded in memory? (Same with a mapped version or similar)

Thanks, 
Antoine Willerval

**Comment by lemire** [comment]
> Is it possible to map the bitmap instead of using a memory version?

For 64-bit variants, I do not think this functionality exists at this time. Pull request invited !

> Is it possible to generate a roaring bitmap using a (sorted?) stream of bits without having the bitmap loaded in memory? 

We have fast functions to load data (some contributed by @richardstartin), but they load the data in memory, always. You can later serialize the result and load it as an `ImmutableRoaringBitmap` instance which can be memory-mapped. 

If you need external-memory mutation, you will need to write the code.
