### ISSUE TITLE
An overflow when infinitely iterating over run containers, ArrayIndexOutOfBoundException is thrown then

### ISSUE THREAD

**Issue by xtonik** [RoaringBitmap/RoaringBitmap#673]
**Describe the bug**
[An overflow](https://github.com/RoaringBitmap/RoaringBitmap/blob/3aa3212fea10e3a1a2dcfd80368e6eb5a7031f66/RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java#L2819) on variable `pos` occurs when infinitely iterating over run containers and `ArrayIndexOutOfBoundException` is thrown. It is very unusual case, but possible. Belonging stack trace:

_OverflowOnInfiniteIterationTest > overflowReverseOnNext() FAILED
    java.lang.ArrayIndexOutOfBoundsException: -1
        at org.roaringbitmap.RunContainer.getLength(RunContainer.java:1024)
        at org.roaringbitmap.ReverseRunContainerCharIterator.next(RunContainer.java:2938)
        at org.roaringbitmap.OverflowOnInfiniteIterationTest.overflowReverseOnNext(OverflowOnInfiniteIterationTest.java:72)_

**To Reproduce**
Checkout [related commit](https://github.com/RoaringBitmap/RoaringBitmap/commit/4c3df18c38919a3200804e04b5246eb227b684a4) and run the test. This is example only, there are surely other places where this occurs.

Note that when debug is on the execution takes much longer time.

**Comment by lemire** [comment]
Containers are not part of our public API. If there is a bug, please reproduce it using a RoaringBitmap instance.

**Comment by xtonik** [comment]
Ok, the responsibility of this behavior lies on user, who called that. I can't still simulate the same from public API, but I didn't not give up. 
When digging deeper in the issue I have found out [another suspicious  behavior](https://github.com/RoaringBitmap/RoaringBitmap/commit/0110ff586b9f10f10ea9c2bd0bc7fba565f4db6d). If it is ok, then it should be documented in API, that calling `next()` without preceding check call to `hasNext()` can lead to unpredictable behavior.

**Comment by lemire** [comment]
> If it is ok, then it should be documented in API, that calling next() without preceding check call to hasNext() can lead to unpredictable behavior.

Yes. That would make a good PR.
