### ISSUE TITLE
Roaring bitmaps for matrix operations

### ISSUE THREAD

**Issue by cogmission** [RoaringBitmap/RoaringBitmap#72]
Hi, I apologize if this isn't the right venue for asking this question?

But I was wondering if it wouldn't be ridiculous to implement a SparseMatrix using a collection of RoaringBitmaps as its rows?

What do you think?

Cheers,
David

**Comment by lemire** [comment]
A bitmap/bitset can be thought of as a set of integers. The rows of a matrix are more like arrays. So there is no obvious match in my mind. Care to elaorate?

**Comment by cogmission** [comment]
Hi Daniel, thank you for responding so quickly, I'm a big fan of your work!

The idea would be to have a Matrix with bits instead of integers (in my case). Each row would be a Roaring Bitmap which would save on memory? For my project, I'm using int[]s as the payload that gets passed around, and the integers are only either 1 or 0; the arrays in the usual case are 2048 bits wide with 2% sparsity (typically == 40 on bits).

I'm thinking about a way to minimize memory consumption without losing performance. Using 32 bits to represent a zero or one, you can see, is kind of a waste - however I did read somewhere that the JVM is more efficient using integers (having something to do with register sizes or something?) [Here](http://stackoverflow.com/questions/8804435/alternative-to-java-bitset-with-array-like-performance) is one place where I saw some discussion of this, though I can't find the original source.

**Comment by lemire** [comment]
Oh! Yes, if it is a matrix of bits, then yes, it could work.

If you are using ``int[]`` to store 0s and 1s, you could reduce your memory usage by nearly a factor of 4 by using ``boolean[]`` arrays instead as a ``boolean`` in an array use as little as 1 byte in Java. 

It is entirely possible that you might do even better with Roaring bitmaps. In the abstract, it is a bit difficult to tell. Have tried it?

**Comment by cogmission** [comment]
Not yet tried it... Right now I'm in the middle of looking for adequate Linear Algebra libraries, though what I have to do is not too complex (some dot products, right vector sums) - but then I have to have a SVD implementation - [my project](https://github.com/numenta/htm.java) is reverse engineering the human neo cortex and we model columns of cells in a matrix as one of the data structures (neural nets with real neurons).

Anyway, I need to get an idea of how it might be to manipulate the bits of a Roaring Bitmap, either by extracting out to a 2D integer array doing my computations; and then putting it back in, or manipulating the bitmaps via a wrapper - in place? Just thinking about what would be most efficient...

**Comment by lemire** [comment]
@cogmission 

Oh. No, you don't want to extract stuff. You'd want to operate directly on the compressed data. 

You could start cataloguing the operations you need to have supported.

Possibly, one might need to design a custom data structure, maybe inspired by Roaring bitmaps. Maybe ``Roaring bit matrices`` or something. I could help, possibly.

**Comment by cogmission** [comment]
@lemire Really? Your help would be unbelievably serendipitous! :-)

But yes, I think it could work! I will start to write down the operations as you suggest, I believe they won't be that many in number... But a Roaring Matrix (maybe RoaringBinaryMatrix) would be pretty cool! The community might enjoy its existence too! 

Do you have any intuition (I know we're speaking with no details), as to whether its performance would be compromised at all as opposed to using int[]s? (outside of the fact that it would save 4x memory)?

**Comment by lemire** [comment]
@cogmission  

We are possibly talking about a lot more than 4x memory savings. But memory is a secondary issue... it is often possible to just throw more RAM at the machine... this is easy with distributed systems. So RAM is rarely a hard limit. The problem I see in practice are systems that get so bogged down moving bits around that they have less and less time for actual computations.

So without knowing anything about your application, what I'd hope is that you would be able to significantly improve the performance, irrespective of the memory usage.

**Comment by cogmission** [comment]
Basically I do dot products, unions, outer vector sums, and mostly flipping bits from 1 to 0 - and a lot of 2048 bit int[] compositions as return values from various methods... So I would experience a lot of RBM creation (I would have to overhaul the code to transition from int[]s to RRbitmaps)... How are they for construction?

**Comment by cogmission** [comment]
I'll create a branch and give it a try - implement one of the algorithms using RRBMs (not implement the Matrix just yet) and then get a jmh comparison going...

**Comment by lemire** [comment]
A dot product between two bit arrays is just the cardinality of the intersection: 

http://static.javadoc.io/org.roaringbitmap/RoaringBitmap/0.5.18/org/roaringbitmap/RoaringBitmap.html#andCardinality-org.roaringbitmap.RoaringBitmap-org.roaringbitmap.RoaringBitmap-

We have unions, of course. We have bit flipping. To avoid creating new objects, we can often using in-place computations.

Best thing is to try it out at a prototype level and see where the problems are.

**Comment by cogmission** [comment]
@lemire Thank you so much! (and thank you for the encouragement & link) I will do some leg work and see how things look... I'll circle back around and see if you have the time to get involved on the Matrix Impl if/when things look promising? 

I created this issue here if you'd like to track its progress and continue discussing this possibility...https://github.com/numenta/htm.java/issues/382  

Thanks again!

**Comment by lemire** [comment]
I subscribed to the issue.

**Comment by cogmission** [comment]
@lemire Awesome. Please stay in touch when you find time and I'll leave comments as to the status... 
Thanks again! :-)

Feel free to delete this if you don't want it hanging around, I made a note of your helpful comments already... :+1:

**Comment by lemire** [comment]
It is fine to let this issue open for now as it may interest others.

**Comment by richardstartin** [comment]
@cogmission did this go anywhere?

**Comment by ChoeYoonSeop** [comment]
Hi
I'm using a RoaringBitmap to represent 50+ million users as a dimension like this (one bit = 1 user) :

| dimension | user |
|---|---|
|country=KR| 01001001|
|gender=male|11010011|

and using it like this :
```
How many are KR & male unique users? = 01001001 & 10110011 = 01000001 = 2 users.
```

Now, I'd like to express relationships between 50+ million "user"s and 40+ million "user group"s (such as chat room) as a bit-matrix.

| group ➡️ | 1 | 2 | 3 | 4 | 5 | 6 ... |
|---|---|---|---|---|---|---|
| user 1 | 1 | 0 | 1 | 1 | 0 | 0 |
| user 2 | 0 | 1 | 0 | 1 | 1 | 0 |
| user 3 | 1 | 0 | 1 | 1 | 0 | 0 |
| user 4 | 0 | 1 | 0 | 0 | 1 | 1 |
| user 5 | 0 | 1 | 0 | 1 | 1 | 0 |
| user 6 | 1 | 1 | 0 | 1 | 1 | 1 |
| user 7 | 1 | 0 | 0 | 0 | 0 | 1 |
| user 8 | 0 | 1 | 0 | 1 | 1 | 0 |
| ... |

(Actually it's very sparse because each group has 5-10 members only(avg.))

After filtering users by some conditions, I have a user bitset(user 1, 3, 5 = 10101000). Now, I want to get a "user group" bitset which contains a user which I filtered. (group 1, 2, 3, 4, 5 = 111110)

Without compressing, we need 227TB memory to represent relationships.

```
50000000 bit * 40000000 bit / 8 (to byte) / 1024 ( to KB) / 1024 ( to MB) / 1024 (GB) / 1024 (TB) = 227TB
```

*Could it be compressed in RoaringBitmap way?* It would be very cool.

Interface like this would be good..

``` 
RoaringBitmap groups = bitMatrix.someManipulation(userRoaringBitmap) 
```

Then we can answer this

```
How many unique groups which contains a KR & male user? = 
```

Sorry for my bad english
I'm not sure it's right place to talk

Thanks

**Comment by lemire** [comment]
@ChoeYoonSeop 

Your English is probably just fine.

Why can't you represent each column of your bit-matrix as a bitmap?


Can you represent your idea using Java code?

**Comment by rolandblain** [comment]
Hi. I'm ChoeYoonSeop(company changed so email invalidated..) and I implemented my requires in kotlin code here:
https://github.com/rolandblain/relationmatrix
Thank you and your library and I hope you always stay healthy and happy.

**Comment by lemire** [comment]
I am going to close the issue and refer interested users to https://github.com/rolandblain/relationmatrix
