### ISSUE TITLE
BitmapBatchIterator.hasNext() - incorrect result

### ISSUE THREAD

**Issue by shikharid** [RoaringBitmap/RoaringBitmap#730]
**Describe the bug**
BitmapBatchIterator.hasNext() is implemented as:

```java
  public boolean hasNext() {
    return wordIndex < 1024;
  }
```
This will produce incorrect results (return true for hasNext) when their is actually nothing at that index (`bitmap.bitmap[wordIndex] == 0` for all remaining indexes).
 
From the looks of it, it might have been done this way for some well-intentioned performance reasons. 

Can be argued though that performance impact of those extra checks amortized over the entire iteration will be same as before. 
And the work that the user does when **hasNext()** returns **true** might be more expensive and even cause unintentional bugs (expected non-empty). 

Proposed fix:

```java
  @Override
  public boolean hasNext() {
    if (wordIndex == 1024) {
      return false;
    }
    while (word == 0) {
      if (wordIndex == 1024) { // reached end without a non-empty word
        return false;
      }
      word = bitmap.bitmap[++wordIndex];
    }
    return word != 0; // found some non-empty word, so hasNext
  }
```

Happy to contribute the fix !  

**To Reproduce**
Obvious to recognise the bug from code, let me know though if reproduce code is necessary

**RoaringBitmap version:** 1.0.0

**Java version:** 21

**Comment by lemire** [comment]
Thanks. Let us document the behavior.

https://github.com/RoaringBitmap/RoaringBitmap/pull/731

**Comment by shikharid** [comment]
Why not fix behaviour though? Since the behaviour is accurate in all other container iterators and fixing here is trivial. 
And the perf overhead seems tolerable (consider this is a batched iterator)

**Comment by shikharid** [comment]
Added PR https://github.com/RoaringBitmap/RoaringBitmap/pull/732
@lemire
