### ISSUE TITLE
RoaringBitmap 1.2.0 version is missing from Maven central

### ISSUE THREAD

**Issue by lhotari** [RoaringBitmap/RoaringBitmap#735]
**Describe the bug**

1.2.0 version has been released according [to GitHub releases](https://github.com/RoaringBitmap/RoaringBitmap/releases).
The artifacts are missing from Maven Central, https://repo1.maven.org/maven2/org/roaringbitmap/RoaringBitmap/ .

**To Reproduce**

https://repo1.maven.org/maven2/org/roaringbitmap/RoaringBitmap/1.2.0/ returns 404

**Comment by lemire** [comment]
We push our releases to maven central. It can take hours, days or weeks for the releases to appear, and they are sometimes dropped. It is an antiquated system. Please be patient or report the issue to Sonatype, the vendor responsible for Maven central. There is nothing we can do as we only provide the software packages.

**Comment by lemire** [comment]
This is a recurring problem, see https://github.com/search?q=repo%3ARoaringBitmap%2FRoaringBitmap+%22Maven+central%22&type=issues

**Comment by lemire** [comment]
To clarify the process, the GitHub release is something that we do manually, after having pushed the artefacts.

**Comment by lemire** [comment]
@lhotari Note that I do so 1.2.0 right now. Are you sure it is missing?

**Comment by lemire** [comment]
https://repo1.maven.org/maven2/org/roaringbitmap/RoaringBitmap/1.2.0/

**Comment by lhotari** [comment]
Thank you @lemire for addressing the issue.
