### ISSUE TITLE
Should the next major release of RoaringBitmap drop support for Java 6? What about dropping support for Java 7?

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#74]
Current RoaringBitmap code works on Java 6. 

We have been discussing phasing out support for Java 6. Some of the arguments are provided in a recent PR: 

https://github.com/RoaringBitmap/RoaringBitmap/pull/70#issuecomment-179473901

There is also some discussion about jumping directly to Java 8, for better parallelisation and a nicer API.

Note that this would be as part of a new major release. We would continue getting bug fixes into 0.5.

**Comment by lemire** [comment]
c.c. @owenkaser @gssiyankai @omirandette @gpunti @samytto @JervenBolleman @navis  @drcrallen @xvrl ....

**Comment by pwebbitrs** [comment]
We are heavily reliant on Roaring and we jumped straight to J8 a while back,  so i'd vote to drop  J6 and go straight to J8.   Any benefits gained through better parallelisation, api, performance and/or other improvements would be well received from our perspective.

**Comment by lemire** [comment]
Thanks @pwebbitrs

**Comment by gpunti** [comment]
I have no strong opinion on that but I think that many large projects are still using J7. I rather update step by step.

**Comment by JervenBolleman** [comment]
JDK7 is EOL software for most people since a year (Oracle JDK 7 was EOL in
April 2015)
People still using java7 as a deployment platform are unlikely to use
cutting edge RoaringBitmap releases.
RoaringBitMap would benefit a lot from java8 functionality.
Which is why I would vote for jumping to java8 directly.

On Thu, Feb 4, 2016 at 9:42 AM, Galderic Puntí <notifications@github.com>
wrote:

> I have no strong opinion on that but I think that many large projects are
> still using J7. I rather update step by step.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoaringBitmap/RoaringBitmap/issues/74#issuecomment-179711406>
> .
>



-- 
Jerven Bolleman
me@jerven.eu

**Comment by gpunti** [comment]
We use RoaringBitmaps in a hadoop envirorment, which doesn't yet support jdk8 ( https://wiki.apache.org/hadoop/HadoopJavaVersions). So we couldn't use the usual repositories and we'd have to compile it ourselves.

Another option is to build two artifacts, one in jdk8 and another with jdk7.

**Comment by lemire** [comment]
Of course, there is no talk of dropping support for Java 6 for the 0.5 release, so people who can't upgrade beyond Java 6 should not be overly concerned.

> https://wiki.apache.org/hadoop/HadoopJavaVersions

Cloudera does not yet support Java 8 

http://cloudera.com/documentation/other/Matrix/topics/pcm_jdk_cdh_cm.html

It looks like Google does not support Java 8 yet

https://cloud.google.com/appengine/docs/java/gettingstarted/setup


> Another option is to build two artifacts, one in jdk8 and another with jdk7.

That would be ideal, but I do not know how to do this elegantly. 

Maven has the notion of a classifier

http://stackoverflow.com/questions/10920142/how-to-configure-maven-to-build-two-versions-of-an-artifact-each-one-for-a-diff

and we can use patches...

http://stackoverflow.com/questions/24859393/dynamically-maven-patching-of-java7-libraries

Thoughts!

**Comment by gssiyankai** [comment]
>  > Another option is to build two artifacts, one in jdk8 and another with jdk7.

>That would be ideal, but I do not know how to do this elegantly. 

If we were to provide 2 artifacts, one for the Java 7 ecosystem and the other for the Java 8 one, I think it would be simpler just to have 2 separate branches. But, this would mean that we would have to maintain 3 different codelines overall !!! Maybe too much for us at the moment...

Given that Cloudera and Google don't support java 8 yet, I would go for the java 7 upgrade.

**Comment by lemire** [comment]
I'll push a new version (0.6) aiming at JDK 7. We can move to JDK 8 when major cloud vendors have started supporting it.

I really do wish we could move to JDK 8, but we can't very well tell people who use cloud infrastructures like Cloudera and Google that they are unreasonably behind the times.

It is possible, however, for us to develop JDK 8 in a branch or fork. People who need such features could then build their own RoaringBitmap.
