### ISSUE TITLE
NullPointerException on serialization

### ISSUE THREAD

**Issue by jhsenjaliya** [RoaringBitmap/RoaringBitmap#741]
**Describe the bug**
occasional NPE on serializing the bitmap.

```java.lang.NullPointerException: Cannot invoke "org.roaringbitmap.Container.getCardinality()" because "this.values[k]" is null
	at org.roaringbitmap.RoaringArray.serialize(RoaringArray.java:875)
	at org.roaringbitmap.RoaringArray.writeExternal(RoaringArray.java:965)
	at org.roaringbitmap.RoaringBitmap.writeExternal(RoaringBitmap.java:3178)
	at java.base/java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1465)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1436)
```

**To Reproduce**
its really hard to reproduce, because this only happens occassional and also does not happens for the same dataset on local. but I will try to reproduce this with some special setup and will update the ticket. 

**RoaringBitmap version:**
1.2.1 & 0.9.45

**Java version:**
17

**Comment by lemire** [comment]
@jhsenjaliya I am going to close this. We need a reproducible test case. Note that this library has been in production for many years. Note that the most likely explanation is that you are using multithreading. 


> occasional NPE

The word 'occasional' strongly suggests that you have unsafe multithreading.

**Comment by jhsenjaliya** [comment]
Sure, will reopen if i can reproduce this, still trying to figure out a way to reproduce this. but here is the snapshot of my debugging for reference for future.
somehow the value array is getting null entry in the array, and thats causing the NPE.
