### ISSUE TITLE
Roaring64BitmapSliceIndex result is inconsistent with itself(first serialize then deserialize)

### ISSUE THREAD

**Issue by linlin994395** [RoaringBitmap/RoaringBitmap#743]
**Describe the bug**
First Roaring64BitmapSliceIndex getValue result is inconsistent with Second Roaring64BitmapSliceIndex getValue result which is generated by the First Roaring64BitmapSliceIndex serialize and then deserialize back

**To Reproduce**
If it is a bug you encountered while working with the library, you should produce a code sample that allows us to reproduce the problem. Your code should be complete and immediately executable:

For example, this is a good example:
```Java
import org.roaringbitmap.bsi.longlong.Roaring64BitmapSliceIndex;

import java.io.IOException;
import java.nio.ByteBuffer;

public class BSI64ToyBug {
    public static void main(String[] args) throws IOException {
        Roaring64BitmapSliceIndex bsi = new Roaring64BitmapSliceIndex();
        bsi.setValue(100L, 3L);
        bsi.setValue(1L, 392L);
        System.out.println(bsi.getValue(100L));
        System.out.println(bsi.getValue(1L));

        ByteBuffer buffer = ByteBuffer.allocate(bsi.serializedSizeInBytes());
        bsi.serialize(buffer);

        Roaring64BitmapSliceIndex de_bsi = new Roaring64BitmapSliceIndex();
        de_bsi.deserialize(ByteBuffer.wrap(buffer.array()));
        System.out.println(de_bsi.getValue(100L));
        System.out.println(de_bsi.getValue(1L));
    }
}
```

If you fail to provide the necessary information for us to reproduce the issue, we may reject your bug report.

**RoaringBitmap version:**
        
        <dependency>
            <groupId>org.roaringbitmap</groupId>
            <artifactId>RoaringBitmap</artifactId>
            <version>1.3.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.roaringbitmap</groupId>
            <artifactId>bsi</artifactId>
            <version>1.3.0</version>
        </dependency>

Please report bugs after testing the latest version of the library. If you are using an older version of the library, please explain.

Make sure to compare your version against the latest available version at https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap

**Java version:**
jdk-1.8.jdk

Please tell us which Java version you are using.

**Result snapshot**
![image](https://github.com/user-attachments/assets/6652127b-6162-4831-99b0-4afb37fc1bb3)

**Comment by lemire** [comment]
@iszhangpch and @zhangpeicheng : can you check this out?

**Comment by iszhangpch** [comment]
> @iszhangpch and @zhangpeicheng : can you check this out?

OK, I will check it.

**Comment by lemire** [comment]
@iszhangpch Thanks!

**Comment by linlin994395** [comment]
> > @iszhangpch and @zhangpeicheng : can you check this out?
> 
> OK, I will check it.

How is the progress?

**Comment by iszhangpch** [comment]
> > > @iszhangpch and @zhangpeicheng : can you check this out?
> > 
> > 
> > OK, I will check it.
> 
> @iszhangpch How is the progress?

I'm trying to locate and fix the problem, but I'm a little busy lately so it might be a little slower.
