### ISSUE TITLE
MutableBitSliceIndex topk bug

### ISSUE THREAD

**Issue by Tan-JiaLiang** [RoaringBitmap/RoaringBitmap#745]
**Describe the bug**
topK method may throw `bugs found when compute topK` exception when value in low cardinality.

**To Reproduce**

For example
```Java
@Test
public void testTopK() {
    MutableBitSliceIndex bsi = new MutableBitSliceIndex();
    bsi.setValue(1, 1);
    bsi.setValue(2, 1);
    bsi.setValue(3, 1);
    bsi.setValue(4, 1);
    bsi.setValue(5, 1);
    MutableRoaringBitmap top = bsi.topK(null, 1);
    System.out.println(top);
}
```

`java.lang.RuntimeException: bugs found when compute topK`

**RoaringBitmap version:** 1.3.0

**Java version:** JDK8

**Comment by Tan-JiaLiang** [comment]
Hi, @Smallhi Can you please take a look?

**Comment by lemire** [comment]
There will be a fix in the next release.
