### ISSUE TITLE
Publishing to JitPack

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#750]
We are currently not publishing to JitPack. It would be quite useful for our users to do.

[The documentation suggests that it is rather easy](https://docs.jitpack.io/building/).

[Here is the latest error log from JitPack](https://jitpack.io/com/github/RoaringBitmap/RoaringBitmap/1.3.12/build.log):

```
 ⚠️   WARNING:
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.
 See the documentation and examples: https://docs.jitpack.io

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/roaringbitmap/build.gradle.kts' line: 14

* What went wrong:
java.lang.UnsupportedClassVersionError: org/javamodularity/moduleplugin/ModuleSystemPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/javamodularity/moduleplugin/ModuleSystemPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 833ms
Running: ./gradlew -Pgroup=com.github.RoaringBitmap -Pversion=1.3.12 publishToMavenLocal
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/roaringbitmap/build.gradle.kts' line: 14

* What went wrong:
java.lang.UnsupportedClassVersionError: org/javamodularity/moduleplugin/ModuleSystemPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/javamodularity/moduleplugin/ModuleSystemPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by lemire** [comment]
Fixed https://jitpack.io/#RoaringBitmap/RoaringBitmap

Thanks to @cmacdonald

**Comment by ChicChip** [comment]
how can i get bsi jar from jitpack, when i use 
`<dependency>
            <groupId>com.github.RoaringBitmap.RoaringBitmap</groupId>
            <artifactId>roaringbitmap</artifactId>
            <version>1.3.15</version>
        </dependency>` 
i can get roaringbitmap jar but when i use 
`<dependency>
            <groupId>com.github.RoaringBitmap.RoaringBitmap</groupId>
            <artifactId>bsi</artifactId>
            <version>1.3.15</version>
        </dependency>`
it doern't work

**Comment by lemire** [comment]
@ChicChip 

For a reason that I do not understand, 1.3.15 is missing bsi. However version 1.3.16 should work just fine:

```xml
	<dependency>
	    <groupId>com.github.RoaringBitmap.RoaringBitmap</groupId>
	    <artifactId>roaringbitmap</artifactId>
	    <version>1.3.16</version>
	</dependency>
	<dependency>
	    <groupId>com.github.RoaringBitmap.RoaringBitmap</groupId>
	    <artifactId>bsi</artifactId>
	    <version>1.3.16</version>
	</dependency>
```

**Comment by ChicChip** [comment]
When I use `<version>1.3.16</version> ` even roaringbitmap can't load, so weired

**Comment by lemire** [comment]
@ChicChip 

We have a complete project example with both gradle and maven tests in CI:

https://github.com/RoaringBitmap/JitPackRoaringBitmapProject

Please clone it and try building it. If that does not work, please open an issue there.

Note that the project runs successfully using GitHub actions on GitHub's servers. It also runs on my machines.

**Comment by lemire** [comment]
@ChicChip Please be specific when you mean 'can't load'. The jar files are definitively online.
