### ISSUE TITLE
Suggested persistence strategy ?

### ISSUE THREAD

**Issue by kk00ss** [RoaringBitmap/RoaringBitmap#76]
Hello. I assume that memory mapped bitmaps are read-only.
(Because otherwise it will involve managing free space in a map and so forth)
If my assumption is correct - I'm thinking about creating a sequence of mutable bitmaps (each of the equal size (number of bits represented)) and saving those that were changed at particular time interval after bitmap optimization in key-value storage. 
Does this approach make sense ? Thanks

**Comment by lemire** [comment]
> I assume that memory mapped bitmaps are read-only.

Yes. They are. I think that the name (```ImmutableRoaringBitmap```) suggests that it is the case.

> If my assumption is correct - I'm thinking about creating a sequence of mutable bitmaps (each of the equal size (number of bits represented)) and saving those that were changed at particular time interval after bitmap optimization in key-value storage.  Does this approach make sense ? Thanks

Using memory mapping may or may not be the right choice. Have you run benchmarks for your use case?

**Comment by kk00ss** [comment]
Sorry for bothering you, compression ratio makes it almost free to write the whole bitmap to disk every time I need to. It's wonderful.
