### ISSUE TITLE
Memory usage issues

### ISSUE THREAD

**Issue by stile1201** [RoaringBitmap/RoaringBitmap#77]
Hi,

I've been using EWAH to manage my bitmap indices for some time. Thought I'd take a look at switching to Roaring, but am running out of heap space and/or hitting the GC overhead limit.

Test code to reproduce (scenario is building an index of 5 million rows over a column with 10000 distinct values - one bitmap per value):

    @Test
    public void testRoaring() throws Throwable {
        final RoaringBitmap[] bitmaps = new RoaringBitmap[10000];
        for (int i = 0; i < 10000; i++) {
            bitmaps[i] = new RoaringBitmap();
        }
        final Random random = new Random();
        for (int i = 0; i < 5000000; i++) {
            final int x = random.nextInt(10000);
            bitmaps[x].add(i);
        }
    }

The equivalent using EWAH runs without problem in just over a second.

Is the problem in Roaring, or am I using it incorrectly?

Thanks in advance for your help.

**Comment by lemire** [comment]
Interesting stress test. Let us try it out.

**Comment by lemire** [comment]
Please upgrade to 0.6.3. Things should be fine then.

You triggered a bug that I had created.

c.c. @owenkaser 

Reopen if you cannot verify.

**Comment by stile1201** [comment]
Yep, that's fixed it. Thanks for the swift resolution, and keep up the great work!
