### ISSUE TITLE
AND/OR of bitmaps within a range

### ISSUE THREAD

**Issue by kishoreg** [RoaringBitmap/RoaringBitmap#78]
Currently And/or are evaluated on the entire range. In some cases we know that we only care about the result for give range start to end. Similar to flip interface, it will be great to have something like

or(ImmutableRoaringBitmap... bitmaps, int rangeStart, int rangeEnd)
and(ImmutableRoaringBitmap... bitmaps, int rangeStart, int rangeEnd)

**Comment by lemire** [comment]
@kishoreg 

That's interesting. It is doable, certainly. It is probably less than 200 lines, not counting unit tests and benchmarks.

Would you be willing to help out in some way?

**Comment by kishoreg** [comment]
Definitely, I can write test cases. Still getting to understand the
internal data structures.

**Comment by lemire** [comment]
@kishoreg 

If you create a fork, and let me know about it, I could issue a PR on your fork with a sketch of an implementation.

**Comment by kishoreg** [comment]
https://github.com/kishoreg/RoaringBitmap here it is.

thanks,
Kishore G

**Comment by lemire** [comment]
See

https://github.com/kishoreg/RoaringBitmap/pull/1

**Comment by kishoreg** [comment]
https://github.com/kishoreg/RoaringBitmap/commit/a51db4c6ab893237b04520a4dff27f0567d2c237

Added a test case. Does not seem to work, it returns the entire range. I
will try to debug and understand the code base. Are you available on any IM?

**Comment by lemire** [comment]
I expect to be in meetings for the next few hours, but I am available through Twitter (@lemire), Google+ (https://plus.google.com/+DanielLemirePhD) and so forth. You can email me directly (lemire@gmail.com). If you get stuck, let me know, I can see if I can do some surgery on your fork.

**Comment by kishoreg** [comment]
I think I see the problem in selectRangeWithoutCopy

final MappeableContainer c = rb.highLowContainer.getContainerAtIndex(i)
                        .remove(lbStart, lbLast + 1);

Its trying to do the opposite of what we want. You probably wanted to
remove [0,lbStart) and [lbLast, infinity) right.

How do I know the end size of container.

**Comment by kishoreg** [comment]
changing that line to fixes it.
final MappeableContainer c =
containerAtIndex.and(MappeableContainer.rangeOfOnes(lbStart, lbLast + 1));

but i see another snippet here
final MappeableContainer c =
rb.highLowContainer.getContainerAtIndex(ifirst).remove(
                     lbStart,BufferUtil.maxLowBitAsInteger()+1);

Trying to understand what this is doing. I will try the test case with
larger size.

**Comment by kishoreg** [comment]
Test case seems to work for large array size as well. Does the change look
ok?

**Comment by lemire** [comment]
@kishoreg 

I'll check your code soon. Hopefully this evening. Thanks.

Note that your membership is private : https://github.com/orgs/RoaringBitmap/people/kishoreg

**Comment by kishoreg** [comment]
have some cycles to get back to this.

**Comment by lemire** [comment]
Excellent.

**Comment by lemire** [comment]
Preparing release.

**Comment by lemire** [comment]
@kishoreg 

We have a broken build. By making your tests stronger, we see that all the new functions fail.

Can you have a look if it is convenient?

c.c. @gssiyankai

**Comment by kishoreg** [comment]
Will look into later tonight.

**Comment by lemire** [comment]
Excellent.  I suspect that it is one silly code path that breaks everything... because *everything* (all functions) fail the same way (with an empty set). Could even be in the code I pushed onto you.

**Comment by kishoreg** [comment]
Is select for copy used anywhere else. The reason I ask is the code I added
is self contained.

**Comment by lemire** [comment]
``selectRangeWithoutCopy`` was introduced by your PR. Please see your diff...

https://github.com/RoaringBitmap/RoaringBitmap/pull/96/commits/353abfe31d49f0d1ecda2a29461331ad0c6ed72b

So no, ``selectRangeWithoutCopy`` is not used elsewhere and so, it could be buggy.

**Comment by lemire** [comment]
> The reason I ask is the code I added is self contained.

The test functions that your PR introduced did not unmask the bugs. I modified your functions (``testRangedOr``) so that they run more tests and this triggered the bugs.

So, yes, your code is "self-contained" in the sense that your new functions do not mix with the rest of the code in a complicated way, they are just straight additions. But these new functions are buggy... and this is shown by a slight modification of your tests:

https://github.com/RoaringBitmap/RoaringBitmap/commit/bcab708a7f6c679b108996c4a04c89434cbf07c3

**Comment by lemire** [comment]
Implemented as of version 0.6.11. We had to correct an issue with ranged removes in the process.

@kishoreg  Thanks for your valued contribution.

Closing.
