### ISSUE TITLE
Our coverage is below 90%

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#81]
We have good test coverage, but we really ought to get it above 90%.

**Comment by lemire** [comment]
c.c. @JunyuanZheng

**Comment by JunyuanZheng** [comment]
Yeah, I see that. I will try my best! :)

**Comment by lemire** [comment]
We are up nearly 0.2% thanks to you. We just need 100 additional such commits and we will get very close to 100%. ;-)

**Comment by lemire** [comment]
We made it to 80% thanks to @JunyuanZheng.

**Comment by lemire** [comment]
I think we can do and should do even better. There might be more bugs in untested code to be found.

**Comment by gssiyankai** [comment]
@lemire 
can we close this issue now ?

**Comment by lemire** [comment]
Yes. Of course. Even though our logo still lies.

Amazing work.

**Comment by gssiyankai** [comment]
Great! Regarding the badge, it might be a cache issue with your browser. I had the same problem with mine.
