### ISSUE TITLE
Implement iterator with "skipping" API

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#82]
Currently, it is not possible to iterate over only a range of values. 

It should be useful to be able to "jump" to the first integer value larger than some threshold.

Currently, we have a PeekableShortIterator internally that could be a building block for this feature.

**Comment by okrische** [comment]
Is this the same as an "getIntIterator(offset,length", where it then returns all set indexes in range?

**Comment by lemire** [comment]
I have in mind something more general that would look like this: 
http://static.javadoc.io/org.roaringbitmap/RoaringBitmap/0.6.5/org/roaringbitmap/PeekableShortIterator.html

Implementing ``getIntIterator(0,length)`` efficiently on top of our API is already possible and quite easy. Just wrap the iterator, bailing out when the value returned is too high.

The part we do not yet support, but should, is the ability to efficiently skip the first few values to make it to the first value that is at least as large as ``offset``. We have part of the underlying implementation ready (using ``PeekableShortIterator``) but we need to complete it.

It is not a very difficult project...

**Comment by okrische** [comment]
As a workaround right now i use an intermediate Bitmap, that i set up with add(rangeStart,rangeEnd), AND it with the target bitmap and then use intIterator. That is not the lightest way to do it, but works.

**Comment by lemire** [comment]
@okrische 

Yes. Skippable iterators are motivated by performance considerations, I guess, because if we just cared  about convenience, we could implement them right now as you propose.

**Comment by lemire** [comment]
@okrische  I wouldn't call what you do a "workaround". It is a fine way to do things, if it is not a performance bottleneck.

I know instances, however, where the lack of a skippable iterator is a performance problem. That's why it is on our todo.

**Comment by okrische** [comment]
Nono, i totally agree. I want to use this feature as well.

**Comment by okrische** [comment]
Maybe you can have a look, if that is what you want?

https://github.com/okrische/RoaringBitmap/commit/a67ae0f3a880435bfc67a00c971134fc52b004db

**Comment by lemire** [comment]
I'll be sure to have a good look.

**Comment by lemire** [comment]
Ok. I looked at your implement and it is good if one wants to skip the first few values. However, we can offer a more general API:

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/PeekableIntIterator.java#L11-L16

Implemented as of release 0.6.7 in part thanks to your code. 

Closing this issue, reopen if you disagree.

**Comment by okrische** [comment]
Perfectly happy with it. 

(Later i actually realized, that my code was behaving like a cursor. I could jump around within the bitmap as i wished and then iterate forward from that position.)

**Comment by lemire** [comment]
+1
