### ISSUE TITLE
Checkstyle to check roaring bitmap code

### ISSUE THREAD

**Issue by kishoreg** [RoaringBitmap/RoaringBitmap#83]
Current code is mostly hand formatted. This makes it hard to submit PR for people like me who are addicted to java IDEs.

I dont have any preference to a particular format, I will go ahead and propose using the style sheet from this project. 

https://github.com/google/styleguide

Here is the description for java. http://google.github.io/styleguide/javaguide.html. They also have style xml for IDEA and Eclipse.

**Comment by lemire** [comment]
Sounds reasonable.

@owenkaser @omirandette  @gssiyankai @gpunti  Any opinions on this issue? We would effectively be enforcing a format from this point forward.

**Comment by gssiyankai** [comment]
As the community is growing, defining a code style is definitely the way to go.
+1 for Google Java Style

**Comment by gpunti** [comment]
Yes, it sounds reasonable. +1 for any particular Java style.

**Comment by lemire** [comment]
@kishoreg  Looks like your proposal is supported.

In time, you could issue a PR with the new style. Ideally with at least some minimal documentation.

I think it is possible to enforce style checking as part of the build using ```maven-checkstyle-plugin```. That would be very handy because if we have to rely on people actually applying the style... it may not get done.

**Comment by omirandette** [comment]
I agree 100%.

I'm good with google java style.

**Comment by lemire** [comment]
+1 @omirandette

**Comment by lemire** [comment]
@kishoreg 

Do you want to propose a pull request whereas we could enforce styles and/or reformat the code? We need to assign this to someone. Will you take it on?

**Comment by kishoreg** [comment]
Hi Daniel,

I will do this over the weekend.

**Comment by lemire** [comment]
@kishoreg Excellent.

**Comment by lemire** [comment]
I have just added checkstyle. 

Whenever you run tests (or ``mvn checkstyle:check``), it should check style compliance. 

I think that Google's style is a bit too much... it triggered hundreds of silly violations. What we enforce is pretty close.

Note that testing code is not check for style... 

Anyhow. It looks like it is a resolved issue.

**Comment by lemire** [comment]
If you had uncommitted changes to master... you might suffer a bit since I had to reformat pretty much all the code. But it is one-time thing.
