### ISSUE TITLE
Roaring and memory-mapped files

### ISSUE THREAD

**Issue by stile1201** [RoaringBitmap/RoaringBitmap#91]
Hi,

I'm very interested in using memory-mapped files to back the bitmaps, and I've looked at the example code you provide along these lines, but I'm not clear whether that approach will quite work in my situation.

Is my understanding correct that this method does not allow the bitmap to be updated?

I am loading up large amounts of data at startup, and using RoaringBitmaps to create indices on the data. As the indices can become large, I am looking to store them in memory-mapped files.

However, after startup, additional data will be loaded from time to time, and the indices need to be updated accordingly.

Will your ByteBuffer implementation handle this kind of scenario?

Of course, I'd probably run into problems anyway, since ByteBuffer only handles 2^31 bytes, but that's a separate issue...

Thanks,
Nick

**Comment by lemire** [comment]
@stile1201 

A typical application for memory-file mapping is a file (or a few files) that contain several bitmaps serialized. The bitmaps might be written out sequentially, as in our examples, or stored in a B-tree. Whatever the case, if you need to update these bitmaps, the resulting bitmaps may use more or less space, so typically your data structure needs to be updated. This means that there is little hope for in-place updates of the bitmaps: They need to be read, modified and rewritten. Moreover, serialized bitmaps have no buffer room in them (they are packed densely), which means that even if we could update them in-place, we would almost surely need to rewrite most of them most of the time.

If you have a bitmap that has been serialized and you need to modify it, you can load it up (using either a ``RoaringBitmap`` or ``MutableRoaringBitmap`` instance), modify it, and then reserialize it (possibly elsewhere).

If you need to access the data, but do not need to modify it, you can use an ``ImmutableRoaringBitmap``.

If the read-modify-write scenario ends up a performance bottleneck for you, then I'd be interested in discussing it further, but I think you will find that it is quite fast in this respect... so it may not be a bottleneck after all.

**Comment by samytto** [comment]
@stile1201  @lemire 

A possible solution to avoid rewriting an entire file after the structure of a serialized bitmap has been changed, is to fragment your indexed data into blocs of a certain amount of entries and to create bitmaps per bloc of data. Blocs can typically be fragmented by time range for example. So, if your application changes bitmaps only when appending new data into the system, a bloc of data and its bitmaps once created for a specific time range will never be updated again and will be exposed on read only in the system.

Druid OLAP engine is adopting such a mecanism to handle bitmaps inside the system : http://static.druid.io/docs/druid.pdf

**Comment by lemire** [comment]
@stile1201 I will close this issue. Reopen if you want to continue the discussion.
