### ISSUE TITLE
Should one call #hasNext, before calling PeekableIntIterator#advanceIfNeeded() ?

### ISSUE THREAD

**Issue by okrische** [RoaringBitmap/RoaringBitmap#93]
When i do this on an empty bitmap,

```java
RoaringBitmap bitmap = new RoaringBitmap();
PeekableIntIterator it = bitmap.getIntIterator();
it.advanceIfNeeded(0);
```
i get a NullPointerException();

Not sure about the contract here. Should one check for hasNext() before trying to advanceIfNeeded as well? The normal next() i would not call without it.hasNext(). But the other method has this check implicitly in the name, kind of.

What is your opinion?

**Comment by lemire** [comment]
You are right. This is ugly. Fixed (I think) for the future version:

https://github.com/RoaringBitmap/RoaringBitmap/commit/a24b2dd459ce685b9b7dba57d6ba51a4a110c9e6

For now, please just prefix your call with ``if(hasNext)``. Won't be necessary with the next release.
