### ISSUE TITLE
Bug: ArrayOutOfBoundgException in PeekingShortIterator from BitmapContainer

### ISSUE THREAD

**Issue by okrische** [RoaringBitmap/RoaringBitmap#94]
Hm, there is probably a bug in the PeekingShortIterator in BitmapContainer. When using advanceIfNeeded, then sometimes i get an ArrayIndexOutOfBoundException:

```java
	@Test
	//@Ignore
	public void testIndexIterator3() throws Exception {
		try(final DataInputStream dos = new DataInputStream(new GZIPInputStream( new FileInputStream(new File("/tmp/broken.roaring.gz"))))) {
			RoaringBitmap bm = new RoaringBitmap();
			bm.deserialize(dos);
			PeekableIntIterator it = bm.getIntIterator();
			it.advanceIfNeeded(917500);
			while(it.hasNext()) {
				it.next();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
```
```
java.lang.ArrayIndexOutOfBoundsException: 1025
	at org.roaringbitmap.BitmapContainerShortIterator.nextAsInt(BitmapContainer.java:1338)
	at org.roaringbitmap.RoaringBitmap$RoaringIntIterator.next(RoaringBitmap.java:75)
```

Maybe due to advanceIfNeeded, x got already incremented and is getting incremented again in nextAsInt, thus the (x == bitmap.length) will no longer trigger the break. Maybe x >= bitmap.length will already fix it.

[broken.roaring.gz](https://github.com/RoaringBitmap/RoaringBitmap/files/182971/broken.roaring.gz)

**Comment by lemire** [comment]
Right. I think that this is already fixed in HEAD.  I am going to produce a release soon.

**Comment by okrische** [comment]
Do you have another HEAD? The one visible to me would only fix the problem with empty bitmaps.

**Comment by lemire** [comment]
I am going to close this issue. Reopen if you can verify with the new release.

**Comment by lemire** [comment]
@okrische 

Can you please provide a reproducible test case on the latest release?

I have added tests the do an advanceUntil followed by a next and I see no problem: 

https://github.com/RoaringBitmap/RoaringBitmap/commit/f075cedcc4ca978d97d2eb8f40819ac15946e5ab

**Comment by okrische** [comment]
This is what a problematic area, that i extracted from the previously attached bitmap:

```java
	@Test
	public void testIndexIterator4() throws Exception {
		RoaringBitmap b = new RoaringBitmap();
		for (int i = 909440; i < 917498; i++) {
			b.add(i);
		}
		PeekableIntIterator it = b.getIntIterator();
		if (it.hasNext()) {
			it.advanceIfNeeded(917500);
			while (it.hasNext()) {
				it.next();
			}
		}
	}
```

**Comment by lemire** [comment]
Excellent.

**Comment by lemire** [comment]
Working on pushing a new release. Thanks.

**Comment by okrische** [comment]
I thank!

**Comment by lemire** [comment]
@okrische  Please keep the bug reports coming!
